### ISSUE TITLE
Indentation for a specific paragraph

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#101]
Is there an option to set an indentation for a specific paragraph? 
When something like [indent=2] is used in asciidoc, no indentation changes are applied.

In the example shown in the following image, colon is also missing after the word "where", and I didn't manage to figure out why.

![image](https://user-images.githubusercontent.com/55683568/67632770-65f10800-f8a8-11e9-8311-b43630cf8ea8.png)

[indent.zip](https://github.com/metanorma/metanorma-itu/files/3775694/indent.zip)

**Comment by opoudjis** [comment]
No, we do no support indents on paragraphs. (We will add mathematical statements, and already support blockquotes, both of which are indented, but neither of which apply here.)

The added complication here is that this is not even a paragraph, but a definition list. We expect definition lists after formulas, and we could in fact indent all such definition lists --- if in fact all definition lists after formulas are indented. But part of what we want to do is regularise formatting, not encourage idiosyncracy. So I'd need to know what the expected indentation of definition lists after formulae in general is.

**Comment by opoudjis** [comment]
The where colon is missing, because the "where" text is actually supplied automatically in rendering, rather than being part of the XML content: it is treated as a connective between the formula and the following definition list, and stripped from the source. I will put the colon back in.

**Comment by ronaldtse** [comment]
Do we have documentation on metanorma.com for this? I don’t remember where we document the “Where” definition list syntax...

**Comment by opoudjis** [comment]
https://www.metanorma.com/author/topics/document-format/text/

> Formulae are marked up as [stem] blocks. Any explanation of symbols in the formula is given as a “where” paragraph, followed by a definition list.

**Comment by ronaldtse** [comment]
@opoudjis can you give me a sample file for the "Where" indent so I can ask ITU? Thanks.

**Comment by opoudjis** [comment]
G 650, 6.1.4.1.

**Comment by ronaldtse** [comment]
@opoudjis I have sent a request to clarify. Will report back.

**Comment by ronaldtse** [comment]
ITU's answer to the list after "where:":

> I would say that in case of a list, we can indent to the position of the next character after the semicolon. That would be 1.4 cm or so.

**Comment by opoudjis** [comment]
Luckily, I've just done https://github.com/metanorma/metanorma-iso/issues/303 to deal with the indentation of the "where:".
