### ISSUE TITLE
Changing numbering style

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#102]
Is there an option to change a numbering style for a specific list? 
When [arabic] style is specified in asciidoc, there is no change in numbering (loweralpha is applied).

![image](https://user-images.githubusercontent.com/55683568/67633069-85d5fb00-f8ab-11e9-8ffb-16919f2e6ec5.png)

[numbering_lists.zip](https://github.com/metanorma/metanorma-itu/files/3775716/numbering_lists.zip)

**Comment by ronaldtse** [comment]
@anermina thanks for reporting this. When you post an example could you also provide the exact document / Recommendation number for reference? Thanks!

**Comment by opoudjis** [comment]
Yes, we have inherited behaviour from ISO, where we expressly do not want numbering respected, because of uniformity requirements there. I can relax that constraint in the general case for Metanorma, but do we have explicit indication from ITU that they can arbitrarily vary numbering between lists? Right now, this still looks to me like a bug and not a feature...

**Comment by ronaldtse** [comment]
@opoudjis @anermina I've sent out a request to clarify. I do not think the numbering style of numbered lists should be up to the author.

**Comment by anermina** [comment]
The initial example was from G.650 recommendation.

However, similar applies to "EDITING GUIDELINES" (Author’s guide for drafting ITU-T Recommendations):
![image](https://user-images.githubusercontent.com/55683568/67639157-bc803580-f8ec-11e9-9a43-684c81f22479.png)
![image](https://user-images.githubusercontent.com/55683568/67639162-d28df600-f8ec-11e9-86c0-fb65144a70fd.png)
![image](https://user-images.githubusercontent.com/55683568/67639169-ecc7d400-f8ec-11e9-8386-2310cf232b32.png)
![image](https://user-images.githubusercontent.com/55683568/67639184-08cb7580-f8ed-11e9-807c-a7d668b2119a.png)
![image](https://user-images.githubusercontent.com/55683568/67639189-184abe80-f8ed-11e9-86ed-68730e3790af.png)

...as well as to Y.3507:
![image](https://user-images.githubusercontent.com/55683568/67639252-eab24500-f8ed-11e9-9cb8-b86b3d6ba718.png)

**Comment by ronaldtse** [comment]
Confirmed with ITU:

> We could standardize per the Author’s guide:
> “One-level-only lists may be separated with dashes, bullets or numbers:
> –           first item;
> –           second item;
> –           etc.

>  When sub-lists appear within a list as a second level, main levels, at least, should be numbered:
> a)          first item:
>   i)    first sub-item;
>   ii)   second sub-item.
> b)         second item:
>   i)    first sub-item;
>   ii)   second sub-item.”
 
> Note, however, that sometimes authors would need to use numbers for the steps of a given process. E.g.
> 1)      Step 1
> 2)      Step 2
> 3)      Etc.

I wonder if we should have a separate style for "steps"?

**Comment by opoudjis** [comment]
We have two options: allow open-ended numbering choice for ordered lists; or allow a type of ordered list as "steps", and enforce arabic numbers as the numbering for just that type of list.

Yes, we will pick the latter option. @anermina, when this task as done, please change all lists with numbers instead of letters to be:

````
[class=steps]
. Step 1
. Step 2
````

We're calling it class instead of type, because the type is already used for arabic, alphabetic, roman etc, and it's a different category of classification.

**Comment by ronaldtse** [comment]
@opoudjis this is a good choice. Not sure if we can simplify further to just [steps] but good enough...

**Comment by ronaldtse** [comment]
And @opoudjis before I forget, this needs to be documented on metanorma.com

**Comment by opoudjis** [comment]
It already has been, it's one of the PRs on metanorma.com. Again, just assume i document as I implement these things.

**Comment by opoudjis** [comment]
Need to implement separately for Word.

**Comment by opoudjis** [comment]
This is going to need extensions to html2doc, since that gem has hardcoded the presumption that there is only one list style (i.e. numbering) for unnumbered and for numbered lists.

**Comment by opoudjis** [comment]
In HTML2Doc, the :ul and :ol classes apply only to lists with no top-level CSS class, or with a class not named as a parameter. If we pass liststyles with values other than `:ul, :ol`, they are CSS classes at the top level that the nominated list style applies to recursively.

**Comment by opoudjis** [comment]
To get this ticket working before next gem release (next weekend), add the following to your Gemfile:

`gem "html2doc", git: "https://github.com/metanorma/html2doc"`
