### ISSUE TITLE
Font size of a list in a multi-paragraph note

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#103]
Font size of an items list in a multi-paragraph note is bigger than it should be. 

Example (G.650 recommendation):
![image](https://user-images.githubusercontent.com/55683568/67639705-30254100-f8f3-11e9-8e1c-f1e9c543535f.png)
[multi-paragraph_note.zip](https://github.com/metanorma/metanorma-itu/files/3776269/multi-paragraph_note.zip)

**Comment by opoudjis** [comment]
This is an issue we have already seen elsewhere: because Word CSS is not as flexible as normal CSS, it is not capturing the embedding of blocks within other blocks, and the resulting font size change. (Cf. https://github.com/metanorma/metanorma-itu/issues/90)

Fixed.
