### ISSUE TITLE
Notes numbering

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#105]
In case notes are not written one after the other in .adoc file (in case there is some text between the notes), it seems that numbering is restarted.

Example from G.650 recommendation:
![image](https://user-images.githubusercontent.com/55683568/67641219-e17ea380-f900-11e9-9807-db8b6f7b0d42.png)

[notes_numbering.zip](https://github.com/metanorma/metanorma-itu/files/3776358/notes_numbering.zip)

**Comment by opoudjis** [comment]
Oh this is a horrid bug.

The first two notes are assumed to belong to the formula, the third is not. Which is fine, but irrelevant to numbering: numbering should be governed only by clauses as containers. I'll need to work out why this is happening.

**Comment by opoudjis** [comment]
... Oh. That was actually a deliberate coding decision, that's been embedded in isodoc for the past couple of years.

In the latest draft of ISO/IEC DIR 2, the notes within a table or a figure are numbered separately. There is no such requirement for formulas or examples, and I will remove that requirement from isodoc.

**Comment by opoudjis** [comment]
This is assuming an ISO default. If ITU overrides this explicitly, we will change behaviour accordingly.

**Comment by ronaldtse** [comment]
@opoudjis are you meaning to have this clarified by ITU? Or is this just closed?

**Comment by opoudjis** [comment]
No need, the original assumption for isodoc that formulas can have notes of their own, with a distinct numbering sequence, was unwarranted.
