### ISSUE TITLE
From ITU: Notes have a `ndash` after number, font size 11

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#108]
From ITU.

- Notes are font size 11
- Notes are shown always with an `ndash` after the number (or when there is no number, after NOTE)

**Comment by opoudjis** [comment]
Notes are already size 11.

Made Note Label also be size 11.

The Editing Guidelines say em dash, but use en dash. I will use en dash, but the Editing Guidelines need to be corrected. @ronaldtse please pass on to ITU.
