### ISSUE TITLE
From ITU: References have duplicated ITU name

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#109]
Correct (original)
![1- following ITU-T Recommendations and other references contain provisions which, through](https://user-images.githubusercontent.com/11865/67963596-28211600-fbff-11e9-819d-18601aa8f01f.jpeg)

Incorrect (asciidoc)

![2507-201612 (h),dge • Worl](https://user-images.githubusercontent.com/11865/67963605-2bb49d00-fbff-11e9-87f5-331e525a1674.jpeg)

**Comment by manuel489** [comment]
Already fixed

![capture5](https://user-images.githubusercontent.com/33627611/67995581-865ef080-fc21-11e9-8911-85a5c608ee7e.JPG)
