### ISSUE TITLE
From ITU: Unnumbered list uses `ndash`es

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#110]
From ITU: Unnumbered list uses `ndash`es

Currently they are `mdash`es.

**Comment by opoudjis** [comment]
Not in their documents they're not.

I am not going to action any of your barrage of tickets until I've been through their editorial guide.

**Comment by ronaldtse** [comment]
> Not in their documents they're not.

This is directly from ITU.

**Comment by ronaldtse** [comment]
> I am not going to action any of your barrage of tickets until I've been through their editorial guide.

Feel free to go through the "Author's guide", but point is all these tickets are from an in-person side-by-side comparison, raised by ITU's chief editor.

**Comment by opoudjis** [comment]
<img width="331" alt="Screen Shot 2019-11-01 at 09 43 03" src="https://user-images.githubusercontent.com/1911039/67999625-40516d80-fcb1-11e9-92de-e7b398eb5039.png">

Already fixed.
