### ISSUE TITLE
From ITU: Remove year from reference number tag textual reference, year is already in reference

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#111]
From ITU.

Remove year from reference number tag textual reference, year is already in reference.

Correct (original)
![1- following ITU-T Recommendations and other references contain provisions which, through](https://user-images.githubusercontent.com/11865/67963775-72a29280-fbff-11e9-9f8f-e3096fa8e132.jpeg)

Incorrect (MN)
![2507-201612 (h),dge • Worl](https://user-images.githubusercontent.com/11865/67963766-6fa7a200-fbff-11e9-807c-76474ad639a3.jpeg)

**Comment by manuel489** [comment]
Fixed already

![capture5](https://user-images.githubusercontent.com/33627611/67995332-40555d00-fc20-11e9-9959-46def493b9f8.JPG)
