### ISSUE TITLE
From ITU: Appendix "header text" should be centered

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#112]
The sentence "The appendix does not..." should be centered.

![Appendix 1](https://user-images.githubusercontent.com/11865/67963828-89e18000-fbff-11e9-9d97-f71bee282da4.jpeg)

**Comment by manuel489** [comment]
Already fixed

![capture6](https://user-images.githubusercontent.com/33627611/67995443-cec9de80-fc20-11e9-8649-f5b427e68762.JPG)
