### ISSUE TITLE
From ITU: all single, double quotes and apostrophes should be "straight"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#115]
i.e. no clever handling of quotes. In fact, maybe the smartness should be reversed so that the quotes are always "straight".

All single, double quotes and apostrophes must be "straight".

**Comment by opoudjis** [comment]
The smartness is the right default to have, and in fact is inherent to Asciidoc anyway. I will override it, but it will be fiddly. It may be simpler just to do global replace of smart with simple dumb quotes on XML output.

**Comment by ronaldtse** [comment]
> It may be simpler just to do global replace of smart with simple dumb quotes on XML output.

Can do.

**Comment by opoudjis** [comment]
I'd forgotten: we have `:smartquotes:` defaulting to true in Metanorma. We'll just default it to false.

**Comment by ronaldtse** [comment]
@opoudjis sure, for the ITU version. However, we probably should also enforce this, e.g.

1. people write adoc smartquotes (`` "` ``) .
2. people who paste in unicode quotes (https://unicode-table.com/en/sets/quotation-marks/)

**Comment by opoudjis** [comment]
That's... peremptory. OK.

I've also found that while asciidoctor can be prevented from smartquoting quotes, it's still making apostrophes smart. So will need to make some changes to metanorma-standoc as well.

**Comment by opoudjis** [comment]
From the User Manual:

> When entered with the ' key, Asciidoctor renders an apostrophe that is directly preceded and followed by a character, such as in contractions and possessive singular forms, as a curved apostrophe. This inconsistent handling of apostrophes and quotation marks is a hold over from the original AsciiDoc processor. An apostrophe directly bounded by two characters is processed during the replacements substitution phase, not the quotes phase. This is why an apostrophe directly followed by white space, such as the possessive plural form, is not curved by default.

That's... unpleasant.

In metanorma-standoc, if smartquotes is off, I have to undo that particular substitution. Moreover, while the user manual claims that substitution does not happen in headings, it does. The substitution is:

````
CC_ALPHA = CG_ALPHA = '\p{Alpha}'
CC_ALNUM = CG_ALNUM = '\p{Alnum}'
# apostrophe (inside a word)
[/(#{CG_ALNUM})\\?'(?=#{CG_ALPHA})/, '&#8217;', :leading],
````
