### ISSUE TITLE
From ITU: Reference tags for double ITU PubIDs and Common Text docs

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#117]
References tags should only have first document identifier.

This occurs in the case of:
- double ITU PubIDs (should only use first one as tag)
- common text (with ISO/IEC) (should only use ITU one as tag)

Correct:

![1- following ITU-T Recommendations and other references contain provisions which, through](https://user-images.githubusercontent.com/11865/67967141-586bb300-fc05-11e9-8703-1dfc42b241b2.jpeg)

Incorrect:

![2507-201612 (h),dge • Worl](https://user-images.githubusercontent.com/11865/67967157-5efa2a80-fc05-11e9-8733-3111554c0feb.jpeg)

**Comment by manuel489** [comment]
Already fixed

![capture5](https://user-images.githubusercontent.com/33627611/67995953-8364ff80-fc23-11e9-8d81-90caf019fc27.JPG)
