### ISSUE TITLE
From ITU: Reference tag should not include year

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#118]
Reference tag should not include the year or the date of publication.

Correct:

![1- following ITU-T Recommendations and other references contain provisions which, through](https://user-images.githubusercontent.com/11865/67967204-7cc78f80-fc05-11e9-893d-cdda5a26032e.jpeg)

Incorrect:

![2507-201612 (h),dge • Worl](https://user-images.githubusercontent.com/11865/67967211-80f3ad00-fc05-11e9-92c0-e055e6c5c9d1.jpeg)

**Comment by opoudjis** [comment]
Already fixed

![image](https://user-images.githubusercontent.com/1911039/67999705-7c84ce00-fcb1-11e9-8536-9164a4d323d9.png)
