### ISSUE TITLE
From ITU: References always ends with a period, and the front portion is not italicized

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#119]
References always ends with a period, and the front portion is not italicized.

Correct:

![1- following ITU-T Recommendations and other references contain provisions which, through](https://user-images.githubusercontent.com/11865/67967264-98cb3100-fc05-11e9-9bd2-a54bed311c03.jpeg)

Incorrect:

![2507-201612 (h),dge • Worl](https://user-images.githubusercontent.com/11865/67967269-9c5eb800-fc05-11e9-9f93-4392f2815eb3.jpeg)

**Comment by manuel489** [comment]
Already fixed

![capture5](https://user-images.githubusercontent.com/33627611/67995774-a17e3000-fc22-11e9-8fd2-0b9a59463ef9.JPG)
