### ISSUE TITLE
From ITU: Terms and definitions formatting issues

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#120]
Terms and definitions reference (the source) should not be in bold.

Term and definition must be on the same line.

Terms and definitions NOTE single note should not be numbered.

Terms and definitions the definition always needs period and also start with capital. Term is always in lowercase.

**Comment by opoudjis** [comment]
> Term and definition must be on the same line.

Already fixed.

<img width="616" alt="Screen Shot 2019-11-06 at 23 28 56" src="https://user-images.githubusercontent.com/1911039/68298369-4b5f3000-00ed-11ea-9d7a-41cf8ef9fc61.png">

**Comment by opoudjis** [comment]
> Terms and definitions reference (the source) should not be in bold.

Already fixed.

<img width="616" alt="Screen Shot 2019-11-06 at 23 30 34" src="https://user-images.githubusercontent.com/1911039/68298443-78abde00-00ed-11ea-8e53-60fff8608719.png">

**Comment by opoudjis** [comment]
> Terms and definitions NOTE single note should not be numbered.

The editors have missed this one. Fixed, rendering same as Notes. (This was behaviour inherited from ISO.)

> Terms and definitions the definition always needs period and also start with capital. Term is always in lowercase.

These are not formatting, they are validation rules, and enforcing case is not something I'm prepared to do --- we have not done it in ISO. I will add validation rules, which is what we have done in ISO.

**Comment by ronaldtse** [comment]
> These are not formatting, they are validation rules, and enforcing case is not something I'm prepared to do --- we have not done it in ISO. I will add validation rules, which is what we have done in ISO.

Yes, validation rules are good. We should not be enforcing case or adding periods. Thanks.
