### ISSUE TITLE
From ITU: some lists are missing tabulation/indentation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#121]
See the list above 6.5.3

![Add-ins](https://user-images.githubusercontent.com/11865/67967498-f95a6e00-fc05-11e9-8106-0288518be057.jpeg)

**Comment by manuel489** [comment]
It is fixed already.

![capture4](https://user-images.githubusercontent.com/33627611/67995124-3a12b100-fc1f-11e9-94d4-acd197d3b20c.JPG)

**Comment by opoudjis** [comment]
This is a markup error: the initial dashes in the list were not recognised as a true list. (Presumably poor styling in the original.)
