### ISSUE TITLE
From ITU: Clause titles and numbers formatting

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#122]
Clause numbers do not end with a period (remove fullstop)

There should be some indentation between the clause number and clause title.

Incorrect:
![Add-ins](https://user-images.githubusercontent.com/11865/67967576-1e4ee100-fc06-11e9-8b6f-7147cef3460b.jpeg)

**Comment by manuel489** [comment]
It is fixed already.

![capture4](https://user-images.githubusercontent.com/33627611/67995234-cf15aa00-fc1f-11e9-919a-727bfd4d934a.JPG)
