### ISSUE TITLE
Strikethrough, color change and table borders

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#124]
In ITU-T Editing Guidelines, following figure is included:
![image](https://user-images.githubusercontent.com/55683568/68088346-9d3e5680-fe5e-11e9-91b4-7c1eade94567.png)

These kind of figures are converted into tables using reverse_adoc, which usually gives similar output. However, this figure includes red color and a strikethrough, which is deprecated in Asciidoc. 

For now, I've just applied different font to differentiate this sentence from the rest of them. Do you have a suggestion on how to make this as similar to the original as possible?
![image](https://user-images.githubusercontent.com/55683568/68088416-5ac94980-fe5f-11e9-9855-b79d0df7f564.png)

It can also be seen that all table borders are kept in the rendered document, i.e. that [frame = none] is ignored. Is there an option to remove all or some of the table borders?
[strike-border.zip](https://github.com/metanorma/metanorma-itu/files/3801784/strike-border.zip)

**Comment by opoudjis** [comment]
Strikethrough has been scheduled for future inclusion into Metanorma. I have no problem moving that forward.

Red colour is actually typically included with strikethrough in markup of deletions. For now, I propose that all rendering of strikethrough be red; but if ITU wants to actually treat this as deletion markup, we will need to add a deletion element to ITU (and an addition element), and mark them up separately. @ronaldtse Please ask ITU what their approach to deletion/addition markup is.

We are as you know allergic to extraneous markup, and I think in this instance this is not a table at all, and should not be data-entered as one. They entered it in Word as a table, but I think we should treat this as a figure or block quote. Let me investigate alternatives.

**Comment by opoudjis** [comment]
Yes, they only realised this as a table because it gave them a border (which we will not preserve in our rendering anyway). This should indeed instead be entered as an example. (We reserve figures for images and Ascii art, and renaming such examples as these into figures would be... difficult.)

**Comment by opoudjis** [comment]
The strikethrough and additions are in fact all about deletions and additions; so rather than just introduce colours and strikethroughs, I will be introducing macros to flag text as deleted or added, as additions to ITU markup.

**Comment by anermina** [comment]
Thanks @opoudjis . Should examples be numbered? There are three of them in total in the document, but all of them are in different sections and they are all currently referred to as "EXAMPLE".
![image](https://user-images.githubusercontent.com/55683568/68160176-79107180-ff53-11e9-8835-859764a3fe32.png)

**Comment by opoudjis** [comment]
The macros shall be `[add]#...#` and `[del]#...#`. So the foregoing would be marked up as:

````
[del]#The use of echo cancellers on the VBD channel, as per Rec. ITU-T G.168.#

... or other forms of redundancy [add]#(e.g. per <<rfc2198>>)#
````

I need to confirm whether Asciidoctor can deal with crossreferences embedded within markup quotes.
