### ISSUE TITLE
Size of the footnote reference number

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#126]
Footnote reference number is smaller than it should be. This applies to the footnotes in regular text, not the ones included in the tables.

Original (from ITU-T Editing Guidelines):
![image](https://user-images.githubusercontent.com/55683568/68091380-409f6380-fe7f-11e9-8b1b-78a0ea7a16ab.png)

Rendered:
![image](https://user-images.githubusercontent.com/55683568/68091370-2feeed80-fe7f-11e9-81cf-de41689bf93e.png)

(Reference number is different here because the first footnote is set in the title on the page with Scope, References and Definitions, which is mentioned in #98 )

[footnote_rn.zip](https://github.com/metanorma/metanorma-itu/files/3802084/footnote_rn.zip)

**Comment by opoudjis** [comment]
Difference in the Word stylesheet. Fixed.
