### ISSUE TITLE
Different indentation for lists

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#127]
Different list types (depending on whether "*" or "." is used in .adoc) have different indentation.

Original (from ITU-T Editing Guidelines):
![image](https://user-images.githubusercontent.com/55683568/68091574-bc021480-fe81-11e9-8238-a4fe41582c3e.png)

Rendered:
![image](https://user-images.githubusercontent.com/55683568/68091578-c4f2e600-fe81-11e9-9bac-4e373aa86abe.png)

[lists_indent.zip](https://github.com/metanorma/metanorma-itu/files/3802100/lists_indent.zip)

**Comment by ronaldtse** [comment]
Thanks for reporting @anermina !

**Comment by opoudjis** [comment]
And as it happens, the sequence of nested list numbers is different in ITU: a) i) not a) 1). Now, the Editing Guidelines themselves switch from a) to i) as the first level list number (B.3.2), and we've already had communication from ITU that we need not respect that outside of steps lists.
