### ISSUE TITLE
Centering in the lists

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#129]
Is there an option to center a line of the text in the list? [align=center] is ignored when it is used in the lists.

Original (from ITU-T Editing Guidelines):
![image](https://user-images.githubusercontent.com/55683568/68091833-fa4d0300-fe84-11e9-8e83-901f204da58d.png)

Rendered:
![image](https://user-images.githubusercontent.com/55683568/68091827-f0c39b00-fe84-11e9-8323-bbeae41b9efb.png)

[list_centering.zip](https://github.com/metanorma/metanorma-itu/files/3802120/list_centering.zip)

**Comment by opoudjis** [comment]
Bad markup. What you want is:

````
* Recommendation ITU-T X.1206 (2008), _A vendor-neutral framework for automatic notification of security related information and dissemination of updates_.
+
[align=center]
*http://www.itu.int/xml-namespace/itu-t/x.1206/core/*
````

The plus for list continuation needs to appear on a separate line.
