### ISSUE TITLE
A.8: Untitled clauses appearance and differences from original DOC

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#134]
In A.8 document, a lot of untitled clauses are used. They are all written in the format "=== {blank}" in .adoc, but there are some issues:
1. Untitled clauses shouldn't appear in Table of Contents
2. Font of the content of untitled clauses is bigger than in the original document
3. Content starts below the clause number in rendered .doc, while it starts in the same line in the original document

In the attached example, another two issues can be seen:
- "Source" section should be rendered on the same page as "Summary" (preface, right after the front page), but it's not. Is there a way to force it to the right position? 
- Subtitle "(2000; 2004; 2006; 2008)" should be added on the first page after ToC. Should this be added automatically or there is a way to make a proper mark-up for subtitles?

Original document:
![image](https://user-images.githubusercontent.com/55683568/69284897-f98bcf00-0bef-11ea-982b-02b72371165b.png)

Rendered:
![image](https://user-images.githubusercontent.com/55683568/69284973-217b3280-0bf0-11ea-8354-b3f7a399eeee.png)

[a8_example.zip](https://github.com/metanorma/metanorma-itu/files/3871894/a8_example.zip)

**Comment by ronaldtse** [comment]
@anermina @opoudjis let me ask ITU for the definitive answer. Hang on.

**Comment by opoudjis** [comment]
There is provision in Metanorma for dealing with headers on the same line: Inline headings, https://www.metanorma.com/author/topics/document-format/sections/#inline-headings

So:

````
[%inline-header]
== {blank}
In accordance with...
````

should render correctly. But yes, @ronaldtse, if this is to be universally applied with blank headings, then we might as well deal with this in code.

**Comment by ronaldtse** [comment]
I think it is a misnomer to call these “blank sections” because they are numbered paragraphs. How about we have a syntax for indicating a section (and its tree) has numbered paragraphs?  

In addition, the other document element type we have to handle in ITU is “resolution” which also has a slightly different format.

**Comment by opoudjis** [comment]
These are absolutely not numbered paragraphs: 1.1 contains two paragraphs.

@ronald This query is stuck pending you, and I'm not sure why. Have you discussed this with ITU? I'm more concerned with the random discrepancies around Source and Subtitle; do these recur in ITU Recommendations?

**Comment by ronaldtse** [comment]
> This query is stuck pending you

This is news to me. 

> 1.1 contains two paragraphs

This is a formatting concern, not a semantic concern. To address your complaint let's call this a CLAUSE then.

>  I'm more concerned with the random discrepancies around Source and Subtitle; do these recur in ITU Recommendations?

Explain please. Yes.

**Comment by opoudjis** [comment]
> This is news to me.

ronaldtse commented on 22 Nov 2019
@anermina @opoudjis let me ask ITU for the definitive answer. Hang on.

So there is no more clarification coming from ITU, and these are to be treated as inline headers of clauses, then, yes?

**Comment by anermina** [comment]
One update to the ticket: I tried with the following syntax:

> [%inline-header]
> == {blank}
> In accordance with...

However, text was still generated after the clause number, and appeared in ToC:
Generated:
![image](https://user-images.githubusercontent.com/55683568/81440215-f1a8f280-916f-11ea-812c-1f2b84c08a1e.png)
![image](https://user-images.githubusercontent.com/55683568/81441853-cb388680-9172-11ea-8086-73e6cad1ea23.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/81440195-eb1a7b00-916f-11ea-99e1-debc9c4a8f84.png)

**Comment by opoudjis** [comment]
ITU was set to ignore inline headers, which several flavours have been; that is now undone.

**Comment by opoudjis** [comment]
I am acutely concerned that shoving Source on the front page is ad hoccery that we cannot track, but I'm permitting a Source section to appear in the Word frontispiece.

**Comment by opoudjis** [comment]
Adding the subtitle in with `:subtitle:` document attribute, to be rendered in Word and HTML only on title repetition at the start of the body.
