### ISSUE TITLE
Boilerplate text should be compiled into XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#138]
Blocking https://github.com/metanorma/mn-native-pdf/issues/24

**Comment by opoudjis** [comment]
Implemented with great pain and disgruntlement. I am imposing a limit of one of these per month. (The pain is putting XML text into idiosyncratically formatted Word cover pages, which need colossal style massaging.)

The attached is a sample of what the boilerplate looks like in XML. 

[a.xml.zip](https://github.com/metanorma/metanorma-itu/files/3916485/a.xml.zip)
