### ISSUE TITLE
Example code not there

### ISSUE THREAD

**Issue by davidlindero** [metanorma/metanorma-itu#139]
The examples linked at the end of the Readme does not exist in that location in the repository. 

For example; `spec/examples/rfc6350.adoc`

**Comment by ronaldtse** [comment]
@davidlindero thanks for reporting! We do have to update the README.

If you were attending the SG 12 session yesterday, the actual examples are now located at a separate location: https://github.com/metanorma/mn-samples-itu

The Recommendation template can be found here:

https://github.com/metanorma/mn-templates-itu

Hope this helps!

**Comment by davidlindero** [comment]
Yes, I was attending that session. Great to read the examples, thanks!

**Comment by ronaldtse** [comment]
Thank you @davidlindero ! Feel free to let us know if any help is needed!

**Comment by opoudjis** [comment]
Updated readmes in all gems that have mn-template-* and mn-samples-* repositories.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
