### ISSUE TITLE
List of acronyms renders very differently in .doc compared to .html

### ISSUE THREAD

**Issue by davidlindero** [metanorma/metanorma-itu#141]
This snippet 

```
== Abbreviations and acronyms

This Recommendation uses the following abbreviations and acronyms:

AAC:: Advanced Audio Coding

AAC-LC:: Advanced Audio Coding – Low Complexity

AC3:: Audio Coding 3
```

Generates very different results when rendering a html page or a .doc-document. The .doc looks correct (each definition and acronym on the same line) but the html-page looks odd with the text after the acronym rendered with an indent and on the row below the acronym. Is this a bug or intended?

**Comment by ronaldtse** [comment]
@davidlindero you are correct, the HTML version splits the acronym and definition.

We'll change it to reflect the existing DOC style for simplicity.

Ping @opoudjis @strogonoff .

**Comment by opoudjis** [comment]
This issue was already fixed in the latest release of isodoc last week: https://github.com/metanorma/isodoc/issues/153

@davidlindero please do a bundle update. Do so in general in fact, the gems get updated fortnightly.

@ronaldtse That applies to you too :-/
