### ISSUE TITLE
XML markup embedded in document text?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#142]
Originally reported here:

https://github.com/metanorma/mn-native-pdf/issues/28

> In source/itu-T-Editing-Guidelines-201602.xml there is a markup:
> 
> ```
> <p id="_7571feeb-d6f1-47bc-a445-0ad010b90a56">The draft <title of="" the="" draft="">, which is proposed for approval, consent or determination:</title>
> 		</p>
> ```
> 
> which displayed in doc as:
> `The draft <title of="" the="" draft="">, which is proposed for approval, consent or determination:</title> `
> But in point of view of xml the tag <title is usual tag, not simple text. I think this text should be coded as:
> `&lt;title .... &gt;, ... &lt;/title&gt;`
> for correct processing in xslt in displaying in PDF.

**Comment by opoudjis** [comment]
Oh dear. @anermina, naughty.

The asciidoctor source reads:

````
The draft <title of the draft>, which is proposed for approval, consent or determination:
````

Bad things are happening when this is converted to XML:

````
The draft <title of="" the="" draft="">, which is proposed for approval
````

This seems to be a similar instance to https://github.com/metanorma/mn-templates-itu/issues/7, which is already supposed to be resolved. Investigating.

**Comment by opoudjis** [comment]
... In fact, this was resolved in the last update:

https://metanorma.github.io/mn-samples-itu/documents/T-Editing-Guidelines-201602.html

@ronaldtse and @Intelligent2013, I have dealt with two bug reports tonight from you about issues that were fixed last week. *Please* check the latest version of documents before reporting bugs. The gems and sample repositories are updated fortnightly.

**Comment by ronaldtse** [comment]
@opoudjis then I suggest you keep the source XMLs up to date with regards to the bug fixes. That would save all agony :wink:

**Comment by opoudjis** [comment]
I did. Did you check it in the samples directory?
