### ISSUE TITLE
Add ITU document type: Supplement

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#143]
`doctype == 'recommendation-supplement'`

**Comment by opoudjis** [comment]
Refer https://github.com/metanorma/mn-templates-itu/issues/2 for sample document

**Comment by opoudjis** [comment]
I am jumping through a lot of hoops to replicate the unmotivated proliferation of ITU supplement titles, 

* _Series L Supplement 37_ (top of coverpage)
* _ITU-T L-series Recommendations – Supplement 37_ (bottom of cover page)
* _L series – Supplement 37 (05/2020)_ (footer)

which I am implementing, though I find it self-indulgent.

But I will NOT implement the following discrepancy in ITU-T L.Sup37, which iss an irredeemable error:

Before summary: 

> Supplement 37 to ITU-T L-series Recommendations

> Guidance to operators of mobile networks, fixed networks and datacentres on setting 1.5°C aligned targets compliant with Recommendation ITU-T L.1470

Before main body:

> Supplement 37 to Recommendation ITU-T L.1470

> Guidance to operators of mobile networks, fixed networks and datacentres on setting 1.5°C aligned targets compliant with Recommendation ITU-T L.1470

The title "Supplement 37 to Recommendation ITU-T L.1470" is unacceptable. There is one title prescribed for internal use in the template supplied, that before the summary, and that is what is going to be used.
