### ISSUE TITLE
Add ITU document type: implementers-guide

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#144]
`doctype == 'implementers-guide'`

**Comment by opoudjis** [comment]
The Document sample for implementers-guide and for technical-report introduce different page breaks for preface sections, with no clear motivation. @ronaldtse Could you confirm with ITU whether those distinctions are needed at all? We would really much rather have a single format for all.

**Technical Report:**

* Summary
* Keywords
* Change Log
* Editors

PAGE BREAK

TOC

**Implementers Guide:**

* Summary

PAGE BREAK

* Change Log

PAGE BREAK

* Contact Information; editors, or ITU-T Study Group YY / Question XX Rapporteur
