### ISSUE TITLE
Add ITU document type: technical-report

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#146]
`doctype == 'technical-report'`

**Comment by ronaldtse** [comment]
Technical report document available here: https://github.com/metanorma/mn-templates-itu/issues/5

**Comment by ronaldtse** [comment]
<img width="637" alt="Screen Shot 2020-10-07 at 6 13 14 PM" src="https://user-images.githubusercontent.com/11865/95318190-c5cd9c80-08c8-11eb-84be-8d8f6268cf58.png">

Attributes:
* question (free text, can enforce in future, but maybe not worth it)
* study group (free text, can enforce in future, but maybe not worth it) 
* working party (free text, can enforce in future, but maybe not worth it) 
* meeting title
* meeting date(s)
* type of document
* source: free text
* title

Attribute for contacts:
* use the typical model we have.


<img width="692" alt="Screen Shot 2020-10-07 at 6 13 42 PM" src="https://user-images.githubusercontent.com/11865/95318241-d5e57c00-08c8-11eb-9c63-5dc4bc981199.png">

* short string (4-letter acronym)
* series
* title
* date of report


<img width="628" alt="Screen Shot 2020-10-07 at 6 15 38 PM" src="https://user-images.githubusercontent.com/11865/95318416-1c3adb00-08c9-11eb-9351-bcb460c99bf3.png">

* abstract/summary (maybe choose ITU word "summary")
* keywords
* change log. can be free block text
* editor: use the typical model we have as with contacts.

**Comment by ronaldtse** [comment]
Example: https://www.itu.int/en/ITU-T/focusgroups/vm/Documents/FGVM-O1-Final.pdf

**Comment by opoudjis** [comment]
ITU working groups work in this structure:
- question > study group > working party


a "term" (e.g. 2016-2020) has multiple "questions"

a term has multiple questions, a question has multiple study groups (sub-questions), and each has multiple working parties.

**Comment by opoudjis** [comment]
ITU already has the structure group/subgroup/workgroup; I'm reusing that structure for question/study group/working party
