### ISSUE TITLE
Add ITU document type: service-publication

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#148]
Service publication: Annex to ITU Operational Bulletin.

**Comment by ronaldtse** [comment]
https://github.com/ituob/service-publications-data/pull/18

On "OB Annex 1002", from @anermina :

1. Front page has different style
2. Table of contents and foreword are not needed
3. Note by TSB should be added as a preface
4. Header is not needed and footer should be different
5. Empty rows don't have a proper height

**Comment by ronaldtse** [comment]
https://github.com/ituob/service-publications-data/pull/17

On "OB Annex 955" from @anermina:

1. Front page has different style
2. Table of contents and foreword are not needed
3. Note by TSB should be added as a preface
4. Titles look different in general, sections shouldn't be numbered and there should be a separate page for each section. E.g. title before the main table should be "Various tones used in national networks", without header
5. In the section "Notification Form for Change of tones used in national networks", the second table only has a heading and several empty rows, which therefore don't have a proper height
6. In the section "Explanation of symbols", line break is added after "Frequency in Hz"
7. The comment "To be returned to ITU/TSB Fax No. +41 22 730 5853 / E-mail: tsbtson@itu.int" should be in the header before the "Notification Form"

**Comment by ronaldtse** [comment]
ituob/service-publications-data#21

. Front page has different style and title doesn't render well
. Table of contents and foreword are not needed
. Note by TSB should be added as a preface
. Original tables are displayed in landscape mode. When rendered, they are too wide to fit to the Word portrait page. (Issue #173 metanorma/metanorma-standoc#173)
. Header and section title are not needed before the main table
. Before "Notification of X.400 ADMD" section, there should be a header with ITU logo and contact information
. Footer should be different

**Comment by ronaldtse** [comment]
ituob/service-publications-data#28

1. Repeating footnotes are duplicated in definition lists (e.g. Australia, Indonesia, San Marino). However, they are fine in tables.
2. Definition lists do not break to another page if they are too long to fit. Page break is added before that long definition list instead (this can be seen for Israel and Italy).
3. Multi-paragraph footnotes (which include some items lists) do not include a line break. I've tried multiple markups, but none of them gave the expected result. This can be seen in the table from the United Kingdom section.
4. Unlike in the other long tables, where table heading should be repeated at the beginning of each new page, in the first two tables of these documents, repetition of the third row is required.
5. Multi-paragraph notes are marked as "NOTE –", which maybe is not the best mark in case when only some list is included. In that case, there is a line break after this mark, which leaves the row after "NOTE -" empty.
6. Word "Note" and footer content should be translated to the language of the document.
7. Front page has a different style.
8. Table of contents and foreword are not needed.
9. Footer should be different.

Arabic version is not added yet due to the issue ituob/service-publications-data#27.

**Comment by ronaldtse** [comment]
ituob/service-publications-data#25

1. Front page has a different style
2. Table of contents and foreword are not needed
3. Footer should be different
4. There should be a title and a subtitle before the Note from TSB, but as in the other documents, I've set [preface] element before the Note. In the subtitle of the English version, there should be a footnote "Formerly CCITT Recommendation".
5. I've set the zones as sections and the list of countries with their MCCs as table entries. In the original document, there is just a title for the zones (they are not numbered as sections) and the countries with their MCCs are written in two columns, probably not using the table option. Please let me know if any changes are needed.

**Comment by opoudjis** [comment]
I am not at this time implementing the ITU coverpage as it is, because any deviation from the standard coverpage template needs to be justified explicitly—not to mention the fact that 1162 from 2018 looks a lot less like the standard template than 1002 from 2012 does. ITU need to reflect on their coverpage styling for this document type.

Table of contents is omitted consistently.

**Comment by ronaldtse** [comment]
The Word sources are at: https://github.com/ituob/service-publications-refs

**Comment by opoudjis** [comment]
Need to internationalise dates: in ITU, for service publications, dd.ROMAN NUM.YYYY for all languages but Chinese.

Chinese renders

> Annex to ITU Operational Bulletin 
> No. 1161 – 1.XII.2018

as

> 国际电联2018年12月1日第1161期
>《操作公报》附件

**Comment by ronaldtse** [comment]
The `doctype` is `service-publication`. The nature of a `service-publication` is an "Annex to an Operational Bulletin Issue". We will have a separate `doctype` called `operational-bulletin`. The OB and the OB Annexes are published by ITU, not ITU-T (the T bureau of ITU) in the case of our current Recommendations.

**Comment by opoudjis** [comment]
Introducing ITU-lang identifier to include language code; that identifier is i18n-ised for the current document language in the case of service publications.

**Comment by opoudjis** [comment]
I have implemented enough of this that I think its rendering is acceptable. Its rendering will not coincide exactly with the reference documents, but the reference documents are inconsistent between each other anyway — not least ITU-R vs ITU-T (BR vs TSR).

The useful thing at this stage is to render some representative publications, and see if their rendering is acceptable to ITU, before proceeding with any further work.

i18n will also need to proceed, pending https://github.com/metanorma/metanorma-itu/issues/5, but the templates are substantially i18n-ready (although Arabic will need the coverpage flipped, and we already know from https://github.com/metanorma/isodoc/issues/166 that it will need to be worked on.)

Putting on hold until input received. No point proceeding with PDF rendering until we have settled on Word rendering.

**Comment by ronaldtse** [comment]
@opoudjis All existent services publications are already completed and ready from @manuel489 , and he verified that the layout is good to go.

The next step is just PDF for @Intelligent2013.

**Comment by manuel489** [comment]
> @opoudjis All existent services publications are already completed and ready from @manuel489 , and he verified that the layout is good to go.

@ronaldtse remember that Arabic documents do not render as expected due to text orientation.

**Comment by ronaldtse** [comment]
@manuel489 thanks, that's a generic issue that needs to be fixed detailed in #274.

**Comment by opoudjis** [comment]
Welp, in that case, this ticket can close, and any updates to formatting on HTML/Word can be new ticket...
