### ISSUE TITLE
Default `doctype` must be set to `recommendation`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#154]
Currently, if `doctype` is not set explicitly, it is being set to `article` which is wrong.

The default `doctype` must be set to `recommendation`.

**Comment by opoudjis** [comment]
This was fixed as https://github.com/metanorma/mn-native-pdf/issues/36, 19 days ago. You may not be seeing it in mn-samples-itu, because docker was broken last release.

**Comment by ronaldtse** [comment]
Great. I've done a temporary fix here too: https://github.com/metanorma/mn-samples-itu/commit/43dbed25334eebde6af2bb97a57093814a6310ca
