### ISSUE TITLE
Go through Editing Guidelines and ensure compliance

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#155]

**Comment by opoudjis** [comment]
Insert missing sections: Scope, Norm Ref, Terms, Symbols, Conventions are all mandatory, and need to be supplied with "none" text if absent.

**Comment by ronaldtse** [comment]
PDF version of the Editing Guidelines if helpful:
[itu-T-Editing-Guidelines-201602.pdf](https://github.com/metanorma/metanorma-itu/files/4335707/itu-T-Editing-Guidelines-201602.pdf)

**Comment by opoudjis** [comment]
Will suppress the insertion of sections by  document attribute `:do-not-insert-missing-sections:`, because it will break legacy documents.

**Comment by ronaldtse** [comment]
Can we prefix this option with “legacy” to indicate it is for compatibility?

**Comment by opoudjis** [comment]
OK

**Comment by opoudjis** [comment]
No need for container in hierarchical asset numbers (restart numbering per appendix/clause): the clause/appendix number is sufficient. Addresses inconsistency: only formulae, requirements had retained containers.

**Comment by opoudjis** [comment]
Renamed `:hierarchical-assets:` to `:legacy-sequential-object-numbering:`: by default, asset numbering follows the Editing Guidelines in restarting each clause.

**Comment by opoudjis** [comment]
9.6.1. Noting here that the Editing Guidelines say Notes should be introduced with em-dashes, but itself uses en-dashes. We will keep using en-dashes.

**Comment by opoudjis** [comment]
9.6.1.

> If the same footnote appears repeatedly on the same page of the text, the text of the footnote should be removed after the first time it is used. Furthermore, the same identifier for the footnote should be used for each occurrence of reference to that note on the page. Should the same footnote appear multiple times across multiple pages, the same rules within each page apply as above; however, the footnote should appear with a (possibly) different identifier for the first occurrence on each page.

The first is already implemented: we have no means of automating the second (repeating a footnote marker the first time it appears newly on a page.) @ronaldtse Please inform ITU.
