### ISSUE TITLE
Namespace of G.650.1-201803-v2.xml not updated

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#164]
For @camobap795:

The deployment process of https://github.com/metanorma/mn-samples-itu is failing. Can you please help fix it, so that the namespace of generated documents are updated? (for @intelligent2013)

Thanks!

> @ronaldtse I would like to merge this PR, but can't due - 
https://metanorma.github.io/mn-samples-itu/documents/G.650.1-201803-v2.xml has namespace "https://open.ribose.com/standards/itu" instead of "https://www.metanorma.com/ns/itu". Could you fix it, please?

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mn-native-pdf/pull/73#issuecomment-600471945_

**Comment by Intelligent2013** [comment]
Update: the name space should be 'https://www.metanorma.org/ns/itu' (not https://www.metanorma.com/ns/itu')

**Comment by opoudjis** [comment]
The namespace https://www.metanorma.com/ns/itu occurs nowhere in the metanorma-itu gem. That was fixed in https://github.com/metanorma/metanorma-itu/releases/tag/v1.0.8, 3 weeks ago.

**Comment by opoudjis** [comment]
The XML in mn-samples-itu has not been updated since Jan 14. I have been triggering samples updates constantly. Whatever is going on, mn-samples-itu is NOT refreshing, and that is the issue for @CAMOBAP795 to be addressing.

**Comment by ronaldtse** [comment]
@CAMOBAP795 I verified that the latest metanorma-itu (1.0.10) creates the correct namespace. Apparently this line in code is obsolete and was just not removed. Can you just fix mn-samples-itu build and it will work?

**Comment by ronaldtse** [comment]
Closing.
