### ISSUE TITLE
DOC Equation reference broken in ITU G.650

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#169]
![image](https://user-images.githubusercontent.com/11865/77982565-42daf080-733f-11ea-9939-3aad6d601352.png)

From @anermina at https://github.com/metanorma/mn-native-pdf/issues/96 .

Document: https://github.com/metanorma/mn-samples-itu/blob/master/sources/G.650.1-201803.adoc

**Comment by opoudjis** [comment]
Fixed in #172
