### ISSUE TITLE
DOC generated is missing document numbers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#170]
From @anermina 

DOC (issue is yellow highlighted):

![image](https://user-images.githubusercontent.com/11865/77982745-a402c400-733f-11ea-8d1b-d78017761c3f.png)

![image](https://user-images.githubusercontent.com/11865/77982759-ac5aff00-733f-11ea-87f0-c02204ed8a35.png)
![image](https://user-images.githubusercontent.com/11865/77982761-ae24c280-733f-11ea-899d-5baded5fac3a.png)

Document: https://github.com/metanorma/mn-samples-itu/blob/master/sources/G.650.1-201803.adoc

From: https://github.com/metanorma/mn-native-pdf/issues/96

**Comment by opoudjis** [comment]
Metadata naming of docnumber field was inconsistent between metadata extraction and coverpage template; fixed. 

Moreover, restricted the docnumber metadata field to be `//bibdata/docidentifier[@type = 'ITU']`, not the first docindentifier found in bibdata.
