### ISSUE TITLE
DOC broken definitions section in G.650

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#172]
From @anermina 

Definitions section is rendered badly in DOC. Some additional text is added - and the section is rendered as Scope. Terms and definitions (subsections) are not generated. Due to this issue, some cross-references are not properly rendered (because these sections were not generated): [term_mode_field_diameter], [term_cladding_diameter], [term_cladding_non_circularity], [term_core_concentricity_error], [definitions], [glass_geometry_characteristics]. The same applies for the cross-references to equations from Definitions section, which are generated in DOC as: Equation (???-2), Equation (???-4) and Equation (???-5).

![image](https://user-images.githubusercontent.com/11865/77982885-022fa700-7340-11ea-946f-90ecb133a3ae.png)

![image](https://user-images.githubusercontent.com/11865/77982898-08be1e80-7340-11ea-91ad-ae873781a5eb.png)

![image](https://user-images.githubusercontent.com/11865/77982903-0bb90f00-7340-11ea-80ee-48de5062fb3b.png)

Document: https://github.com/metanorma/mn-samples-itu/blob/master/sources/G.650.1-201803.adoc

From: https://github.com/metanorma/mn-native-pdf/issues/96

**Comment by opoudjis** [comment]
Things are better after #171 fix:

> Definitions section is rendered badly in DOC. Some additional text is added - and the section is rendered as Scope.

These are addressed. 

The terms and the definitions equations are not yet.
