### ISSUE TITLE
Italic text isn't working in math mode (DOC output)

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#173]
stem:[ii"italic text"] renders as normal text (in doc output).

**Comment by opoudjis** [comment]
Force stylesheet to inject italic style if this is mtext

**Comment by opoudjis** [comment]
The `<span class=stem>`, which enforces italics, is blocking the italicisation of `<m:t>`: overriding it by wrapping `<span class=nostem>`

**Comment by opoudjis** [comment]
The solution is kludgy, but it's done.
