### ISSUE TITLE
Issues in generating T-Editing-Guidelines-201602

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#175]
It is mentioned in https://github.com/metanorma/mn-native-pdf/issues/60#issuecomment-605702497 that this document has errors in MN XML.

@Intelligent2013 can you help explain what errors you have encountered? Thanks.

**Comment by Intelligent2013** [comment]
@ronaldtse I've updated XSLT for ITU documents. There was an issue in id generation for cross reference links.
