### ISSUE TITLE
Word: Centering equations written as a part of one thesis (bullet/dash)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#182]
When equations are written as a part of one thesis (after the bullet/dash), they are not centered.

Original:
![image](https://user-images.githubusercontent.com/55683568/80263952-b2b86e80-8692-11ea-9a00-55167331b6ab.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/80263974-c532a800-8692-11ea-9c25-0feb0cf19cdd.png)

[test_equations.zip](https://github.com/metanorma/metanorma-itu/files/4531991/test_equations.zip)

**Comment by opoudjis** [comment]
Formulas in Word rely on tabs being in the right place in the Formulas style; there are two tabs at the start of a formula. In a list context, formulas end up indented, which means that the first tab overshoots, and the whole formula ends up overflowing.

This double tab is specific to ITU Word, and is unnecessary: getting rid of the initial tab in rendering and stylesheet.
