### ISSUE TITLE
Bug in referencing equations in hierarchical numbering

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#183]
from @intelligent2013
> Example of differences I can see is below. Please note that cross-references to equations differ, as well.

ITU equation cross-reference is somewhat broken:

```
The mathematical equivalence of equations <<eq3-2>> and <<eq-6-1>> is valid in the approximation of small angles θ. Under this approximation, <<eq-6-1>> can be derived from <<eq3-2>> by integration.
```

In the previous version of DOC:
![image](https://user-images.githubusercontent.com/5559926/80286777-062fc880-8736-11ea-81ef-a5e6e9cc84bc.png)

In the latest DOC:
![image](https://user-images.githubusercontent.com/5559926/80286763-ec8e8100-8735-11ea-8000-34c676068cc1.png)

_Originally posted by @Intelligent2013 in https://github.com/metanorma/mn-native-pdf/issues/96#issuecomment-619416449_

**Comment by opoudjis** [comment]
This has since been fixed.
