### ISSUE TITLE
Word: Numbering notes in tables vs. in sections

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#187]
Table notes are numbered separately from other notes included in the same (sub)section of the generated DOC. This produces different note numbering in comparison to the original.

I'm not sure whether this is a problem, but it was noticed as a difference while comparing original vs. PDF and DOC outputs for ITU H.782.

Original:
![image](https://user-images.githubusercontent.com/55683568/80397028-db6c7e00-88b5-11ea-9582-2f15f5aea9a0.png)

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/80616877-b442b780-8a41-11ea-9c5d-58204ba9f17e.png)

**Comment by ronaldtse** [comment]
I’d also like to make sure that the first NOTE is encoded in xml as part of the table itself. Thanks.

**Comment by anermina** [comment]
This note is written after the table in .adoc, as shown in the original document. Attached are some example cases which illustrate notes numbering.

[test_table_notes.zip](https://github.com/metanorma/metanorma-itu/files/4556747/test_table_notes.zip)

**Comment by opoudjis** [comment]
> Table notes are numbered separately from other notes included in the same (sub)section of the generated DOC. This produces different note numbering in comparison to the original.

This is behaviour inherited from ISO, and assumed by default in Metanorma. Fine to change this behaviour for ITU, but be aware that it is a Metanorma default.

**Comment by opoudjis** [comment]
More to the point: Currently Metanorma grabs any note immediately after a table, and treats it as part of the table. We can globally say that does not happen in ITU, but we would need to conform that.

**Comment by opoudjis** [comment]
@anermina I have implemented a fix to this behaviour in https://github.com/metanorma/metanorma-iso/issues/379, 

````
[NOTE,keep-separate=true]
====
Note contents
====
````

It is not clear to me whether we need to anything further. The Metanorma default is a useful default, and now we can stop it when needed. Closing ticket.
