### ISSUE TITLE
Word: text justification after the + sign for the new line

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#188]
When `+` sign is used in .adoc as a linebreak, text becomes justified, which doesn't always look good. For example, in ITU G.191, many subsections begin like this:

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/80623993-574bff00-8a4b-11ea-86d8-6daee05fbce2.png)
![image](https://user-images.githubusercontent.com/55683568/80624433-f4a73300-8a4b-11ea-9773-a6c8ed4f9fd1.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/80624383-e527ea00-8a4b-11ea-8bdb-b12ce88d2f8c.png)
![image](https://user-images.githubusercontent.com/55683568/80624488-07ba0300-8a4c-11ea-91cf-4de3740b6847.png)

**Comment by opoudjis** [comment]
Longstanding known issue, and this has already been recorded as a gotcha. All you can do in such cases is make the paragraph left-aligned:

````
[align=left]
Name: `firflt.c` +
Associated header file: `firflt.h`
````
