### ISSUE TITLE
Word: Copyright position and year

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#189]
In generated ITU DOCs, copyright title "© ITU 2020" is not centered, unlike in the original documents. 
Copyright year also differs.

DOC:
![image](https://user-images.githubusercontent.com/55683568/77966177-c74b5600-72e2-11ea-8c07-38334a7df9fb.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/80635044-a863ef00-8a5b-11ea-8345-91f5acda23d1.png)

**Comment by opoudjis** [comment]
The year is the `:copyright-year:`, if provided, else the current year; please check the document that the copyright-year has been provided.
