### ISSUE TITLE
ITU logo squished sideways

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#19]
ITU logo squished sideways:

<img width="746" alt="Screen Shot 2019-09-09 at 11 24 33 PM" src="https://user-images.githubusercontent.com/11865/64546771-daee9980-d35d-11e9-9fe7-39aba5c52949.png">

Sample: see https://github.com/metanorma/mn-samples-itu/

**Comment by opoudjis** [comment]
This is a CSS fix. Which means it will break again once @strogonoff gives me the CSS files he has been refactoring. Anton, URGENT you give me those files, in whatever state you have them; they have been holding up development. I would rather fix any issues that arise after the fact.

**Comment by opoudjis** [comment]
I have added `height:auto` to `#ITU-logo` CSS, but I cannot close this ticket until @strogonoff gives me the refactored CSS files.

**Comment by opoudjis** [comment]
ITU CSS refactored
