### ISSUE TITLE
Word: Generating a colon before/after the [.source]

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#190]
If some document is referred to using the [.source] attribute, it gets generated after the term in ITU documents. However, original document uses a colon right after the term, while generated one adds a colon after the source. This was noticed in ITU P.1203.

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/80635315-02fd4b00-8a5c-11ea-9118-7550ad257b98.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/80635337-098bc280-8a5c-11ea-896e-20f8d97fa74d.png)

**Comment by opoudjis** [comment]
Also needs to be implemented for PDF: @Intelligent2013

**Comment by Intelligent2013** [comment]
Done.
Resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/97863213-aedb6800-1d17-11eb-9aac-73b721151f7e.png)
