### ISSUE TITLE
Word: Managing long tables

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#191]
- When tables are too long to fit to one page, their caption (and heading) repeats in the original, unlike in generated DOC. Examples below are provided from ITU Y.3507.

Original:
![image](https://user-images.githubusercontent.com/55683568/73481358-fce3c980-439b-11ea-87f9-f72c40dfaa60.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/73481380-053c0480-439c-11ea-8823-8e9771bf9095.png)

Moreover, heading is sometimes missing in the generated DOC:
![image](https://user-images.githubusercontent.com/55683568/80696019-126daa00-8ad7-11ea-9a09-5bc6a27fe2cb.png)

- In case one merged cell (multiple merged rows) cannot fit to the same page as the previous cell (row), page break is added in generated DOC and then that long merged cell is inserted on a new page. However, in the original DOC this long cell is divided, i.e. rows are inserted below the previous cell until the bottom margin is reached, then cell splits and the rest of the rows are inserted on the next page.

Original:
![image](https://user-images.githubusercontent.com/55683568/73481957-1cc7bd00-439d-11ea-8819-46e31fe30535.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/73482010-3e28a900-439d-11ea-92a8-8271b5087ec2.png)

**Comment by opoudjis** [comment]
> When tables are too long to fit to one page, their caption (and heading) repeats in the original, unlike in generated DOC. 

They are meant to repeat, and in your examples, it looks like they do repeat sometimes; this may get more complicated to debug.

**Comment by opoudjis** [comment]
In this document, tables rows are explicitly permitted to split across two pages; imposing that condition on the generated document fixes the repeating header (which only becomes an issue when a row becomes bigger than a page.)

**Comment by opoudjis** [comment]
I'm reluctant to adopt a general rule of allowing table rows to break between pages, because it will happen to small tables.

**Comment by opoudjis** [comment]
No, it turns out this isn't a universal rule of Word stylesheets: disallowing pagebreaks in tables is specific to ITU, and this is an instance where it leads to bad outcomes. Removing that restriction.
