### ISSUE TITLE
Word: Numbering tables in Appendices

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#192]
- Numbering format differs for the tables in appendices. In the original document (ITU Y.3507), dot is used between appendix number and the ordinal number of the table, while generated DOC/PDF use a dash.

Generated:
![image](https://user-images.githubusercontent.com/55683568/80690601-552b8400-8acf-11ea-9c02-34b38a4da186.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/80690619-5c529200-8acf-11ea-9516-71e891d66505.png)

**Comment by opoudjis** [comment]
Confirmed that ITU does not use dash between appendix/annex and asset number—with the annoying exception of formulae.

**Comment by anermina** [comment]
@opoudjis , do you know does this apply only to annexes and appendices?

We have the following rule for `:hierarchical-object-numbering:` on metanorma.com:
_Use in complex documents, with multiple tables or figures, that need to be tracked against clauses for ease of lookup (so Figure 6-3, 6-4, instead of Figure 21, 22.) Note that equations in ITU are always numbered hierarchically._

To me, it seems inconsistent to use dots in annexes/appendices and to use dashes in the rest of the document.

**Comment by anermina** [comment]
In addition to this, I have seen combination of dashes and dots in ITU Y.3507, but...it just seems inconsistent. 

![image](https://user-images.githubusercontent.com/55683568/83906093-30c46680-a763-11ea-8790-44ae70d5b81a.png)

![image](https://user-images.githubusercontent.com/55683568/83906104-38840b00-a763-11ea-9fef-c94b61471653.png)

@ronaldtse , could you also please check this question: Does ITU want to use:
- dots between section number and figure/table number, when that figure/table is a part of an annex/appendix;
- dashes between section number and figure/table number, otherwise?

**Comment by ronaldtse** [comment]
@anermina can you gather all the evidence that this is a problem in new issue so that I directly ask ITU? Right now there is only 1 sample case.

**Comment by ronaldtse** [comment]
I've sent the question.

**Comment by opoudjis** [comment]
Sorry, @anermina, I know nothing more than you do about the conventions at work. Seeming inconsistency with SDOs usually is real inconsistency :-/

**Comment by anermina** [comment]
> @anermina can you gather all the evidence that this is a problem in new issue so that I directly ask ITU? Right now there is only 1 sample case.

@ronaldtse New issue is opened in https://github.com/metanorma/metanorma-itu/issues/219.
