### ISSUE TITLE
Word: differences in generated vs. original document for :doctype: recommendation-annex

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#193]
- In `:doctype: recommendation-annex`, annex title is written along with annex ID in the original document, and without the ID in generated DOC.

Original:
![image](https://user-images.githubusercontent.com/55683568/80699670-adb54e00-8adc-11ea-91e9-68690a70fe42.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/80699687-b443c580-8adc-11ea-9877-ad60d44ae4fd.png)

- Annex identifier and title are also written as a subtitle of the page with Summary and History in the original document, unlike the generated one.

Original:
![image](https://user-images.githubusercontent.com/55683568/80699747-cc1b4980-8adc-11ea-86de-7d3dfc42094c.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/80699760-d2a9c100-8adc-11ea-87b7-4fcf2dfb6dfe.png)

- Table of contents doesn't include the main section name (annex title) in the original document, unlike in the generated one.

Original:
![image](https://user-images.githubusercontent.com/55683568/80699884-11d81200-8add-11ea-8ccd-74d8d1ca4164.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/80699905-1b617a00-8add-11ea-8b02-f0bf10fce62c.png)

- In generated DOC, page break is inserted between the title and subtitle (1st and 2nd page).

Original:
![image](https://user-images.githubusercontent.com/55683568/80767336-f22a0380-8b47-11ea-88a0-7f6f983d5f6b.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/80767355-f8b87b00-8b47-11ea-9784-9e377c41472d.png)
...
![image](https://user-images.githubusercontent.com/55683568/80767365-01a94c80-8b48-11ea-9621-88bd658e0322.png)

**Comment by opoudjis** [comment]
Metadata field `:doctype:` needs to be Recommendation not Recommendation Annex in display.

**Comment by opoudjis** [comment]
Insert actual doctype in internal middle title

**Comment by opoudjis** [comment]
Numbers being validated must be preceded by space or be at start of block.

**Comment by opoudjis** [comment]
Switch h1.Annex to .h1Annex style, to preempt inclusion in Table of contents
