### ISSUE TITLE
Different keywords order in generated DOC and PDF

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#194]
Keywords are ordered differently in generated DOC in comparison to their order in .adoc and in generated PDF.
First word is always written with capital letter in the original document, but this can currently be produced only if that word is written with capital letter in source .adoc. It wouldn't be a problem to write the first word with capital in .adoc, but that would produce a proper result in PDF, while the same word wouldn't need to be the first keyword in DOC. For example:

Original:
![image](https://user-images.githubusercontent.com/55683568/80730459-e9b2d800-8b09-11ea-91e8-d937fb766189.png)

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/80730521-f9322100-8b09-11ea-8cf1-51e85066b36a.png)

**Comment by opoudjis** [comment]
Sorting of keywords, and capitalisation of first keyword, done in XML.
