### ISSUE TITLE
Word: Numbering figures in example blocks

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#195]
In generated DOC, figures which are part of the example blocks do not include numeration in their titles, unlike in the original document. This was noticed in generated document for ITU REC Z.100.

Original:
![image](https://user-images.githubusercontent.com/55683568/80734905-300b3580-8b10-11ea-8fa4-fc877f1a423e.png)

Generated:
![image](https://user-images.githubusercontent.com/55683568/80734919-35688000-8b10-11ea-8cc3-a6ae2c243c9f.png)

**Comment by opoudjis** [comment]
Issue included in https://github.com/metanorma/metanorma-iso/issues/374

**Comment by anermina** [comment]
@ronaldtse, ISO gave us the instructions you wrote in https://github.com/metanorma/metanorma-iso/issues/374#issuecomment-631253086. Could you please check does the same apply to ITU? In case it does, please let me know so I can exclude figures and tables from the example blocks.

**Comment by ronaldtse** [comment]
> @ronaldtse, ISO gave us the instructions you wrote in metanorma/metanorma-iso#374 (comment). Could you please check does the same apply to ITU? In case it does, please let me know so I can exclude figures and tables from the example blocks.

ITU uses different rules from ISO, but in this case it is reasonable to assume that the Figure here is considered part of the document (Figure F1-3, where F1 is the doc, and 3 is the ID within the doc), so let's bring it out.

**Comment by anermina** [comment]
Fixed in https://github.com/metanorma/mn-samples-itu/pull/107. Closing.
