### ISSUE TITLE
ITU HTML styling: oversized ITU logo, empty orange box underneath

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#197]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/11865/80963617-e6895600-8e41-11ea-84db-270bce95797f.png">

**Comment by opoudjis** [comment]
Source document plox?

**Comment by opoudjis** [comment]
Logo was left at 200px width on change-over from old to new logo in https://github.com/metanorma/metanorma-itu/issues/19. I'll reduce to 150px for now.
