### ISSUE TITLE
PDF: XML contains "Definitions" section as a part of the "Scope" section

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#198]
Scope section is rendered badly in PDFs and it includes an additional subsection.

PDF:
![image](https://user-images.githubusercontent.com/55683568/80309726-0fbd3d00-87d7-11ea-9649-7e710e013b11.png)
![image](https://user-images.githubusercontent.com/55683568/80309822-9114cf80-87d7-11ea-97c2-fe04f4015294.png)
 
Original:
![image](https://user-images.githubusercontent.com/55683568/80309746-219ee000-87d7-11ea-81f4-31839c25d21b.png)
![image](https://user-images.githubusercontent.com/55683568/80309829-9a9e3780-87d7-11ea-8b6e-fbf1b5a16112.png)

@Intelligent2013 reported:
> Additional subsection is a part of XML:
> 
> ```
> <clause id="Scope" obligation="normative">
> 	<title>Scope</title><p id="_896dca22-8745-4bf0-9b48-21309e4708a6">This Recommendation defines the following terms:</p>
> 	<terms obligation="normative">
> 		<title>Definitions</title><p id="_cd0ed414-df2a-4580-87f2-34d77adfd233">None.</p>
> 	</terms>
> 	<note id="_d60b467c-cc57-42ca-b89b-e26f4730c638">
> 		<p id="_e9b3613b-0178-4e0a-8054-1cbffc89eb84">Recommendation ITU-T A.1500 is a fictitious Recommendation. It was established for illustrative purposes only and constitutes an example of the proposed presentation style.</p>
> 	</note>...
> ```

**Comment by opoudjis** [comment]
Just regenerated, and I'm not getting any of this behaviour. Could you please recheck @anermina?

**Comment by anermina** [comment]
Based on ITU PDFs in https://github.com/metanorma/mn-native-pdf/tree/gh-pages/documents, this issue is solved. Closing.
