### ISSUE TITLE
XML: title should not escape apostrophe twice

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#199]
In two PDFs, it was noticed that title was not rendered properly and @Intelligent2013 reported some XML issues in those cases.
Should generation of dashes, apostrophes etc. be forced in .adoc when it comes to titles (using some code, similar to generating `(c)` instead of a copyright symbol), or the change should be made in XML?

ITU-T A.1500 (T-Editing Guidelines) document review
----------------
Title doesn't render well in PDF (apostrophe ' is rendered badly).

PDF:
![image](https://user-images.githubusercontent.com/55683568/80309572-2c0caa00-87d6-11ea-880f-c5922ba9fae9.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/80309580-362ea880-87d6-11ea-8da3-d3abd2154568.png)

> The issue in source XML:
> 
> ```
> <title language="en" format="text/plain" type="main">Author&amp;#8217;s guide for drafting ITU-T Recommendations</title>
> ```
> 
> Should be:
> 
> ```
> <title language="en" format="text/plain" type="main">Author&#8217;s guide for drafting ITU-T Recommendations</title>
> ```

ITU Y.3507 document review
---------------
Title is not rendering properly in PDF (dash is represented with some code).

PDF:
![image](https://user-images.githubusercontent.com/55683568/72920202-1efc9c80-3d49-11ea-8712-bd7c8c2c06c0.png)

DOC:
![image](https://user-images.githubusercontent.com/55683568/72920235-2ae85e80-3d49-11ea-9246-95a73546d824.png)

> Issue in XML:
> 
> ```
> <title language="en" format="text/plain" type="main">Cloud computing&amp;#8201;&amp;#8212;&amp;#8201;Functional requirements of physical machine</title>
> ```

**Comment by ronaldtse** [comment]
> Should generation of dashes, apostrophes etc. be forced in .adoc when it comes to titles (using some code, similar to generating (c) instead of a copyright symbol), or the change should be made in XML?

This should definitely be done inside the XML.

**Comment by ronaldtse** [comment]
The apostrophe shouldn’t have the “&” symbol escaped in the XML.

**Comment by anermina** [comment]
Update: Both titles render well now.

**Comment by opoudjis** [comment]
Confirming that in XML, apostrophes and dashes are properly handled.
