### ISSUE TITLE
Published vs Prepublished IPR statements are different

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#2]
Prepublished:

"
INTELLECTUAL PROPERTY RIGHTS

ITU draws attention to the possibility that the practice or implementation of this Recommendation may involve the use of a claimed Intellectual Property Right. ITU takes no position concerning the evidence, validity or applicability of claimed Intellectual Property Rights, whether asserted by ITU members or others outside of the Recommendation development process.

As of the date of approval of this Recommendation, ITU [had/had not] received notice of intellectual property, protected by patents, which may be required to implement this Recommendation. However, implementers are cautioned that this may not represent the latest information and are therefore strongly urged to consult the TSB patent database at http://www.itu.int/ITU-T/ipr/.

"

Published (no notice): (D.000)

"
INTELLECTUAL PROPERTY RIGHTS

ITU draws attention to the possibility that the practice or implementation of this Recommendation may involve the use of a claimed Intellectual Property Right. ITU takes no position concerning the evidence, validity or applicability of claimed Intellectual Property Rights, whether asserted by ITU members or others outside of the Recommendation development process.

As of the date of approval of this Recommendation, ITU had not received notice of intellectual property, protected by patents, which may be required to implement this Recommendation. However, implementers are cautioned that this may not represent the latest information and are therefore strongly urged to consult the TSB patent database at http://www.itu.int/ITU-T/ipr/.
"

**Comment by ronaldtse** [comment]
From ITU-T:

> The boilerplate text is identical, except for the phrase that you highlight below. At the time of editing the phrase “…ITU [had/had not]…” is modified to “…ITU had…” or “…ITU had not…” depending on whether patents declaration have or not been filed with ITU against the specific Recommendation. Prepublished texts contain the unedited phrase.

So we should have an attribute "switch" that decides one of these three:
* not yet received
* received
* not received

It might be better to implement these as three separate pieces of text (rather than only changing "[had/had not]" into "had" or "had not") since it may change in the future.

**Comment by opoudjis** [comment]
The switch only needs to be not received/received; if the document status is unpublished, the not yet received boilerplate is used instead.
