### ISSUE TITLE
Word: Generating empty default sections in ITU recommendations

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#200]
Some ITU recommendation-specific sections do not exist in ITU A.8 document. However, they are generated (which is probably default behavior), but it can be seen that there is some error - Definitions section is duplicated, Conventions section is not numbered, References contain word "None" twice.
I understand that document style probably changed through the years, but when referencing some section from the other recommendation, original section number is used, so I believe we shouldn't generate these empty sections for that reason. This ticket is opened in order to check the expected behavior.

Generated:
![image](https://user-images.githubusercontent.com/55683568/81439521-cbcf1e00-916e-11ea-8551-d347b3840ef9.png)
![image](https://user-images.githubusercontent.com/55683568/81439551-d5588600-916e-11ea-9f46-895a3116bbf8.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/81442336-ac86bf80-9173-11ea-9d54-f2c9b553523c.png)

**Comment by opoudjis** [comment]
@anermina, as noted in https://github.com/metanorma/metanorma-itu/issues/155, you can suppress the generation of these now mandatory sections by inserting the document attribute `:do-not-insert-missing-sections:`.

Please close issue if this addresses your concern.

**Comment by ronaldtse** [comment]
@opoudjis it looks like there are two issues:
1. suppress the generation of these now mandatory sections, which you have answered
2. errors in generated document with supplemented sections:
> Definitions section is duplicated, Conventions section is not numbered, References contain word "None" twice.

**Comment by anermina** [comment]
> @anermina, as noted in #155, you can suppress the generation of these now mandatory sections by inserting the document attribute `:legacy-do-not-insert-missing-sections:`.

Yes, this attribute was missing. Adding it solves the problem.

> 2\. errors in generated document with supplemented sections:
> 
> > Definitions section is duplicated, Conventions section is not numbered, References contain word "None" twice.

I think this issue occurs only when all mandatory sections are empty and document attribute `:legacy-do-not-insert-missing-sections:` is missing, i.e. if only Definitions/Conventions/References section is empty, there will be no duplication. Closing.

**Comment by opoudjis** [comment]
Let me confirm that, the duplication still shouldn't be happening

**Comment by opoudjis** [comment]
Was misnaming auto-inserted symbols section as Definitions, same title as terms section. Needed to insert anchor to Conventions in order to ensure it is autonumbered.
