### ISSUE TITLE
PDF: Table heading in ITU P.1203

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#207]
Heading of the Table 5 is not repeated at each new page in generated ITU P.1203 PDF.

PDF:
![image](https://user-images.githubusercontent.com/55683568/81407423-a8d74680-913b-11ea-8a2e-78c183300a00.png)
 
Original:
![image](https://user-images.githubusercontent.com/55683568/81407458-b8568f80-913b-11ea-8773-9e7af082bd77.png)

Source .adoc:
`|===`
`^.^h| ID ^.^h| Description ^.^h| Values ^.^h| Frequency ^.^h| Available to modes`
`5+| *_I.GEN_*`

From @Intelligent2013 (https://github.com/metanorma/mn-native-pdf/issues/153#issuecomment-629853654): 
> In the source XML there isn't table header:
> 
> ```
> <table id="table5">
> <name>I.11, I.13 and I.14 inputs description</name>
> <tbody>
> <tr>
> <th align="center">ID</th>
> <th align="center">Description</th>
> <th align="center">Values</th>
> <th align="center">Frequency</th>
> <th align="center">Available to modes</th>
> </tr>
> <tr>
> <td colspan="5" align="left">
> <strong>
> <em>I.GEN</em>
> </strong>
> </td>
> </tr>
> ```
> 
> Please note, that there are `th`, but they are in `tbody`. But should be in `thead` like this:
> 
> ```
> <table id="table5">
> <name>I.11, I.13 and I.14 inputs description</name>
> <thead>
> <tr>
> <th align="center">ID</th>
> <th align="center">Description</th>
> <th align="center">Values</th>
> <th align="center">Frequency</th>
> <th align="center">Available to modes</th>
> </tr>
> </thead>
> <tbody>
> <tr>
> <td colspan="5" align="left">
> <strong>
> <em>I.GEN</em>
> </strong>
> </td>
> </tr>
> ```

**Comment by opoudjis** [comment]
In order for table heads to be recognised (and repeated), the markup in AsciiDoc MUST introduce a blank line between the header line and the rest of the table. This has not happened in the document in question, presumably because it is not the default of the Word to Asciidoctor converter.

So:

````
[[table3]]
.Application areas, test factors, and coding technologies for which ITU-T P.1203 is not intended to be used
|===
.<h| Applications for which the model is not intended
.<| In-service monitoring of video UDP-based streaming, where packet loss introduces visible quality degradations
.<| Direct comparison/benchmarking of encoder implementations, and thus of services that employ different encoder implementations
````

needs to be:

````
[[table3]]
.Application areas, test factors, and coding technologies for which ITU-T P.1203 is not intended to be used
|===
.<h| Applications for which the model is not intended

.<| In-service monitoring of video UDP-based streaming, where packet loss introduces visible quality degradations
.<| Direct comparison/benchmarking of encoder implementations, and thus of services that employ different encoder implementations
````

And the same, I fear, throughout for any tables.
