### ISSUE TITLE
Word: referencing subclauses

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#208]
Cross-references for ITU subclauses should be in the format `clause x.y.z`, i.e. word "clause" should be written with small instead of capital C.

Original:
![image](https://user-images.githubusercontent.com/55683568/82585623-9676f700-9b96-11ea-8f56-6978ceaaf81d.png)
 
Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/82585570-7cd5af80-9b96-11ea-93af-c63305d4c7c0.png)

**Comment by opoudjis** [comment]
There is a reason I don't want to do this.

The reason I don't want to do this is, I don't want to detect whether the crossreference is at the start of a sentence, in which case "Clause" needs to be capitalised; it introduces a possibility of error I would rather avoid. @ronaldtse Can we possibly push back on this?

**Comment by opoudjis** [comment]
We will allow autodetection of sentence start within block, and override option of "start-of-sentence" in markup.

Demoting.

**Comment by opoudjis** [comment]
Will implement `<<xref,capital%>>` and `<<xref,lowercase%>>` to force casing in crossreferences.
