### ISSUE TITLE
Word: indentation when using attribute [class=steps]

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#209]
In ITU G.650.1, it can be seen that indentation settings for `[class=steps]` are different when comparing original document to the generated one. I'm not sure whether it was agreed to follow the pattern which is currently applied in Metanorma when it comes to `[class=steps]`, but the following difference is present:

Generated DOC:
![image](https://user-images.githubusercontent.com/55683568/82716164-5e56dd80-9c96-11ea-9dcc-b089a8ac0329.png)

Original DOC/Generated PDF:
![image](https://user-images.githubusercontent.com/55683568/82716172-69aa0900-9c96-11ea-9372-fe753f71ab65.png)

**Comment by opoudjis** [comment]
That seems to be an oversight; fixing.
