### ISSUE TITLE
Temporary build files polluting the MN source directory

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#21]
When building an ITU document, the following files are created by metanorma-itu as temporary build files but are not cleaned up.

<img width="378" alt="Screen Shot 2019-09-10 at 8 53 31 AM" src="https://user-images.githubusercontent.com/11865/64575878-786ebb00-d3a8-11e9-9321-8dee9c23988f.png">

This is not the first time that flavor gems "add files to the current directory" without proper cleanup. We must use a generic method in handling these files.

**Comment by opoudjis** [comment]
There is a generic mechanism. I'll need to find out why they weren't caught by it.

**Comment by opoudjis** [comment]
Had forgotten to do it.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
