### ISSUE TITLE
Is "Resolution" an official document type for ITU?

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#211]
I have noticed that this [document ITU sample](https://raw.githubusercontent.com/metanorma/mn-samples-itu/master/sources/T-RES-T.1-2016-MSW-E.adoc) (with this [output](https://metanorma.github.io/mn-samples-itu/documents/T-RES-T.1-2016-MSW-E.html)) has "resolution" set as doctype. But this value doesn't appear in the [official documentation](https://www.metanorma.com/author/itu/authoring/), so I wonder if "resolution" is an official document type for ITU.

**Comment by manuel489** [comment]
Well, given that "Resolution" is listed in the [Supported document layouts](https://github.com/metanorma/metanorma/wiki/Supported-document-layouts), I guess it is one of the official doctypes. Sorry. Closing.

**Comment by opoudjis** [comment]
If the official documentation is lagging, do update it, but in general I'm not documenting layouts, because they're open-ended.
