### ISSUE TITLE
References are not rendering properly

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#212]
Taking this [ITU doc](https://github.com/metanorma/mn-samples-itu/blob/master/sources/T-Editing-Guidelines-201602.adoc) as example:

````
[bibliography]
[[References]]
== References

* [[[ITU-T_A.5,ITU-T A.5]]] Recommendation ITU-T A.5 (2016), _Generic procedures for including references to documents of other organizations in ITU-T Recommendations._

* [[[ITU-T_A.23,ITU-T A.23]]] Recommendation ITU-T A.23, Annex A (2014), _Guide for ITU-T and ISO/IEC JTC 1 cooperation._
````

*Output:*

![Capture](https://user-images.githubusercontent.com/33627611/83356550-f4dd6b80-a334-11ea-8719-a6c79d5f5071.PNG)

**Comment by opoudjis** [comment]
Fixed, sorry: I switched rowspan=2 to colspan=2. @manuel489 Could you recheck?

**Comment by manuel489** [comment]
@opoudjis, I have re-checked. Now the identifiers are getting separated in lines:

````
[bibliography]
[[References]]
== References

* [[[ITU-T_A.5,ITU-T A.5]]] Recommendation ITU-T A.5 (2016), _Generic procedures for including references to documents of other organizations in ITU-T Recommendations._

* [[[ITU-T_A.23,ITU-T A.23]]] Recommendation ITU-T A.23, Annex A (2014), _Guide for ITU-T and ISO/IEC JTC 1 cooperation._
````

Output:
![Capture4](https://user-images.githubusercontent.com/33627611/83778839-39307a80-a659-11ea-8834-857fde101ea0.PNG)

**Comment by opoudjis** [comment]
Ugh. Of course, that is because it's a table with no set width; ITU in real life would be manually setting the table width.

I'm reluctant to do that, so I'm going to try making the hyphens non-breaking instead. Please retest.

**Comment by manuel489** [comment]
Yup! All good now @opoudjis

**Comment by manuel489** [comment]
Oh shoot! wait a moment. Looking at the DOC output:

![capture1](https://user-images.githubusercontent.com/33627611/83829005-ee8e1d00-a6af-11ea-9829-97c60d82d36b.PNG)

the identifiers are vertically centered respect to the reference content. Conversely, in HTML output this doesn't happen:

![capture2](https://user-images.githubusercontent.com/33627611/83829199-4dec2d00-a6b0-11ea-8ec8-f6b832b7ed93.PNG)

I rushed myself, sorry.

**Comment by opoudjis** [comment]
Sigh. Of course they are. OK, fixed.

**Comment by anermina** [comment]
> I'm reluctant to do that, so I'm going to try making the hyphens non-breaking instead. @manuel489 Please retest.

@opoudjis , this works fine in some cases, but in others we unfortunately still have an issue:

![image](https://user-images.githubusercontent.com/55683568/83913345-a59d9d80-a76f-11ea-889f-dc07a1ce839a.png)

**Comment by manuel489** [comment]
@anermina, could you point me the documents where you are not getting the proper result? (I get the expected rendering.)

**Comment by manuel489** [comment]
I believe the above example is from "T-Editing-Guidelines-201602", right?

Here's my output:
![capture3](https://user-images.githubusercontent.com/33627611/83915755-df57af80-a741-11ea-8c89-7e0a992874ff.PNG)

**Comment by manuel489** [comment]
Maybe you haven't fetched the updates yet. In my case, I execute `bundle update` using this Gemfile configuration:

````
source "https://rubygems.org"

gem "metanorma-cli"
gem "metanorma-itu", git: "https://github.com/metanorma/metanorma-itu"
gem "isodoc", git: "https://github.com/metanorma/isodoc"
````

**Comment by anermina** [comment]
@manuel489 It seems I executed `bundle update` prior to this change. Thanks, all good!

**Comment by manuel489** [comment]
Great! Well, there is a minor detail that maybe we can ignore (or maybe not). In DOC output, in one-line references, the *brackets* that wrap the identifier get cut in the inferior part making them look as "ceil symbols" (`⌈identifier⌉`). For example, 

DOC:
![capture5](https://user-images.githubusercontent.com/33627611/83925395-0c618d80-a755-11ea-8313-bb7fa51f3133.PNG)

This does not happen in PDF though:
PDF:
![capture5-pdf](https://user-images.githubusercontent.com/33627611/83925402-11264180-a755-11ea-9b46-1c2784ebea0f.PNG)

I have checked all the bibliographies from this repository and I trust that is the only detail is left.

**Comment by opoudjis** [comment]
That's bizarre! Setting spacing between bibliography table lines will take care of it.
