### ISSUE TITLE
Windows failing to run rspec

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#213]
https://github.com/metanorma/metanorma-itu/runs/727552758?check_suite_focus=true

**Comment by CAMOBAP** [comment]
Error in `sassc` native code, investigation in progress...

**Comment by CAMOBAP** [comment]
A similar problem exists in other repositories:
 - https://github.com/metanorma/mn-samples-iec/runs/731061747?check_suite_focus=true
 - https://github.com/metanorma/mn-samples-mpfa/pull/40/checks?check_run_id=731062788

sassc wasn't updated recently, we still use 2.2.1

Investigation in progress...

**Comment by CAMOBAP** [comment]
PR prepared https://github.com/metanorma/isodoc/pull/187

**Comment by opoudjis** [comment]
Huh. OK, thank you @CAMOBAP!
