### ISSUE TITLE
Word: Numbering subfigures in ITU documents

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#214]
In ITU G.650.1, subfigures are numbered in the format "Figure xa", "Figure xb", etc., where x is the corresponding figure number. 
Generated document numbers these subfigures with additional dash, i.e. in the format "Figure x-a", "Figure x-b", etc.

DOC:
![image](https://user-images.githubusercontent.com/55683568/83879369-cea53a80-a73d-11ea-91e7-c6671e23ef87.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83878691-d44e5080-a73c-11ea-9346-fc37ce63a6dc.png)

Cross-referencing therefore also differs. Original uses format "Figure xa", while generated DOC uses format "Figure x-a".

DOC:
![image](https://user-images.githubusercontent.com/55683568/83878526-93eed280-a73c-11ea-8055-749372833a78.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83879005-49218a80-a73d-11ea-80a3-e87e32ed5047.png)

**Comment by opoudjis** [comment]
This is an error in the document. The Editorial Guidelines are clear:

9.5.1

> When a figure is in 2 parts (e.g., Figure 6, part a and part b), refer to these parts in the text as follows: Figure 6-a, Figure 6-b. They may be referred to collectively as Figure 6.
