### ISSUE TITLE
Word: Nesting definition list in an item list

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#215]
Definition list nested in an item list should be indented accordingly. In generated DOC, it can be seen that symbols written in the form of definition list are moved to the left (aligned with the left document margin), comparing to the left margin for item e).

DOC:
![image](https://user-images.githubusercontent.com/55683568/83882994-3316c880-a743-11ea-8af1-e76a78fad12c.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83867287-78c69780-a729-11ea-83cd-45b15eb6f834.png)

**Comment by ronaldtse** [comment]
@anermina I also noticed that the equations are numbered differently in these two images! Which one is correct?

**Comment by anermina** [comment]
@ronaldtse They are numbered differently because prior to this we have equation 6-16 a) and 6-16 b) in the original document:
![image](https://user-images.githubusercontent.com/55683568/83888883-bab40580-a74a-11ea-91fe-af7ecaeb1a30.png)

These equations are numbered as 6-16 and 6-17 in generated DOC.
I hope there is no need for implementing some exception to allow numbering equations with a), b), etc.

**Comment by opoudjis** [comment]
> I hope there is no need for implementing some exception to allow numbering equations with a, b, etc.

In fact that's already been done: 

https://www.metanorma.com/author/topics/document-format/text/#multi-level-numbering

So markup would be:

````
[stem,subsequence=A]
++++
(6-16a)
++++

[stem,subsequence=A]
++++
(6-16b)
++++

[stem]
++++
(6-17)
++++
````

**Comment by ronaldtse** [comment]
@anermina is this issue fixed? Thanks!

**Comment by anermina** [comment]
> @anermina is this issue fixed? Thanks!

Unfortunately, it's not. Definition list is still not indented in .doc output, unlike in .pdf output, or the original.

**Comment by opoudjis** [comment]
The postprocessing function in Word to indent paragraphs and div's inside a list needs to also indent tables.
