### ISSUE TITLE
Document attribute `:hierarchical-object-numbering:` is not working

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#217]
With or without document attribute `:hierarchical-object-numbering:`, figures are not numbered hierarchically, rather as: Figure 1, Figure 2, etc.

Example from ITU Y.3507:

DOC:
![image](https://user-images.githubusercontent.com/55683568/83905956-ee028e80-a762-11ea-84bb-ff54a298eced.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83905989-fa86e700-a762-11ea-8897-245796eda3ab.png)

**Comment by opoudjis** [comment]
Issue has gone away, possibly as a result of the Presentation XML refactor: compiling the document locally, figures are numbered hierarchically.
