### ISSUE TITLE
Word: Horizontal spacing in nested item lists

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#218]
While comparing generated PDF/DOC outputs against the original ITU documents, I noticed a small indentation difference. Can we reduce horizontal spacing in item lists nested in tables, i.e. can we reduce spacing between the dash and the text which comes after?

DOC:
![image](https://user-images.githubusercontent.com/55683568/83909657-7d12a500-a769-11ea-8e36-31ed23a6b380.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/83909645-77b55a80-a769-11ea-8bdc-502ac240dece.png)

**Comment by opoudjis** [comment]
In short: can't fix.

The space after the bullet is a tab. Tab spacing is fixed at the start of a line; but in a table, the distance of the bullet from the nearest tab is going to be random. Tab in the Word document is every 1.27cm.

This is addressed in the original documents by a special "table text" style, with tabs every 0.5cm. I will see about inserting tabs into paragraphs in tables without a special style.

**Comment by opoudjis** [comment]
Done as postprocessing in Word before rendering: calculating margin offsets and having them override those assigned by default to the list.
