### ISSUE TITLE
Differentiate Annexes and Appendixes

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#22]
* Appendixes are non-normative annexes

* Appendixes are numbered separately from Annexes (Alphabetic vs Roman numbering)

* Annex titles are followed by "This annex forms an integral part of this #{doctype}"

* Appendix titles are followed by "This appendix does not form an integral part of this #{doctype}"

**Comment by ronaldtse** [comment]
I’ve asked ITU to confirm this.

**Comment by opoudjis** [comment]
Welp, if it turns out to be inaccurate, new ticket.

**Comment by ronaldtse** [comment]
@opoudjis this is confirmed:

> In ITU-T annexes are considered to be normative while appendices are informative.
