### ISSUE TITLE
Add "iteration" number in Recommendation Amendment, Corrigendum, and Resolution

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#229]
Currently, the "iteration" number (maybe it is called in another way) like shown below:

![amd-original](https://user-images.githubusercontent.com/33627611/90338318-dba09e80-dfb6-11ea-9d76-be1582c0dc2f.PNG)

![cor-original](https://user-images.githubusercontent.com/33627611/90338553-6e8e0880-dfb8-11ea-83cb-80d27d6c3641.PNG)

Does not appear in document types like: `recommendation-amendment`, `recommendation-corrigendum`, and `resolution`.

I think the right thing to do is introduce a new attribute (`:iteration-number:` or something)  in order to place this value and render in consequence. (Or maybe it does exist already?)

**Comment by opoudjis** [comment]
ISO has done these as `:amendment-number:`, `:corrigendum-number:`; will extend these to ITU, and inject them into structured identifier.
