### ISSUE TITLE
Add "iteration" number in Recommendation Amendment, Corrigendum, and Resolution

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#234]
Follow-on from https://github.com/metanorma/metanorma-itu/issues/229

If a document is an amendment or corrigendum, it will have //local_bibdata/ext/structuredidentifier/amendment or //local_bibdata/ext/structuredidentifier/corrigendum, containing the value "Amendment n" or "Corrigendum n".

This value will need to be prefixed to the title and displayed under the identifier, as in:

![amd-original](https://user-images.githubusercontent.com/33627611/90338318-dba09e80-dfb6-11ea-9d76-be1582c0dc2f.PNG)

![cor-original](https://user-images.githubusercontent.com/33627611/90338553-6e8e0880-dfb8-11ea-83cb-80d27d6c3641.PNG)

There will also be potentially a `//bibdata/title[@type = 'amendment']` or `//bibdata/title[@type = 'corrigendum']` to be added to the Amendment/Corrigendum identifier.

**Comment by Intelligent2013** [comment]
Done.
