### ISSUE TITLE
PDF format needed for technical report

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#236]
Follow-on from https://github.com/metanorma/metanorma-itu/issues/146, https://github.com/metanorma/mn-templates-itu/pull/11

[Technical_Report.docx](https://github.com/metanorma/metanorma-itu/files/5339639/Technical_Report.docx)

**Comment by opoudjis** [comment]
You can proceed with this now, attaching sample XML.

[sample-tr.zip](https://github.com/metanorma/metanorma-itu/files/5364831/sample-tr.zip)

**Comment by opoudjis** [comment]
Add to this technical paper as a doctype: as far as I can tell, their rendering is identical

[Uploading Technical_Paper.docx…]()

**Comment by Intelligent2013** [comment]
![изображение](https://user-images.githubusercontent.com/5559926/98788062-5f7cf200-2411-11eb-8c43-09e0359a88b4.png)
@opoudjis could you clarify, what are the xml elements for:
- the closest Series, 
- acronym

**Comment by opoudjis** [comment]
acronym could be the docnumeric element. xStr is currently the first letter of `bibdata/series[@type = 'main']/title`, and I should use abbreviation in there. 

But right now, I'm treating xSTR-ACRONYM as the atomic `docidentifier[@type = 'ITU']`. If there needs to be refinement to that, we can come back to it.

**Comment by Intelligent2013** [comment]
Done.
[a2.presentation.pdf](https://github.com/metanorma/metanorma-itu/files/5530727/a2.presentation.pdf)
