### ISSUE TITLE
Referring to formulas as Equations or Inequality

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#24]
Sometimes “equations” are referred to “equations”, yet sometimes “inequality”. Should we only use “Equation”, or allow the user to also override as “Inequality”? Should these be capitalized or in normal/lower case?

![image008](https://user-images.githubusercontent.com/11865/64980742-13a5ea00-d8ed-11e9-91ce-5443a5215a48.png)

> Again, it is not usual to refer to formulas as inequalities, but if we are strict, equations are those formulas that contain an equal sign, and inequalities are formulas that contain either the less than or bigger than sign. In this case, (3-3) is an inequality.
> ‘Equation’ should be capitalized if it is followed by the equation number. (There is a mistake in the paragraph following Equation 6-1. It should read “The mathematical equivalence of Equations 3-2 and 6-1…”

Technically we are able to detect via MathML whether we have an inequality or an equality sign. 

Apparently it is common to differentiate Equation and Inequality in math text, as seen in : https://tex.stackexchange.com/questions/190983/how-to-cross-reference-an-inequality-with-cref

**Comment by ronaldtse** [comment]
In a case like this, is this an Equation or an Inequality?

```
A = B > C
```

Or would it be better to allow the author to override on defining the equation (i.e. add an attribute that the type is "inequality")?

e.g.

```adoc
[stem] 
====
A = B > C
====
```

vs

```adoc
[equation] 
====
A = B > C
====
```

vs

```adoc
[inequality] 
====
A = B > C
====
```

**Comment by opoudjis** [comment]
I'd rather we not parse it, because we could get any of AsciiMath, MathML, or LaTeX in there. It's simpler just to do an override. FWIW, though, I would call the pathological A = B > C an inequality.

Because the output is multilingual, we will need the labels Equation and Inequality introduced into the YAML. So we won't have an open-ended set of labels: we will have Equation as the default (under "formula"), and allow an option attribute `%inequality%:

````
[stem%inequality]
++++
A
++++
````

**Comment by ronaldtse** [comment]
> I'd rather we not parse it, because we could get any of AsciiMath, MathML, or LaTeX in there. It's simpler just to do an override. FWIW, though, I would call the pathological A = B > C an inequality.

Agreed.

> Because the output is multilingual, we will need the labels Equation and Inequality introduced into the YAML. So we won't have an open-ended set of labels: we will have Equation as the default (under "formula"), and allow an option attribute %inequality:

The implemented solution seems proper -- @opoudjis could you help document this? It "might" be the case that it is more generic than ITU.

**Comment by opoudjis** [comment]
Generalised the code, though you will only see the difference in ITU, because that is the only gflavour at the moment where the labelling of inequalities and equations is differentiated.

**Comment by ronaldtse** [comment]
Thanks @opoudjis , does this mean that in the upcoming releases the other flavors will be able to apply the differentiation between inequalities and equations too?

**Comment by opoudjis** [comment]
In theory yes. Asciidoctor XML will do it universally. But it will only render any differently if the local isodoc yaml differentiates the labels for inequalities and formuae; at the moment, only the ITU yaml does.
