### ISSUE TITLE
PDF: Add ITU document type: implementers-guide

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#251]
Follow-on from https://github.com/metanorma/metanorma-itu/issues/144: implement PDF version of Implementers' Guide. Attached Word template, and sample PDF.

[Implementers_Guides.docx](https://github.com/metanorma/metanorma-itu/files/5523160/Implementers_Guides.docx)
[imp-guide.zip](https://github.com/metanorma/metanorma-itu/files/5523200/imp-guide.zip)

**Comment by Intelligent2013** [comment]
Done.
