### ISSUE TITLE
PDF of ITU Resolutions

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#268]
This is the PDF counterpart to https://github.com/metanorma/metanorma-itu/issues/133

See the attached as the document sample. See the source ticket for formatting requirements.

[t-res.zip](https://github.com/metanorma/metanorma-itu/files/5795717/t-res.zip)

The following changes have been introduced:

* Boilerplate is different for resolutions: resolutions do not have a /boilerplate/license-statement or the NOTE under /boilerplate/legal-statement
* Resolutions have inline-headers for subsections without a distinct title ("1.1. blah blah blah")
* Resolutions have new associated metadata: `//bibdata/ext/meeting, //bibdata/ext/meeting/@acronym, //bibdata/ext/meeting-place, //bibdata/ext/meeting-date`
* Resolution /sections/clause/h1 have a preceding paragraph, "SECTION n", of class "supertitle". (So the title of a clause is two paragraphs, but we treat only the second as the actual title, the first is the number of the clause.)
* Annexes in resolutions don't have the obligation text (normative/informative)
* The middle title of resolutions (the introduction to //sections) is different, and it is composed of `//bibdata/title[@type = 'resolution']` plus `//bibdata/title[@type = 'main']` as two separate paragraphs
* The middle subtitle of resolutions (appearing under the middle title) consists of `//bibdata/title[@type = 'resolution-placedate']` in parentheses, optionally followed by `//note[@type = 'title-footnote']` as footnotes
* //note[@type = 'title-footnote'] are rendered only on the middle subtitle. They are not rendered in situ
* Section numbers and cross-references can contain italics (`1<em>bis</em>`)

**Comment by Intelligent2013** [comment]
@opoudjis I have two questions:
1. there is a difference in title (preceding paragraph)
In //sections it encodes with `class="supertitle"`:
```xml
<clause id="section1" inline-header="false" obligation="normative">
	<p keep-with-next="true" class="supertitle">SECTION 1</p>
	<title depth="1">World Telecommunication Standardization Assembly</title>
```

but in annex - just with `align="center"`:
```xml
<annex id="appendixI" inline-header="false" obligation="informative">
	<p align="center">APPENDIX I<br/>(to RESOLUTION 1 (Rev. Hammamet, 2016))</p>
	<title>
			<strong>Information for submission of a Question</strong>
		</title>
```
Is there adoc markup issue or should I add a processing first `p` before `title` as supertitle also?

2. > //note[@type = 'title-footnote'] are rendered only on the middle subtitle. They are not rendered in situ

Looks like some text disappeared - `in situ`....

**Comment by opoudjis** [comment]
1. That is me being inconsistent. I'll fix it to be "supertitle".

2. I'm sorry: _in situ_ is a Latin phrase, meaning "in place", i.e. "without moving it" (https://en.wikipedia.org/wiki/In_situ). By "not rendered in situ", I mean "don't render it in he location where you found it". (We don't allow footnotes inside the title string, because it's open-ended where exactly they will be rendered, if at all; that's why they are instead dumped inside the document as a note.)

**Comment by Intelligent2013** [comment]
@opoudjis Thank you!

**Comment by Intelligent2013** [comment]
ITU xslt updated for Resolutions.
