### ISSUE TITLE
Support implementer's guide

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#269]
"Implementer's guide" is a separate doctype.

Issues:
* https://github.com/metanorma/mn-samples-itu/issues/124
* https://github.com/metanorma/mn-samples-itu/issues/125

The relevant PRs are:
* https://github.com/metanorma/mn-samples-itu/pull/134
* https://github.com/metanorma/mn-samples-itu/pull/135

## Word Layout issues

Cover page issues

<img width="362" alt="Screen Shot 2021-01-17 at 11 35 04 AM" src="https://user-images.githubusercontent.com/11865/104830252-0d949480-58b8-11eb-8e25-f73472d4ebea.png">

Cover page logo dropped below page
<img width="485" alt="Screen Shot 2021-01-17 at 11 35 16 AM" src="https://user-images.githubusercontent.com/11865/104830260-15eccf80-58b8-11eb-969b-5bddc71fbc8e.png">

Duplicated title in inner cover
<img width="435" alt="Screen Shot 2021-01-17 at 11 35 31 AM" src="https://user-images.githubusercontent.com/11865/104830263-1d13dd80-58b8-11eb-9289-3c16bbe32dd1.png">

## PDF Layout issues

Docnumber is missing on cover page
<img width="831" alt="Screen Shot 2021-01-16 at 4 11 23 PM" src="https://user-images.githubusercontent.com/11865/104806864-7d9e0e80-5815-11eb-9805-0b9fcfa5d1f8.png">

Inner cover duplicates title
<img width="868" alt="Screen Shot 2021-01-16 at 4 11 32 PM" src="https://user-images.githubusercontent.com/11865/104806869-81ca2c00-5815-11eb-831f-fe754b91719c.png">

Footer title truncated
<img width="626" alt="Screen Shot 2021-01-16 at 4 12 39 PM" src="https://user-images.githubusercontent.com/11865/104806887-acb48000-5815-11eb-8f8e-35e3f3df040c.png">

Bibliography not placed in a table, clause headers not to be centered
<img width="481" alt="Screen Shot 2021-01-17 at 11 36 27 AM" src="https://user-images.githubusercontent.com/11865/104830278-403e8d00-58b8-11eb-940f-e0571444b3db.png">

(Correct Word)
<img width="398" alt="Screen Shot 2021-01-17 at 11 36 45 AM" src="https://user-images.githubusercontent.com/11865/104830280-4a608b80-58b8-11eb-9ecf-a1d861e570ec.png">

**Comment by Intelligent2013** [comment]
> ### PDF Layout issues

> Docnumber is missing on cover page

Regarding example from https://github.com/metanorma/metanorma-itu/issues/251 for Implementers Guide doctype:
```xml
<xsl:when test="$doctype = 'implementers-guide'">
	<xsl:value-of select="/itu:itu-standard/itu:bibdata/itu:docidentifier[@type='ITU-Recommendation']"/>
	<xsl:text> </xsl:text>
	<xsl:value-of select="/itu:itu-standard/itu:bibdata/itu:ext/itu:doctype[@language = $lang]"/>
</xsl:when>
```

In source xml there isn't docidentifier[@type='ITU-Recommendation'], therefore we see only doctype on cover page:
```xml
<ext>
<doctype language="en">Implementers’ Guide</doctype>
...
```

**Comment by Intelligent2013** [comment]
> Inner cover duplicates title

Fixed.

![изображение](https://user-images.githubusercontent.com/5559926/105608580-cd9c4880-5db4-11eb-8cd1-0ac70c318437.png)

> Footer title truncated

It's same issue.
```xml
<xsl:when  test="$doctype = 'implementers-guide'">
	<xsl:value-of select="/itu:itu-standard/itu:bibdata/itu:ext/itu:doctype[@language = $lang]"/>
	<xsl:text> for </xsl:text>
	<xsl:value-of select="/itu:itu-standard/itu:bibdata/itu:docidentifier[@type='ITU-Recommendation']"/>
	<xsl:text> </xsl:text>
	<xsl:variable name="date" select="concat('(',substring(/itu:itu-standard/itu:bibdata/itu:date[@type = 'published']/itu:on,1,7), ')')"/>
	<xsl:value-of select="$date"/>
</xsl:when>
```
In source XML there isn't field `docidentifier[@type='ITU-Recommendation']`.

> Bibliography not placed in a table, clause headers not to be centered

Fixed.

![изображение](https://user-images.githubusercontent.com/5559926/105608627-13f1a780-5db5-11eb-8886-5b096ade3b4a.png)

Resulted PDFs:
[T-REC-P.Imp863-201805-I.presentation.pdf](https://github.com/metanorma/metanorma-itu/files/5860587/T-REC-P.Imp863-201805-I.presentation.pdf)
[T-REC-G.Imp8001-202002-I.presentation.pdf](https://github.com/metanorma/metanorma-itu/files/5860585/T-REC-G.Imp8001-202002-I.presentation.pdf)

**Comment by ronaldtse** [comment]
@Intelligent2013 is this the only issue that @opoudjis needs to deal with?

> In source xml there isn't docidentifier[@type='ITU-Recommendation'], therefore we see only doctype on cover page:

Thanks.

**Comment by opoudjis** [comment]
That docidentifier corresponds to `: recommendationnumber:`, which needs to be inserted into the source document.

(In retrospect, I'm realising that was better handled as `:complement-of:`, as a document relation; but I won't change the code.)

Updated the documents in question.
