### ISSUE TITLE
PDF for ITU document type: Supplement

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#271]
Follow-on to https://github.com/metanorma/metanorma-itu/issues/143

Need PDF rendering of Recommendation Supplements. Attaching a published document, and document I have generated.

[supp.zip](https://github.com/metanorma/metanorma-itu/files/5857064/supp.zip)

[T-REC-L.Sup37-202005-I!!PDF-E.pdf](https://github.com/metanorma/metanorma-itu/files/5857055/T-REC-L.Sup37-202005-I.PDF-E.pdf)

I draw your attention to the following updates:

* `//bibdata/series[@type = 'main']/title` now split into `//bibdata/series[@type = 'main']/title[@type = 'full']`, the complete series title, and `//bibdata/series[@type = 'main']/title[@type = 'abbrev']`, the single letter series abbreviation
* `//bibdata/docidentifier[@type = 'ITU-Supplement-Internal']`, the title of the supplement to use within the main document ("middle title")
* `//bibdata/docidentifier[@type = 'ITU-Supplement-Short']`, the title of the supplement to use in the document footer
* `//bibdata/docidentifier[@type = 'ITU-Supplement']`, the title of the supplement to use in the bottom of the coverpage
* the localised strings "series" and "doctype_dict"/"recommendation-supplement".

**Comment by Intelligent2013** [comment]
Done.
[supp.presentation.pdf](https://github.com/metanorma/metanorma-itu/files/5862533/supp.presentation.pdf)
