### ISSUE TITLE
i18n for Chinese

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#272]
From #5 .

All content retrieved through these documents:

* ITU-T Rec. G.113: https://www.itu.int/rec/T-REC-G.113-200102-S/en (has all languages)
* ITU-R Rec. P.1546-4: https://www.itu.int/dms_pubrec/itu-r/rec/p/R-REC-P.1546-4-200910-S!!PDF-C.pdf
* ITU-T A.1: https://www.itu.int/rec/T-REC-A.1-201909-I/en
* ITU-T A.5: https://www.itu.int/rec/T-REC-A.5-201909-I/en
* ITU-T A.25: https://www.itu.int/rec/T-REC-A.25-201909-I/en

**Comment by ronaldtse** [comment]
The translated text to Chinese:
* https://gist.github.com/ronaldtse/b05f701f346fbe196c8adbf9604108ff
* https://gist.github.com/ronaldtse/48ece5dc835dd46f0839fc26d9c147eb

------
@opoudjis however I believe these files have are conflating ISO sentences:

```yaml
external_terms_boilerplate: |
  <p>For the purposes of this document,
    the terms and definitions given in % apply.</p>
internal_external_terms_boilerplate: |
  <p>For the purposes of this document, the terms and definitions
    given in % and the following apply.</p>
```

This is definitely ISO, not ITU.
------

The translations for `in`, `and`, and `to` are not going to work, because the grammatical pattern differs between Chinese and English.

```
in: in
to: to
where: "where:"
```

I also can't find where "where" and "Key" are used.
-----

I can't find this usage in Chinese. Can you provide an English document so as to find the Chinese.

```
blankclause: This clause is intentionally left blank.
```

------

In general, the two files contain overlaps, and just for the term "clause" there are like 4 or 5. These files need to be re-formatted and somewhat cleaned up.

**Comment by ronaldtse** [comment]
I also believe that some of this is insufficient for generating the Operational Bulletin and Service Publications. For example, the Operational Bulletin contains several strings and name patterns I don't see a correspondence.

**Comment by ronaldtse** [comment]
In general I had to use Google search a lot in finding this.

In particular, the ITU A.1, A.5 and A.25 documents provide many of these terms.

**Comment by opoudjis** [comment]
The overlaps are for inheritance: the ITU file overrides the default file

**Comment by opoudjis** [comment]
> I also believe that some of this is insufficient for generating the Operational Bulletin and Service Publications. For example, the Operational Bulletin contains several strings and name patterns I don't see a correspondence.

There is going to be a lot of tweaking once we do real i18n for Chinese in ITU, I couldn't anticipate everything. This is at least a start.

**Comment by opoudjis** [comment]
Where https://gist.github.com/ronaldtse/48ece5dc835dd46f0839fc26d9c147eb contradicts the existing https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-zh-Hans.yaml , I am not changing it: recall that that file is generic. If ITU practice uses different phrases for Chinese than the (GB-derived) default, we will treat those as overrides specific to ITU.

**Comment by opoudjis** [comment]
I acknowledge that "in" and "to" are going to bite me later, and I defer that consideration to later...

**Comment by opoudjis** [comment]
Because there is such a backlog, I am doing a basic implementation now. There will be things it misses, but I prefer for them to be dealt with as bugs later on, compared against real documents.

**Comment by ronaldtse** [comment]
> Where https://gist.github.com/ronaldtse/48ece5dc835dd46f0839fc26d9c147eb contradicts the existing https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-zh-Hans.yaml , I am not changing it: recall that that file is generic. If ITU practice uses different phrases for Chinese than the (GB-derived) default, we will treat those as overrides specific to ITU. If you have translated a phrase in both the generic and the ITU phrase, and a generic equivalent is already in place, I am ignoring your generic translation.

It’s fine to get a start implemented but note that the model right now is inaccurate. ITU boilerplate does not inherit from ISO. It just doesn’t work like that. The proper model is to have one common set of boilerplate inherited by ISO and ITU. This conflation will 100% bite us later.

**Comment by opoudjis** [comment]
And that IS what I have done. isodoc gem contains the common model, and ITU and ISO inherit from it. And if the common model looks a lot like ISO right now, that's because I've have to start somewhere.
