### ISSUE TITLE
i18n for Arabic

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#274]
Related to #5 

From @ahmohsen46:
https://gist.github.com/AhMohsen46/300e4390aac4da3177c832822fed96d3/

I added a comment here for the files: https://gist.github.com/AhMohsen46/300e4390aac4da3177c832822fed96d3/#gistcomment-3631389

Ping @ahmohsen46 can you help update the gist? Thanks.

**Comment by AhMohsen46** [comment]
https://gist.github.com/AhMohsen46/300e4390aac4da3177c832822fed96d3/
@opoudjis that's the gist, I've updated the arabic yaml file one last time, can you please check if it looks okay?
let me know if any further assistance is needed please, thank you!

**Comment by opoudjis** [comment]
I'm sorry about ongoing delay, @AhMohsen46, I've got a backlog of bugs and projects I'm working through...

**Comment by AhMohsen46** [comment]
thanks @opoudjis , please let me know if i can be of any help

**Comment by ronaldtse** [comment]
@opoudjis this is blocking ituob/service-publications-docs#17 now

**Comment by ronaldtse** [comment]
Ping @Intelligent2013 I assume we need to do something with mn2pdf? Thanks.

**Comment by Intelligent2013** [comment]
> 
> 
> Ping @Intelligent2013 I assume we need to do something with mn2pdf? Thanks.

@ronaldtse  at first glance in mn2pdf we have to add the font with Arabic glyphs support only. Main changes should be done in xslt.

**Comment by AhMohsen46** [comment]
@opoudjis Hey Nick, is any further action required from my side?
Thanks

**Comment by opoudjis** [comment]
No, just reassigned you because I'd unassigned you.

**Comment by opoudjis** [comment]
It turns out that some parts of the files were untranslated, or in Chinese; could you please go through and address the remaining English? Please do so as a PR: 

https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-ar.yaml
https://github.com/metanorma/metanorma-itu/blob/master/lib/isodoc/itu/i18n-ar.yaml (just the "this clause intentionally left blank")

Please ask questions if anything in the list is unclear.

**Comment by ronaldtse** [comment]
@AhMohsen46 could you please help here? Thanks.

**Comment by opoudjis** [comment]
Finished in https://github.com/metanorma/isodoc/pull/305
