### ISSUE TITLE
ITU sub-clause title when in monospace gets centered

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#276]
From STL-manual.adoc in mn-samples-itu. The clause title should not be centered when in monospace.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/11865/110263164-cc378000-7ff0-11eb-882f-59faff9600ff.png">

**Comment by Intelligent2013** [comment]
Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/110338330-ee082580-8037-11eb-8000-dac7eaf2a8df.png)
