### ISSUE TITLE
Override normative/informative status of bibliography section

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#278]
In these documents:
- https://github.com/metanorma/mn-samples-itu/blob/master/sources/T-TUT-CCIT-2017-E.adoc
- https://github.com/metanorma/mn-samples-itu/blob/master/sources/T-TUT-CCIT-2015-E.adoc

(see issue metanorma/mn-samples-itu#141)

They use the clause title "References" for informative references, but the correct word according to ITU Editing Guidelines it is "Bibliography" -- "References" is reserved for normative references only.

I am currently using the hack:
```adoc
[bibliography,heading="Bibliography"]
== References
```

Which overrides the auto-detected heading. Maybe we should have a declarative mechanism like `[bibliography,type=informative]` for this purpose instead of relying on "heading". This also relates to i18n.

**Comment by opoudjis** [comment]
The value `normative=true/false` false is already used in the Metanorma/XML, so I would be using that as the attribute.

**Comment by ronaldtse** [comment]
I have sought clarification from ITU, awaiting reply.

**Comment by ronaldtse** [comment]
ITU-T response:

> Authors of non-normative publications are free to follow the structure and use the headings they feel will work best for their case.

So the "normative=true/false" option will work -- we just need to document this.
