### ISSUE TITLE
Supporting numeric reference tags in ITU-T Recommendations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#279]
From ITU-T
> Aside from non-normative publications, the bibliography of common text with ISO/IEC may also contain numeric tags.

This means that for ITU-T Recommendations, the bibliography of common text documents (same text with ISO/IEC, but native ITU layout) can contain numeric tags. 

So we need to support numeric tags in ITU-T Recommendations.

**Comment by opoudjis** [comment]
This is supported already as:

````
* [[[a,(3)ISO 690]]]
````

But the numeric tag is ignored in ITU. Will need to override that.
