### ISSUE TITLE
Word: Draft indication in header and footer for draft documents (ITU J.1108)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#282]
Original draft document contains draft indication in header and footer. Should we have this in generated documents?

Generated:
![image](https://user-images.githubusercontent.com/55683568/113490420-0a2da400-94ca-11eb-9aab-ef7932ac418d.png)
![image](https://user-images.githubusercontent.com/55683568/113490436-2a5d6300-94ca-11eb-9082-f3d4d3dfbf51.png)

Original:
![image](https://user-images.githubusercontent.com/55683568/113490424-0f8aee80-94ca-11eb-9ccd-221e7e9ca4e4.png)
![image](https://user-images.githubusercontent.com/55683568/113490441-2fbaad80-94ca-11eb-8cda-dc8f3abd1753.png)

**Comment by opoudjis** [comment]
Yeah, I guess so, was not aware of this. Will need that text internationalised, too...

**Comment by opoudjis** [comment]
I've done the footer. The header is going to be an i18n nightmare (e.g. Arabic _tawsia_ vs _mashrue tawsiat jadida_), and I would rather leave it until we have explicit guidance from ITU.

**Comment by opoudjis** [comment]
@ronaldtse @anermina Would it be possible to see what the headers of Word documents with "Draft new Recommendation" look like in each ITU language?

**Comment by opoudjis** [comment]
Changed my mind: *all* i18n is going to need heavy editing once we hit testing, and will need grammatical inflection. Will do a brute force implementation of prefixed "Draft new" for now.

**Comment by opoudjis** [comment]
The grammar is wrong, but that will be fixed later.
