### ISSUE TITLE
i18n for Russian

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-itu#287]
From #5.
* ITU-T Rec. G.113: https://www.itu.int/rec/T-REC-G.113-200102-S/en
* ITU-T A.1: https://www.itu.int/rec/T-REC-A.1-201909-I/en
* ITU-T A.5: https://www.itu.int/rec/T-REC-A.5-201909-I/en
* ITU-T A.25: https://www.itu.int/rec/T-REC-A.25-201909-I/en
* ITU-T E.119 (04/2017): https://www.itu.int/itu-t/recommendations/rec.aspx?id=13074

**Comment by opoudjis** [comment]
The required translations are the files:

https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-en.yaml
https://github.com/metanorma/metanorma-itu/blob/master/lib/isodoc/itu/i18n-en.yaml

Nominative Singulars only please; we will eventually use Project Fluent from Firefox, and source tagging, to indicate how to inflect the inserted text (so "see chapter 6" will be entered up as `смотрите <<ch6,case=acc>>`).

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-itu/issues/289

**Comment by opoudjis** [comment]
Please don't push them, just attach files here.

The ITU file overrides the isodoc file where they have the same key: the isodoc file is generic (and is basically ISO practice).

"to" (which is a bad idea) is used for reference ranges, "Clauses 2 to 9".

"key" is the key for the symbols used in a Figure.

**Comment by Intelligent2013** [comment]
Done: [i18n.ru.zip](https://github.com/metanorma/metanorma-itu/files/6409782/i18n.ru.zip)
