### ISSUE TITLE
i18n for Spanish

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#288]
Not at all urgent, but need Spanish translations for

https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-en.yaml
https://github.com/metanorma/metanorma-itu/blob/master/lib/isodoc/itu/i18n-en.yaml

**Comment by opoudjis** [comment]
Required for #5

**Comment by manuel489** [comment]
Hey @ronaldtse, seems like I don't have enough privileges to push branches in `metanorma-itu` and `isodoc`.
Would you like me to send you the translations through another way?

**Comment by opoudjis** [comment]
Please don't push them, just attach files here.

The ITU file overrides the isodoc file where they have the same key: the isodoc file is generic (and is basically ISO practice).

"to" (which is a bad idea) is used for reference ranges, "Clauses 2 to 9".

"key" is the key for the symbols used in a Figure.

**Comment by manuel489** [comment]
Thanks @opoudjis
Here are the files: [i18n-spanish.zip](https://github.com/metanorma/metanorma-itu/files/6408797/i18n-spanish.zip)
