### ISSUE TITLE
i18n for German

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#289]
https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-en.yaml
https://github.com/metanorma/metanorma-itu/blob/master/lib/isodoc/itu/i18n-en.yaml

**Comment by opoudjis** [comment]
Required for #5

**Comment by opoudjis** [comment]
@abunashir Do you think you would be able to do this?

**Comment by opoudjis** [comment]
Please don't push the files, just attach files here.

The ITU file overrides the isodoc file where they have the same key: the isodoc file is generic (and is basically ISO practice).

"to" (which is a bad idea) is used for reference ranges, "Clauses 2 to 9".

"key" is the key for the symbols used in a Figure.

**Comment by abunashir** [comment]
Hey man, I wouldn't trust my german but here is the yml file for iso doc - https://gist.github.com/abunashir/774cb6f6241da157e9d7c4ec5a82f8e1, Normally we use [DeepL](https://www.deepl.com/translator), which is quite accurate, but please double check before we push those out to actual user.

**Comment by opoudjis** [comment]
Mach dir kein angst, I expect us to ask ITU translators to review all internationalisations before anything goes out

**Comment by opoudjis** [comment]
Oh, allergeehter @abunashir, need this one too:

https://github.com/metanorma/metanorma-itu/blob/master/lib/isodoc/itu/i18n-en.yaml

**Comment by abunashir** [comment]
Here you go - https://gist.github.com/abunashir/4102b813f531c8295529331a3094d61c

**Comment by opoudjis** [comment]
Thank you!
