### ISSUE TITLE
PDF layout: add service-publications

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#293]
We need to render PDF output for documents of the type `service-publication`. 

See original ticket #148. 

All documents are available in https://github.com/ituob/service-publications-docs

_Originally posted by @ronaldtse in https://github.com/metanorma/metanorma-itu/issues/148#issuecomment-869175693_

**Comment by Intelligent2013** [comment]
@ronaldtse could you point me, which is reference doc/docx (https://github.com/ituob/service-publications-refs/) should be used for PDF layout development? They look very differently.

**Comment by ronaldtse** [comment]
@Intelligent2013 we follow the latest template, i.e.:

https://github.com/ituob/service-publications-refs/tree/master/1162-E.212

**Comment by Intelligent2013** [comment]
I'll add in this ticket any found missing data in the metanorma xml.
### 1. Annex number.
Source DOCX:
![image](https://user-images.githubusercontent.com/5559926/126485818-1ebe6704-03b7-4199-8aa2-fa1264492a13.png)

adoc:
```
:annex-id: No. 1162
```

**Comment by Intelligent2013** [comment]
### 2. Different font-size in title's components:
In the source docx font size for `Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions ` is 16pt,
font size for `(According to Recommendation ITU-T E.212 (09/2016))` is 14pt:
![image](https://user-images.githubusercontent.com/5559926/126501993-4e6cc59a-e1c6-4af9-a906-860fb8e1fa89.png)

Title in adoc:
```adoc
= Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions (According to Recommendation ITU-T E.212 (09/2016))
```
xml:
```xml
<title language="en" format="text/plain" type="main">Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions (According to Recommendation ITU-T E.212 (09/2016))</title>
```

I can't display it using by different font-sizes. Or can I split it by first `(` in xslt on-fly?

**Comment by Intelligent2013** [comment]
### 3. Title on 2nd page (issue relates to previous):
Original docx:
![image](https://user-images.githubusercontent.com/5559926/126518688-4d5348b5-b5d0-46fc-8443-9b69ba92fcf8.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/126518986-6ccd10b3-d583-4721-a9b8-6c4cb68e6ebe.png)


Reason - the title in adoc:
```adoc
= Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions (According to Recommendation ITU-T E.212 (09/2016))
```

**Comment by Intelligent2013** [comment]
### 4. Non-correct header before first table.
Original docx:
![image](https://user-images.githubusercontent.com/5559926/126540317-eb5b8b18-c071-4248-aa73-1fc1943e9fce.png)

Generated PDF:
![image](https://user-images.githubusercontent.com/5559926/126540362-ecdb023f-68de-43c6-a3d2-4e9073189efb.png)

**Comment by Intelligent2013** [comment]
### 5. Non-correct language code in xml for Arabic.
```xml
<title language="en" format="text/plain" type="main">&#1575;&#1604;&#1585; ...
...
<language current="true">en</language>
...

**Comment by Intelligent2013** [comment]
To do: in ITU xslt implement these rules for displaying titles vs. series for this cases:
### - if there is `series type="main"` and `type="secondary"` and not `type="tertiary"`, then don't show `title`:
```adoc
= Five-letter Code Groups for the use of the International Public Telegram Service
:bureau: T
:docnumber: 669
:series: FIVE LETTER CODE GROUPS* *FOR THE USE OF THE INTERNATIONAL PUBLIC TELEGRAM SERVICE
:series1: According to ITU-T Recommendation F.1 (03/98)
```
```xml
<title language="en" format="text/plain" type="main">Five-letter Code Groups for the use of the International Public Telegram Service</title>
...
<series type="main">
<title>FIVE LETTER CODE GROUPS* *FOR THE USE OF THE INTERNATIONAL PUBLIC TELEGRAM SERVICE</title>
</series>
<series type="secondary">
<title>According to ITU-T Recommendation F.1 (03/98)</title>
</series>
```
Original docx:
![image](https://user-images.githubusercontent.com/5559926/126630414-263d2258-1261-4e3b-957d-a45152abe8e6.png)


### - if there only `title`, then show it as is:
```adoc
= Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions (According to Recommendation ITU-T E.212 (09/2016))
```
```xml
<title language="en" format="text/plain" type="main">Mobile Network Codes (MNC) for the international identification plan for public networks and subscriptions (According to Recommendation ITU-T E.212 (09/2016))</title>
```
### -  if there are `series` `type=main` `secondary` and `tertiary`, then show the sequence `series` (all types) and `title`:
```adoc
= Form of Call Signs Assigned by Each Administration to its Amateur and Experimental Stations
:bureau: R
:docnumber: 1154
:series: Status of Radiocommunications between Amateur Stations of Different Countries
:series1: (In accordance with optional provision No. 25.1 of the Radio Regulations)
:series2: and
```
xml:
```xml
<title language="en" format="text/plain" type="main">Form of Call Signs Assigned by Each Administration to its Amateur and Experimental Stations</title>
...
<series type="main">
<title>Status of Radiocommunications between Amateur Stations of Different Countries</title>
</series>
<series type="secondary">
<title>(In accordance with optional provision No. 25.1 of the Radio Regulations)</title>
</series>
<series type="tertiary">
<title>and</title>
</series>
```
Original docx:
![image](https://user-images.githubusercontent.com/5559926/126630016-78306d8f-473e-415f-83f5-630333be555c.png)

### - if there is `title` and `series type="main"` only, then show both:
```adoc
= Access codes/numbers for mobile networks
:bureau: T
:docnumber: 1015
:series: According to ITU-T Recommendation E.164 (11/2010)
```
Original docx:
![image](https://user-images.githubusercontent.com/5559926/126630888-9832f7ea-2644-4b0f-8da7-74dcf6907597.png)

**Comment by Intelligent2013** [comment]
Xslt for ITU service-publication added (https://github.com/metanorma/mn-native-pdf/blob/master/xslt_src/itu.service-publication.core.xsl). But it should be updated later for https://github.com/metanorma/metanorma-itu/issues/297.
