### ISSUE TITLE
Complements processing

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-itu#297]
Source: https://github.com/metanorma/metanorma-itu/issues/293

Original docx (https://github.com/ituob/service-publications-refs/blob/master/978-F.68/T-SP-F.68-2011-MSW-E.doc):
![image](https://user-images.githubusercontent.com/5559926/126647698-a4445bf5-341b-48bb-b060-15c803884878.png)

adoc (https://github.com/ituob/service-publications-docs/blob/master/978-F.68/T-SP-F.68-2011-MSW-E.adoc):
```adoc
:complements: F.69 (06/1994), F.68 (11/1988)
```
Issue: in the generated xml there isn't data for complements.

**Comment by opoudjis** [comment]
Markup error: this should be:

````
:complements: ITU F.69;ITU F.68
````

See https://www.metanorma.org/author/ref/document-attributes/#document-relations

**Comment by opoudjis** [comment]
Relations have to be explicitly added in; only `part-of` and `translated-from` are supported by default. Added `complements`.
