### ISSUE TITLE
Is :language: attribute mandatory from authoring perspective?

### ISSUE THREAD

**Issue by strogonoff** [metanorma/metanorma-itu#3]
This gem’s docs say it is required:

> :language: The language of the document (only en for now) (mandatory)

This is also true for other flavour gems.

However, author’s [attribute reference](https://www.metanorma.com/author/ref/document-attributes/#languages-localization) I’ve compiled from other sources begs to differ, saying it defaults to `en` anyway.

I suppose the fact that it’s required is not that important to the author, and filling in missing `:language:` is taken care on a level outside of this flavour gem?

**Comment by ronaldtse** [comment]
This is a good question, and for @opoudjis to answer. FYI, ITU has 6 official languages (for every document). We can default to “en”.

**Comment by strogonoff** [comment]
if so I suppose Metanorma-ITU has ways to go to advance from alpha stage, Metanorma core only supports 3 languages as of yet AFAIK; also I believe it’d be better if Metanorma could check that all 6 languages are implemented for a given doc

**Comment by ronaldtse** [comment]
There is no limit to what languages supported by Metanorma, so it’s not a limitation for us. But you’re right, validation will need work to support the languages.

**Comment by strogonoff** [comment]
> There is no limit to what languages supported by Metanorma

Boilerplate currently exists only in 3 languages, but to allow ITU authors create documents hassle-free Metanorma would have to have YAML with boilerplate texts for all 6 languages required by ITU. I am not claiming it’s a limitation, just the matter of time and translation work.

**Comment by ronaldtse** [comment]
Yes you’re right. We should do that. Will file a ticket to the gem!

**Comment by strogonoff** [comment]
(Thank you, I didn’t file it myself as I wasn’t sure my understanding was entirely correct.)

**Comment by opoudjis** [comment]
This is an old issue with Metanorma, and originates with the fact that different standards have different language policies. 

As few attributes as possible should be mandatory, and in almost all flavours, the gem does default to English. That occurred a fair while back, but not as far back as when the documentation was written.

A couple of flavours allow a large number of languages: UNECE, ISO, ITU, GB (which defaults to Simplified Chinese). We still default to English in flavours other than GB, but the documentation should say that the language must be provided explicitly, for optics. 

I will need to update the documentation of attributes, to make that less misleading.

**Comment by ronaldtse** [comment]
> the documentation should say that the language must be provided explicitly, for optics

Why is that? I was with a user yesterday and was questioned why we have a long list of attributes that are not relevant to the author that can be hidden...

**Comment by opoudjis** [comment]
Because we do not want to be seen as anglocentric in the context of ISO, in particular.

**Comment by ronaldtse** [comment]
Hmm... well, it's true, but there ought to be some default...? And "default" means we don't need to fill in?...

**Comment by ronaldtse** [comment]
OK fine keep it explicitly required in the documentation. We will solve the long list of attributes via `metanorma create` 😉

**Comment by opoudjis** [comment]
There is a default, English.

**Comment by opoudjis** [comment]
I have changed the readme's not to make language mandatory, and to reflect the defaults where applicable.

**Comment by ronaldtse** [comment]
Thank you!
