### ISSUE TITLE
Tests are being skipped on GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#317]
Appears to apply throughout GHA:

https://github.com/metanorma/metanorma-itu/pull/316

https://github.com/metanorma/metanorma-nist/pull/309

**Comment by CAMOBAP** [comment]
Fixed for all repos, https://github.com/metanorma/metanorma-build-scripts/commit/4a0015514f56c445c076093c45f6fe4d06da9c14

To activate you can "restart all jobs" from GH Web
