### ISSUE TITLE
Subsume `:legacy-do-not-insert-missing-sections:` behavior into `document-scheme`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#321]
In ITU, we currently have `:legacy-do-not-insert-missing-sections:`. We will do the equivalent behaviour here as an unrecognised `document-scheme`.

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-ieee/issues/117#issuecomment-1200358259_

**Comment by opoudjis** [comment]
The use of "none" if the relevant clauses are empty is required as of 2016, and I strongly suspect 2011, but cannot verify. I will use "legacy" as the relevant document-schema.
