### ISSUE TITLE
Cross reference signifier still renders as "Annex".

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#33]
The cross reference signifier still renders as "Annex" when the section is nested in the appendix environment.

[cr-issue.zip](https://github.com/metanorma/metanorma-itu/files/3679452/cr-issue.zip)

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-itu/issues/27 : I fixed it, but forgot to push the button to create the pull request.
