### ISSUE TITLE
PDF: Generating "Summary" section with `[abstract]` markup

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#334]
On https://www.metanorma.org/author/itu/topics/markup/#preface-sections it is stated that "The summary sections of Recommendations are marked up with the style attribute `[abstract]`." 

However, when that is applied, both "Summary" and "Abstract" titles are shown in PDF.

````
[abstract]
== Summary

Artificial Intelligence (AI) refers to the ability of algorithms encoded in (...)
````

produces:
![image](https://user-images.githubusercontent.com/55683568/196051297-c0cd96fd-6bdc-4dec-b72e-85b4d0811e1b.png)

**Comment by Intelligent2013** [comment]
Presentation XML has the title `Abstract`:
```xml
		<abstract id="_summary" displayorder="1">
			<title>Abstract</title>
			<p id="_">Artificial Intelligence (AI) refers to the ability of algorithms encoded in
```

In ITU XSLT there is a special processing for `abstract` with `id="_summary"` - it shows `Summary` title before abstract body:
```xml
	<!-- Summary -->
	<xsl:template match="itu:itu-standard/itu:preface/itu:abstract[@id = '_summary']" priority="3">
	...
		<fo:block font-weight="bold" margin-top="18pt" margin-bottom="18pt">			
			<xsl:variable name="title-summary">
				<xsl:call-template name="getTitle">
					<xsl:with-param name="name" select="'title-summary'"/>
				</xsl:call-template>
			</xsl:variable>
			<xsl:value-of select="$title-summary"/>
		</fo:block>
		<xsl:apply-templates />
	</xsl:template>
```
(I've added this code more 2 years ago, and may be earlier the title in `abstract`[@id = '_summary']` was omitted...)

I.e. `Summary` title renders from ITU XSLT, but `Abstract` from XML.

So, I have to omit `abstract[@id = '_summary']/title` rendering.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/196243391-996be427-83eb-419b-9953-bbef6ad8fc4b.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
