### ISSUE TITLE
PDF: `:series:` document attribute doesn't get rendered

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#335]
If some value is given to the `:series:` document attribute, it doesn't get shown in PDF. However, it appears when the `:series1:` document attribute is used.

Following markup:
````
= Ethics and governance of artificial intelligence for health
:bureau: T
:docnumber: FG-AI4H DEL01
:series: Focus Group on Artificial Intelligence for Health (FG-AI4H)
````

gives this output:
![image](https://user-images.githubusercontent.com/55683568/196051378-db606df1-6345-4caa-9e89-25be82d88a84.png)

**Comment by Intelligent2013** [comment]
Presentation XML:
```xml
<series type="main">
<title>Focus Group on Artificial Intelligence for Health (FG-AI4H)</title>
</series>
```

but ITU XSLT expects that the `series[type='main']/title` has the attribute `type='full'`:
```xml
<fo:block text-transform="uppercase">
	<xsl:variable name="series_title" select="normalize-space(/itu:itu-standard/itu:bibdata/itu:series[@type = 'main']/itu:title[@type = 'full'])"/>
	<xsl:if test="$series_title != ''">
		<xsl:variable name="title">
			<xsl:if test="$doctype != 'resolution'">
				<!-- <xsl:text>Series </xsl:text> -->
				<xsl:call-template name="getLocalizedString">
					<xsl:with-param name="key">series</xsl:with-param>
				</xsl:call-template>
				<xsl:text> </xsl:text>
			</xsl:if>
			<xsl:value-of select="$series_title"/>
		</xsl:variable>
		<xsl:value-of select="$title"/>
	</xsl:if>
</fo:block>
<xsl:choose>
	<xsl:when test="$doctype = 'recommendation-supplement'"/>
	<xsl:otherwise>
		<xsl:if test="/itu:itu-standard/itu:bibdata/itu:series">
			<fo:block margin-top="6pt">
				<xsl:value-of select="/itu:itu-standard/itu:bibdata/itu:series[@type = 'secondary']"/>
				<xsl:if test="normalize-space(/itu:itu-standard/itu:bibdata/itu:series[@type = 'tertiary']) != ''">
					<xsl:text> — </xsl:text>
					<xsl:value-of select="/itu:itu-standard/itu:bibdata/itu:series[@type = 'tertiary']"/>
				</xsl:if>
			</fo:block>
		</xsl:if>
	</xsl:otherwise>
</xsl:choose>
```

(also, there is a processing for another value `type = 'abbrev' in XSLT).

From https://github.com/metanorma/metanorma-itu/issues/271 (PDF for ITU document type: Supplement):
> * `//bibdata/series[@type = 'main']/title` now split into `//bibdata/series[@type = 'main']/title[@type = 'full']`, the complete series title, and `//bibdata/series[@type = 'main']/title[@type = 'abbrev']`, the single letter series abbreviation

But may be this relates to the Supplement documents only. I'll check it.

**Comment by Intelligent2013** [comment]
I've tried to change the doctype to `:doctype: recommendation-supplement`, but again `series` didn't split into `full` and `abbrev`:
```xml
<series type="main">
<title>Focus Group on Artificial Intelligence for Health (FG-AI4H)</title>
</series>
```
The attributes `full` and `abbrev` were added in the commit https://github.com/metanorma/metanorma-itu/commit/ae9f982365fd6a982f04b133b50b6acf728e865b, but the branch `[feature/supplement](https://github.com/metanorma/metanorma-itu/compare/feature/supplement)` isn't merged yet.
Then I'll update XSLT to process both `series` structures:
- `series[@type = 'main']/title`
- `series[@type = 'main']/title[@type = 'full']` and `series[@type = 'main']/title[@type = 'abbrev']`

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/196243224-913303d9-f68f-4e3d-ad45-30861524d7c8.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
