### ISSUE TITLE
Unnumbered sections in ITU-WHO T-FG AI4H

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#337]
ITU-WHO T-FG AI4H has two sections ("Abbreviations and acronyms" and "Executive summary") which are unnumbered but aren't preface sections. They appear after the ToC of the original document, right before the main (numbered) sections.

In case `[%unnumbered]` attribute is used, it only applies to the "Executive summary" section, since "Abbreviations and acronyms" require numbering by default.

![image](https://user-images.githubusercontent.com/55683568/196052383-34ab9b38-62eb-46b4-8637-61c0f827d883.png)

In case `[preface]` attribute is used, it applies not only to these two sections but also to the "Introduction" section, which should be the first numbered section of the document.

![image](https://user-images.githubusercontent.com/55683568/196052375-68c367ca-ecf6-40e7-ba7a-b16e0b054859.png)

What is the correct markup and behavior of Metanorma in this case?

**Comment by opoudjis** [comment]
I guess of the two, [%unnumbered] on Abbreviations and acronyms is the least bad option. I know why I'm insisting on the numbering; let me work out whether I can relax that constraint.

**Comment by opoudjis** [comment]
<img width="355" alt="Screen Shot 2022-11-12 at 01 36 37" src="https://user-images.githubusercontent.com/1911039/201362273-88da9479-47cf-4236-a150-cb828fb2e577.png">
