### ISSUE TITLE
PDF: Numbers of references are not generated in the "Bibliography" section

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#338]
The "Bibliography" section doesn't contain reference numbers, although the proper numbers are used when referencing some source in the text.

Generated PDF:
![image](https://user-images.githubusercontent.com/55683568/196052674-51b179c3-269e-4fce-a4cd-c5bb0ddc3165.png)

Generated HTML:
![image](https://user-images.githubusercontent.com/55683568/196052868-249190a9-a617-42d3-b62a-722af527473e.png)

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/196243117-360dde0e-d735-4540-baf5-b616d062f67b.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
