### ISSUE TITLE
GHA appears to be ignoring Gemfile.devel

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#360]
Not fetching isodoc from Github:

https://github.com/metanorma/metanorma-bsi/actions/runs/3619868072/jobs/6101510186

cf. 

https://github.com/metanorma/metanorma-bipm/actions/runs/3638108689/jobs/6139916272

which does.

Same is happening in 

https://github.com/metanorma/metanorma-iho/actions/runs/3638581892/jobs/6140946638

**Comment by CAMOBAP** [comment]
@ronaldtse I have checked relevant PR/branches but there is no `Gemfile.devel` in those branches.

The initial idea was to:
1. Commit `Gemfile.devel` in a feature branch
2. Once development is done and the dependent gem released, remove `Gemfile.devel` before merging a feature branch to `main`

**Comment by opoudjis** [comment]
I'm sorry, I could have sworn that I'd checked Gemfile.devel in, but clearly I hadn't.
