### ISSUE TITLE
PDF: Editorial note rendering missing

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#372]
Document in question is this: https://github.com/metanorma/itu-sg17-td611

The editorial note type in ITU is not rendering properly:

```adoc
EDITOR: need to find a good definition here.
```

<img width="548" alt="Screen Shot 2023-01-20 at 12 57 23 PM" src="https://user-images.githubusercontent.com/11865/213620380-45f54566-c793-45a5-b284-32b4596e0bb9.png">

```adoc
[EDITOR]
====
a lot of work here to do

* How to do an ASN.1 project
* Do the scripts for the ASN.1 project
* How do to an electronic attachment
* How to perhaps automatically extract the human readable part and
insert it into this recommendation
* Etc.
====
```

<img width="516" alt="Screen Shot 2023-01-20 at 12 59 11 PM" src="https://user-images.githubusercontent.com/11865/213620597-2bba3f76-2fbd-43ef-a4b5-2d93dd64e6c9.png">

**Comment by ronaldtse** [comment]
In Word it looks like this, perhaps it can be improved:
<img width="824" alt="Screen Shot 2023-01-20 at 1 00 39 PM" src="https://user-images.githubusercontent.com/11865/213620748-294c603a-8d1b-47f8-adfc-6b782d3b7790.png">

**Comment by Intelligent2013** [comment]
ITU XSLT styles updated:

![image](https://user-images.githubusercontent.com/5559926/213675737-9d2ce5ad-1b38-4ec9-8e43-05fcf4054a8a.png)

![image](https://user-images.githubusercontent.com/5559926/213675777-f22de7fe-a175-4d6b-ada5-75ac2f410c12.png)

**Comment by ronaldtse** [comment]
Thank you!
