### ISSUE TITLE
XML/PDF: rendering of Abstract/Summary should not jump to the second page

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#373]
There is currently an issue with rendering differing according to the encoding:

```adoc

[abstract]
== Abstract

This document is the 2nd Revised baseline text for X.icd-schemas:
Vendor agnostic Security Data Schemas for Integrated Cyber Defense
Solutions
...
```

Results in this (new page before Abstract):
<img width="479" alt="Screen Shot 2023-01-20 at 1 29 04 PM" src="https://user-images.githubusercontent.com/11865/213624029-8c1b3727-3651-448d-a8b1-8a65b025e81c.png">

But:

```adoc

[abstract]
== Summary

This document is the 2nd Revised baseline text for X.icd-schemas:
Vendor agnostic Security Data Schemas for Integrated Cyber Defense
Solutions
...
```

Results in this (this layout is correct):
<img width="624" alt="Screen Shot 2023-01-20 at 1 28 02 PM" src="https://user-images.githubusercontent.com/11865/213623913-f72213cc-3444-462c-b606-91f1517ae50c.png">

The document in question is this:
* https://github.com/metanorma/itu-sg17-td611

**Comment by Intelligent2013** [comment]
The difference between adoc markup:
```
[abstract]
== Abstract
```
and
```
[abstract]
== Summary
```
and the Metanorma XML is only in `id` value:
```xml
<abstract id="_summary" displayorder="1"><title>Abstract</title>
```
```xml
<abstract id="_abstract" displayorder="1"><title>Abstract</title>
```
Title is 'Abstract' in both cases.
In the ITU XSLT there is a special processing for `abstract` with `id="_summary"` (https://github.com/metanorma/metanorma-itu/issues/334). In this case, the title 'Summary' substitutes instead of 'Abstract'. By default, the page break adds before each preface section (not in case for 'id="_summary"'). So I've updated ITU XSLT to fix it.

![image](https://user-images.githubusercontent.com/5559926/213677535-75c0cf43-df5b-401a-bad5-2374f7d06fe0.png)
![image](https://user-images.githubusercontent.com/5559926/213677583-72fef332-5e96-4f09-9244-e39083b5fc75.png)

**Comment by ronaldtse** [comment]
Thank you!

**Comment by ronaldtse** [comment]
Actually @Intelligent2013 , why don't we just make the first preface section "not break the page"?

**Comment by ronaldtse** [comment]
Oh, I see that it now does not break page at the first preface element. But why do we still have special processing for `_summary`?

**Comment by Intelligent2013** [comment]
> But why do we still have special processing for _summary?

From https://www.metanorma.org/author/itu/topics/markup/#preface-sections:
```
The summary sections of Recommendations are marked up with the style attribute [abstract].
```

For adoc:
```
[abstract]
== Summary
```
Metanorma XML contains the title `Abstract`, not `Summary`:
```xml
<abstract id="_summary" displayorder="1"><title>Abstract</title>
```
To show `Summary` in the PDF I've had to add a special workaround processing for `<abstract id="_summary"`.
Actually I don't know why metanorma-itu replaces 'Summary' from adoc to 'Abstract'.
@opoudjis could you explain it?

**Comment by opoudjis** [comment]
(In progress until I answer :)

**Comment by opoudjis** [comment]
I introduced functionality to enforce consistent naming of preface section titles years ago, and I'd forgotten to override it for ITU. Fixing.

**Comment by opoudjis** [comment]
This means you can remove your workaround, @Intelligent2013

**Comment by Intelligent2013** [comment]
> This means you can remove your workaround, @Intelligent2013

ITU XSLT updated.
