### ISSUE TITLE
Support ITU-T Meeting "Temporary Document" type

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#375]
From https://github.com/metanorma/itu-sg17-td611/issues/3

In ITU-T, they have "Temporary Document" documents for Study Group meetings.
The cover page in Word contains additional information (RED indicates ones we do not have metadata attributes for):

<img width="750" alt="Screen Shot 2023-01-20 at 6 54 01 PM" src="https://user-images.githubusercontent.com/11865/213678831-6b8212fd-7e61-4d23-ab8d-cb06c2c7d563.png">

**Comment by opoudjis** [comment]
Per discussion in https://github.com/metanorma/itu-sg17-td611/issues/3 , only implementing `:td-number:` for now, delaying implementation until I have clearer instructions.

**Comment by opoudjis** [comment]
https://github.com/metanorma/itu-sg17-td611/issues/3#issuecomment-1405174388

> So there are 2 things to do (these also need to be done with PDF):

> Add the TD number (and the provisional identifier) to the document page header
> Add the TD number (and the provisional identifier) to the original cover page (somehow)
> No need to generate the cover page as shown in this ticket.

**Comment by opoudjis** [comment]
[Αρχειοθήκη 2.zip](https://github.com/metanorma/metanorma-itu/files/10556423/2.zip)
