### ISSUE TITLE
Is it possible to remove the default bold header in a table block?

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-itu#38]
I'm trying to typeset a diagram using the table environment, but I need to remove the bold text form the header. I can't find the way how is done. (I have tried asciidoctor markup already.)

[diagram-sample.zip](https://github.com/metanorma/metanorma-itu/files/3691148/diagram-sample.zip)

**Comment by opoudjis** [comment]
> I'm trying to typeset a diagram using the table environment

Please don't. 

The `%unnumbered` attribute will prevent captions from being displayed, but you're already using that.

**Comment by manuel489** [comment]
Ok, thanks Nick.
