### ISSUE TITLE
(URGENT) PDF: Missing "Series" description on cover page, using old logo

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#381]
<img width="1071" alt="Screen Shot 2023-02-02 at 2 58 03 PM" src="https://user-images.githubusercontent.com/11865/216253798-6e53738b-631c-45bd-89cb-c63291b923a7.png">

1. The "Series" description is conspicuously missing
2. The ITU logo should be the new logo

* PDF: https://metanorma.github.io/mn-samples-itu/documents/Y.3507-201812.pdf
* Source: https://github.com/metanorma/mn-samples-itu/blob/main/sources/Y.3507-201812.adoc

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/216282958-a646af59-3254-4221-b775-703a47dd2270.png)
