### ISSUE TITLE
Word output: hangs on ITU Service Publication `1109-Q.708B/T-SP-Q.708B-2016-E.adoc`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#412]
From https://github.com/ituob/service-publications-docs/issues/43

This doesn't work -- it never returns:
```sh
$ time bundle exec metanorma 1109-Q.708B/T-SP-Q.708B-2016-E.adoc
```

However, as pointed out by @Intelligent2013 , the Java portion completes but the Ruby portion never completes. The PDF file is actually generated too.

I found the culprit being the DOC output:

This returns:
```
:mn-output-extensions: xml,html,pdf,rxl
```

This never returns:
```
:mn-output-extensions: xml,html,doc
```

_Originally posted by @ronaldtse in https://github.com/ituob/service-publications-docs/issues/34#issuecomment-1482319122_

**Comment by ronaldtse** [comment]
This is reproduced using Git gems:

```ruby
source "https://rubygems.org"

gem "metanorma", git: "https://github.com/metanorma/metanorma", branch: "main"
gem "metanorma-cli", git: "https://github.com/metanorma/metanorma-cli", branch: "main"
gem "metanorma-itu", git: "https://github.com/metanorma/metanorma-itu", branch: "main"
gem "metanorma-standoc", git: "https://github.com/metanorma/metanorma-standoc", branch: "main"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma-utils", git: "https://github.com/metanorma/metanorma-utils", branch: "main"
gem "sassc"
```

**Comment by opoudjis** [comment]
Table size is calculated in Word HTML to determine whether to split it between pages. This document contains a table with 6300 rows, and there are extreme inefficiencies with table size calculation, it is happening from scratch for each row.
