### ISSUE TITLE
XML validation spurious message: `element "admonition" not allowed here`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#466]
From https://github.com/openitu/X.icd-schemas/issues/5 by @taddhar

When running 'metanorma site generate' a very strange Metanorma error appears multiple times:

```
Metanorma XML Syntax: (XML Line 000133:73): element "admonition" not allowed here; expected element "admitted", "definition", "deprecates", "domain", "preferred", "related" or "subject"
```

The semantic XML generated does not seem to be incorrect.

**Comment by opoudjis** [comment]
This is absolutely not a false positive.

````
=== Terms defined in this Recommendation

// EDITOR: We should consider to bring ALL the event terms and attributes
// here so that they can be used and referred to by other Recommendations
// and normative work elsewhere, in particular as to potential alignment
// with OASIS OpenC2.
````

An editorial note does not belong in a terms definition. A *term* or a *clause* belongs in a terms definition.
