### ISSUE TITLE
(PDF) Broken layout when there is no `docnumber` set

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#468]
From https://github.com/openitu/X.icd-schemas/issues/3#issuecomment-1784860710:

ITU Recommendations are either published with a provisional name or a docnumber. Notice that both PDF layouts contain errors:

Documentation reference:
* https://www.metanorma.org/author/itu/ref/document-attributes/

There are two cases:
1. If a document has a `:provisional-name:`, it should set it without `:docnumber:`.
2. If a document is published with a code, then `:docnumber:` should be set.

## Case 1: Recommendation with provisional name

![image](https://github.com/metanorma/metanorma-itu/assets/11865/20d0626a-84db-45fd-969d-6dc36b93391e)

Problems:
* Missing "ITU-T" text on the top left corner
* Last line saying "Recommendation" but no name shown. This line should be removed when there is no docnumber.
* There should not be "CAUTION..." box because it is not "recently approved".

## Case 2: Recommendation with document number assigned

![image](https://github.com/metanorma/metanorma-itu/assets/11865/e2e762ed-3481-4566-9b94-caec15d540c9)

Problems:
* Last line should be "Recommendation X.1111", not "Recommendation T  X.1111".

**Comment by Intelligent2013** [comment]
@ronaldtse could you give me the access to the repository [https://github.com/openitu/X.icd-schemas](https://github.com/openitu/X.icd-schemas/issues/3#issuecomment-1784860710)? Because I don't see the screenshots:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/6e4836a8-8b9a-4771-8ca8-752381a883c8)
Thanks.

**Comment by ronaldtse** [comment]
@Intelligent2013 updated!

**Comment by Intelligent2013** [comment]
> ## Case 1: Recommendation with provisional name

> * Missing "ITU-T" text on the top left corner
> * Last line saying "Recommendation" but no name shown. This line should be removed when there is no docnumber.

Fixed:

![image](https://github.com/metanorma/metanorma-itu/assets/5559926/5a16bb9d-2250-443e-a4ba-895ebb0fffdb)

> There should not be "CAUTION..." box because it is not "recently approved".

ITU XSLT renders the text "CAUTION..." from the Presentation XML:
```xml
			<clause id="draft-warning" inline-header="false" obligation="normative">
				<title depth="2">CAUTION! PREPUBLISHED RECOMMENDATION</title>
				<p id="_70eaf4fb-5407-a798-95eb-e6d3b858436a">This prepublication is an unedited version of a recently approved Recommendation.
It will be replaced by the published version after editing. Therefore,
there will be differences between this prepublication and the published
version.</p>
			</clause>
		</legal-statement>
	</boilerplate>
```

@opoudjis could you omit it?

> ## Case 2: Recommendation with document number assigned

ITU XSLT renders the letter `T` from `bureau` element:
```xml
			<structuredidentifier>
				<bureau>T</bureau>
				<docnumber>X.1111</docnumber>
			</structuredidentifier>
		</ext>
	</bibdata>
```

@ronaldtse please confirm that `bureau` should be omitted in all cases.

**Comment by opoudjis** [comment]
And the prepub should be omitted because this is a provisional-name standard? OK, making separate ticket. I am pretty deluged.

**Comment by ronaldtse** [comment]
> ITU XSLT renders the letter T from bureau element

The T does not belong to the identifier number. The full identifier would be like "ITU-T Recommendation X.1111", the "T" should not be between "Recommendation" and "X".

**Comment by Intelligent2013** [comment]
> ## Case 2: Recommendation with document number assigned

> Problems:
> * Last line should be "Recommendation X.1111", not "Recommendation T  X.1111".

Fixed:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/b1701036-df24-4657-b958-2a6439f6cddd)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
