### ISSUE TITLE
(URGENT, HTML) TOC displays broken order

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#469]
<img width="321" alt="Screenshot 2023-10-31 at 6 49 14 PM" src="https://github.com/metanorma/metanorma-itu/assets/11865/36c184c9-17af-4b0d-950f-1f6418f2a4e0">

* 1 is gone
* 9 and 8 are swapped
* Bibliography is placed between 11 and 12

Likely related to the OGC TOC ordering bug as well:
* https://github.com/metanorma/metanorma-ogc/issues/597

**Comment by opoudjis** [comment]
it is IMPERATIVE that you provide the document you are writing a ticket about in tickets, and I have repeatedly told you so, Ronald. I do NOT have the capacity to read minds that you repeatedly seem to assume of me, and randomly telling me to fix an issue with no provision of context, and therefore no wherewithal to replicate, is sloppy and foolish.

Lucky for you in this instance, I know that you have recently been working on https://github.com/openitu/X.icd-schemas . However, the general rule if you fail to provide a document as context for a ticket is going to remain that I unassign myself and reject the ticket as invalid.

**Comment by opoudjis** [comment]
The issues have almost all been addressed, except that 1 is still not being generated. That however is an issue in the document itself, which I need to investigate:

![Screenshot 2023-11-12 at 17 03 48](https://github.com/metanorma/metanorma-itu/assets/1911039/b1232e71-f8a6-4a05-b7fb-5879a2897674)

**Comment by opoudjis** [comment]
For some bizarre reason, there is a scope clause in this document's boilerplate, and the function looking for clauses to order has grabbed it instead of the right clause. Fixing, by requiring that the numbered clause for document scope, if any, be under the /sections container.

**Comment by opoudjis** [comment]
![Screenshot 2023-11-13 at 12 53 25](https://github.com/metanorma/metanorma-itu/assets/1911039/8db84f1a-7527-4815-b568-26d859942e66)
