### ISSUE TITLE
(URGENT, PDF) Definition lists inconsistent in column alignments

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#473]
Reported by @taddhar in https://github.com/openitu/X.icd-schemas/issues/21 :

<img width="444" alt="Screenshot 2023-11-04 at 12 36 21 PM" src="https://github.com/metanorma/metanorma-itu/assets/11865/4178e085-3f68-40a2-86c6-64d95409e3d2">

**Comment by Intelligent2013** [comment]
@ronaldtse these lists are independent lists (the tables actually in the terms of XSL-FO). The auto-layout table width algorithm in `mn2pdf` applies independently for each table:

The columns widths calculated for the 9.10.2.1:
```xml
<fo:table-column column-width="proportional-column-width(620)"/>
<fo:table-column column-width="proportional-column-width(1142)"/>
```

The columns widths calculated for the 9.10.2.2 are:
```xml
<fo:table-column column-width="proportional-column-width(620)"/>
<fo:table-column column-width="proportional-column-width(1678)"/>
```

@opoudjis I don't remember exactly, but looks like we have the feature for definition list columns width for another SDOs. Do you remember it?

**Comment by opoudjis** [comment]
> @opoudjis I don't remember exactly, but looks like we have the feature for definition list columns width for another SDOs. Do you remember it?

It was indeed felt desirable, because some SDOs did in fact implement definition lists as tables in Word. NIST certainly does  it, for terms as well as definitions.

**Comment by opoudjis** [comment]
I can't find any other examples, although I'm convinced this has come up with ISO in the past...

**Comment by ronaldtse** [comment]
@opoudjis so is the solution to use a manual table (instead of a definition list) that includes manually set column widths?

This is key to fixing https://github.com/openitu/X.icd-schemas/issues/21

**Comment by opoudjis** [comment]
That is one way of solving it, but it would need to be done in Presentation XML if so, so that it carries across to all formats.

**Comment by opoudjis** [comment]
ITU want definition lists rendered as tables. The approach I had taken here was to leave the definition list in the Presentation XML as dl/dt, dl/dd, and leave the rendering as a Table downstream, as a PDF auto-table, a CSS grid in HTML, and a table in Word. 

The supposed problem is that this means the definition list columns won't line up with each other. 

Addressing this by imposing a uniform width on definition list tables is inevitably going to lead sooner or later to someone on ITU whining about some exception. When that time comes, they will be told the stock Metanorma answer to requests by SDOs to perpetuate formatting inconsistencies: if they want to keep authoring documents in Word, they know where to find it.

I am going to turn all definition lists in ITU into tables of class "dl", with 20% width for terms, in Presentation XML.

**Comment by opoudjis** [comment]
Note that definition lists are left alone if they are the children of tables, figures, or formulas (so we do not get intractable nesting of tables.)

**Comment by Intelligent2013** [comment]
Now, ITU XSLT renders so:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/0da5592c-c77f-4b96-b5d9-99c3b6ad08d6)

Issues: 
- ITU XSLT ignores table cells width `<th width="20%"` and `<td width="80%"`, because XSLT expects the table columns widths is the `table/colgroup/col/@width`
- no need to apply table styles to the `table` with `class="dl"`

Presentation XML:
```xml
<table id="_1552205f-c9f1-d661-4863-f429d21f7a93" class="dl">
	<tbody>
		<tr>
			<th width="20%">Description</th>
			<td width="80%">
				<p id="_2439a912-2533-8ffe-b47a-c62db3378761">The name of the entity</p>
			</td>
		</tr>
		<tr>
			<th width="20%">Requirement</th>
			<td width="80%">
				<p id="_fae9297d-7fd5-51b3-681f-f83ec47129e9">
					<tt>recommended</tt>
				</p>
			</td>
		</tr>
	</tbody>
</table>
```

I have to fix ITU XSLT.

**Comment by opoudjis** [comment]
My turn to fix this:

* I will leave dl in the Presentation XML, since that is what @Intelligent2013 would much rather work with
* I will insert into the dl :
````
<colgroup>
		<col col="20%"/>
		<col col="80%"/>
</colgroup>
````
as that is what @Intelligent2013 processes—even though that is not legitimately part of `dl`
* I will convert Presentation XML dl in HTML and DOC to `table[@class = 'dl']` before further processing
