### ISSUE TITLE
(PDF, Word) New ITU cover page and layout

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#474]
ITU has updated their cover page, which now applies to ITU-T Recommendations:

For example:
* https://www.itu.int/dms_pub/itu-t/oth/0a/0f/T0A0F0000040005PDFE.pdf

We need to find out if there's anything else that has changed:
* cover page
* other layout issues (and different document types)

I suspect there must be a branding guide of some sort?

FYI @taddhar @simaocampos

**Comment by ronaldtse** [comment]
I've emailed Anibal.

**Comment by simaocampos** [comment]
That's better, as Anibal is the reference person for the publication templates.
Simão

**Comment by ronaldtse** [comment]
Thanks @simaocampos !

**Comment by ronaldtse** [comment]
I've received the following publishing guidelines from Anibal:

> Yes, the layout changed, but it’s only the cover page. They are now aligned with the (new) ITU visual guidelines.
> Please see attachment.

@Intelligent2013 this can now be actioned. Thanks!

[Guidelines-Publication-Covers.pdf](https://github.com/metanorma/metanorma-itu/files/14373082/Guidelines-Publication-Covers.pdf)

**Comment by Intelligent2013** [comment]
The requirements (draft):
- fonts:
   - 'Avenir Next' - main ITU font for Latin and Cyrillic scripts.
   - 'Janna' for Arabic
   - 'M Ying Hei' for Chinese.

Note: the font Arial is using in the PDF example from the initial post (https://www.itu.int/dms_pub/itu-t/oth/0a/0f/T0A0F0000040005PDFE.pdf)

- support Arabic (Right-to-Left language)

- document attributes
  - bureau name
  - sector name

**Comment by Intelligent2013** [comment]
> Moreover, the ITU Table of Contents is in the font "Adelle CYR" (Adelle Sans Cyrillic)

@ronaldtse I think that we need to update the cover page only, we don't need to apply the styles from Guidelines ToC. The example PDF from the initial post contains only changed cover page, the ToC in old style:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/cadfe6dd-eb81-43bd-8736-8fbe41f2aa13)


I have a question. On the page 8 (Technical publications) said that the color logo is black:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/7f024c98-c94f-42c9-ae22-cbf939e50364)

But in the next pages we see the blue logo:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/913e9221-9cfa-4b35-a871-e77d3d884f10)

And the example PDF also has blue logo:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/cf0a9f2a-2761-46a4-b995-0d5c599aabad)

What is the right option?

**Comment by Intelligent2013** [comment]
The document attributes:
- collection/series (optional):
`:presentation-metadata-collection: Recommendations`
- sector name
`:presentation-metadata-sector: Standardization Sector`
if sector name is empty, then i18n predefined localized string will be used, for example:
```xml
		<localized-string key="tsb_short" language="en">Telecommunication Standardization Bureau</localized-string>
		<localized-string key="br_short" language="en">Radiocommunication Bureau</localized-string>
		<localized-string key="bdt_short" language="en">Telecommunication Development Bureau</localized-string>
```

**Comment by Intelligent2013** [comment]
@ronaldtse I would like to clarify the scope of this task. Do we need to support the new cover page for Technical publications only, i.e.:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/f84fd99e-a806-477a-9ab3-5fa5fc9a6317)

or should we support another layouts?  A few years ago we've added a support for `service-publication` (https://github.com/metanorma/metanorma-itu/issues/293), the first page looks so:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/6587917d-4de2-46f3-a54d-47561959b418)

Regarding Guidelines, the `BR Service Publications` relates to the Flagship cover template:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/4f5f4d2b-d660-4e1e-b0d9-9b6e3e9103ca)
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/7ad16586-5818-46eb-866a-855b34dcc3b2)

The Flagship publications cover template looks so:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/c0d88211-006b-4539-bac2-727f7bdd8fa8)

and contains the additional entities (we need the additional document attributes for them):
- title color (black or white)
- background image (with the band, because it has different design):
- ITU logo color (blue or white)
- additional logos
   - Event logos
   - Partner logos 
   - Co-publisher logos

Do we need support the Flagship template?

**Comment by ronaldtse** [comment]
@Intelligent2013 yes we need to support "Service Publications", hence the Flagship template.

Also, page 12 says: for “Slogan”, "Adelle italic for latin and cyrillic scripts, Traditional arabic for Arabic and STKaiti for Chinese."

* "Adelle italic" can be substituted by the macOS "Adelle Devanagari"
* ["Traditional Arabic"](https://learn.microsoft.com/en-us/typography/font-list/traditional-arabic) is provided on Windows and Office.
* "STKaiti" is only provided by Office.

Fontist currently does not support any of these fonts.

**Comment by ronaldtse** [comment]
> The document attributes:
> 
> * collection/series (optional):
>   `:presentation-metadata-collection: Recommendations`
> * sector name
>   `:presentation-metadata-sector: Standardization Sector`
>   if sector name is empty, then i18n predefined localized string will be used, for example:
> 
> ```
> 		<localized-string key="tsb_short" language="en">Telecommunication Standardization Bureau</localized-string>
> 		<localized-string key="br_short" language="en">Radiocommunication Bureau</localized-string>
> 		<localized-string key="bdt_short" language="en">Telecommunication Development Bureau</localized-string>
> ```

These need to be officially `metanorma-itu` attributes.

**Comment by Intelligent2013** [comment]
I propose these visual appearance document attributes (similar to https://github.com/metanorma/metanorma-bsi?tab=readme-ov-file#visual-appearance)

- `:coverpage-image:`
image location, for image to be included on the PDF cover page. Image location is relative to the source document.

- `:coverpage-image-event-logo:`
Comma-delimited list of image locations, for images to be included on the PDF cover page as 'event logos'. All image locations are relative to the source document.

- `:coverpage-image-partner-logo:`
Same, for images to be included on the PDF cover page as 'partner logos'.

- `:coverpage-image-copublisher-logo:`
Same, for images to be included on the PDF cover page as 'co-publisher logos'.

- `:presentation-metadata-color-cover-title:`
Title colour on PDF cover, as 'black' (default) or 'white', depending on the contrast with the background.

- `:presentation-metadata-cover-header-hide:`
Hide page header titles (ITUPublications, International Telecommunication Union, Sector or Bureau name). The values are 'true' or 'false' (default).

- `:presentation-metadata-color-cover-itu-logo:`
ITU logo color - 'blue' (default) or 'white'. Allows to choose the color to contrast with background.

Note: the attributes `:coverpage-image-...` should be added into metanorma-itu.

**Comment by Intelligent2013** [comment]
> Also, page 12 says: for “Slogan”, "Adelle italic for latin and cyrillic scripts, Traditional arabic for Arabic and STKaiti for Chinese."

@ronaldtse is there any sample where (and which font-size) slogan should be render?

**Comment by ronaldtse** [comment]
@Intelligent2013 we don't have a sample. Could you extrapolate the font size from the minimized images? Thanks.

**Comment by Intelligent2013** [comment]
ITU XSLT updated for new cover page (Technical and Flagship publications).

Regarding fonts for slogan title:
> * "Adelle italic" can be substituted by the macOS "Adelle Devanagari"
> * ["Traditional Arabic"](https://learn.microsoft.com/en-us/typography/font-list/traditional-arabic) is provided on Windows and Office.
> * ["STKaiti"](https://learn.microsoft.com/en-us/typography/font-list/stkaiti) is only provided by Office.

As existence of the slogan title currently is rare case, then the font name should be specified manually in the document attributes (vs. in the processor.rb in metanorma-itu gem for mainly using fonts):
```
:fonts: Traditional Arabic
```
(see `:fonts:` description in https://www.metanorma.org/author/ref/document-attributes/#visual-appearance)

These fonts can't be installed by fontist (currently don't supported), but fontist may find these fonts on the user machine and pass them into mn2pdf via the font manifest file.
I.e. user responsibility for pre-installed these fonts.

**Comment by ronaldtse** [comment]
@Intelligent2013 can you please help create a blog post for the new ITU layout? Thanks!
