### ISSUE TITLE
(PDF, Word) Tables should have column headings "bold-faced and centred, and its first letter shall be capitalized"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#496]
From https://github.com/openitu/X.icd-schemas/issues/17

<img width="784" alt="Screenshot 2024-02-22 at 10 04 42 PM" src="https://github.com/metanorma/metanorma-itu/assets/11865/811b2f20-f7ce-4eeb-803e-4ba4b7fef3ae">

Now:
<img width="797" alt="Screenshot 2024-02-22 at 10 07 42 PM" src="https://github.com/metanorma/metanorma-itu/assets/11865/85972855-52ff-49a7-91a3-6ca03d701d1c">

**Comment by opoudjis** [comment]
I need to set the centering for table columns, @Intelligent2013, so there is nothing here for you to do.
