### ISSUE TITLE
Metanorma-ITU should support all 6 ITU official languages

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#5]
As discussed in #3 , we need the boilerplate in YAML to support all 6 ITU languages.

They are:
* Arabic
* Chinese
* English
* French
* Russian
* Spanish

(No. 171 of the ITU Constitution)

https://www.itu.int/en/publications/SiteAssets/Res%20168%20procedure-FINAL.pdf

Update: from these documents you can find all corresponding texts listed in the YAML files:
* ITU-T Rec. G.113: https://www.itu.int/rec/T-REC-G.113-200102-S/en (has all languages)
* ITU-R Rec. P.1546-4: https://www.itu.int/dms_pubrec/itu-r/rec/p/R-REC-P.1546-4-200910-S!!PDF-C.pdf
* ITU-T A.1: https://www.itu.int/rec/T-REC-A.1-201909-I/en
* ITU-T A.5: https://www.itu.int/rec/T-REC-A.5-201909-I/en
* ITU-T A.25: https://www.itu.int/rec/T-REC-A.25-201909-I/en

**Comment by opoudjis** [comment]
Someone is going to have to provide me translations for all six.

**Comment by ronaldtse** [comment]
Translations for which strings?

I've uploaded all 6 languages of E.119 (https://www.itu.int/itu-t/recommendations/rec.aspx?id=13074) in Word to `mn-itu-docs` under `references/itu-t/`

**Comment by opoudjis** [comment]
> Translations for which strings?

isodoc-yaml: https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-en.yaml

Without Spanish, Russian, Arabic for these, we cannot meaningfully claim we support the six languages. And Arabic is presumably going to have punctuation challenges of its own.

There is a reason I am reluctant to keep expanding the scope of Metanorma...

**Comment by opoudjis** [comment]
... And no, I am not going to go through three Word documents, randomly hoping to work out what the Arabic for "figure" or "foreword" is. Someone is going to need to provide me translations.

**Comment by opoudjis** [comment]
This is still an action on you @ronaldtse. Get them to provide translations for:

https://github.com/metanorma/metanorma-standoc/blob/master/lib/asciidoctor-yaml/i18n-en.yaml
https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-en.yaml
https://github.com/metanorma/metanorma-itu/blob/master/lib/asciidoctor/itu/i18n-en.yaml
https://github.com/metanorma/metanorma-itu/blob/master/lib/isodoc/itu/i18n-en.yaml

(for the first two, not all fields are relevant to ITU.)

**Comment by ronaldtse** [comment]
@opoudjis Regarding https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-en.yaml
 shouldn't this be moved to `metanorma-standoc`?

**Comment by opoudjis** [comment]
No

**Comment by ronaldtse** [comment]
@opoudjis can you help check which files are necessary for translation? Thanks!

**Comment by opoudjis** [comment]
https://github.com/metanorma/isodoc/blob/master/lib/isodoc-yaml/i18n-en.yaml
https://github.com/metanorma/metanorma-itu/blob/master/lib/isodoc/itu/i18n-en.yaml

I have added "Page" to itu/i18n-en.yaml, to internationalise the table of contents header.

**Comment by opoudjis** [comment]
I am adding other headings that emerge from the service publication documents, but I can copy paste those from the cover pages of the preexisting Word documents.

**Comment by ronaldtse** [comment]
I've done Chinese in #272, issues raised there for @opoudjis .

**Comment by AhMohsen46** [comment]
@ronaldtse that's the best I think I can get to with Arabic as per the english docs and the arabic docs
https://gist.github.com/AhMohsen46/300e4390aac4da3177c832822fed96d3/

**Comment by ronaldtse** [comment]
@AhMohsen46 I've moved Arabic to a separate issue here: https://github.com/metanorma/metanorma-itu/issues/274

**Comment by ronaldtse** [comment]
@opoudjis can we indicate which languages are now supported and can be closed? Thanks.

**Comment by opoudjis** [comment]
We don't have Russian or Spanish, so not yet.

**Comment by ronaldtse** [comment]
Spanish: @manuel489 can you help?

Russian: @intelligent2013 can you help?

**Comment by opoudjis** [comment]
@manuel489 Making you a ticket

**Comment by opoudjis** [comment]
And I've undertaken to do German (god help me), so I'll close this ticket in favour of those.

**Comment by opoudjis** [comment]
https://github.com/metanorma/metanorma-itu/issues/288
https://github.com/metanorma/metanorma-itu/issues/289
