### ISSUE TITLE
Notes font size doesn't match the original

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#50]
Single-paragraph notes have smaller font size than in original .doc. Multiple-paragraph notes have bigger font size than in original .doc.

[NOTE_size.zip](https://github.com/metanorma/metanorma-itu/files/3725219/NOTE_size.zip)

**Comment by opoudjis** [comment]
Stylesheet has p.Note as 10pt; it should be 11pt.

**Comment by opoudjis** [comment]
Issue fixed. The second issue is a mark up error, I'm afraid: a multiparagraph Note is not marked up in Asciidoctor as:

````
NOTE:
Paragraph 1

Paragraph 2
````

but as 

````
[NOTE]
====
Paragraph 1

Paragraph 2
====
````

@anermina, please fix the markup accordingly. @manuel489 @tgolubev, if you have any multiple paragraph notes, please ensure they are marked up correctly.
