### ISSUE TITLE
Document attribute for collection/series

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-itu#504]
Source ticket: https://github.com/metanorma/metanorma-itu/issues/474#issuecomment-1966451196

The documentation (see Guideline https://github.com/metanorma/metanorma-itu/issues/474#issuecomment-1959472072) provides for publication of 'Collection/series (optional)' on the cover page:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/d56b8487-0cbc-4dbb-b873-7885a2979e61)

In the metanorma-itu there is the attribute :series:` already  for another purpose (https://www.metanorma.org/author/itu/ref/document-attributes/).

There is only one example (the text 'Recommendations'):
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/cc76f4d4-aa78-4f62-ac24-65bb9bd2b8b9)

I propose to add the attribute `:title-collection:` or `:collection:`.
Example:
`:title-collection: Recommendations`.

**Comment by opoudjis** [comment]
Have put the collection title into the HTML title page. Not doing so in the Word page, without explicit guidance on where it should go, if anywhere.
