### ISSUE TITLE
Document attribute for sector name

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-itu#505]
Source ticket: https://github.com/metanorma/metanorma-itu/issues/474#issuecomment-1966451196

We need to publish the 'Sector or Bureau name` on the cover page (see Guideline https://github.com/metanorma/metanorma-itu/issues/474#issuecomment-1959472072):
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/d56b8487-0cbc-4dbb-b873-7885a2979e61)

The bureau name can be determined automatically by letter from the attribute `:bureau: ...` and these localized string from `metanorma-itu` gem will be used:
```
 		<localized-string key="tsb_short" language="en">Telecommunication Standardization Bureau</localized-string>
 		<localized-string key="br_short" language="en">Radiocommunication Bureau</localized-string>
 		<localized-string key="bdt_short" language="en">Telecommunication Development Bureau</localized-string>
```

PDF example with sector name:
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/9f8838c3-452e-429c-b475-3bb666bf5f84)

For sector name I propose to add the attribute `:sector:`, for example:
```
:sector: Standardization Sector
```

Note: If sector name isn't set, then i18n predefined localized string will be used in the PDF.

**Comment by opoudjis** [comment]
//bibdata/ext/editorialgroup/sector
