### ISSUE TITLE
Visual appearance document attributes

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-itu#506]
Source issue: https://github.com/metanorma/metanorma-itu/issues/474#issuecomment-1969044338

We need to add these attributes for ITU "Service Publications" (Flagship):

- `:coverpage-image:`
image location, for image to be included on the PDF cover page. Image location is relative to the source document.

- `:coverpage-image-event-logo:`
Comma-delimited list of image locations, for images to be included on the PDF cover page as 'event logos'. All image locations are relative to the source document.

- `:coverpage-image-partner-logo:`
Same, for images to be included on the PDF cover page as 'partner logos'.

- `:coverpage-image-copublisher-logo:`
Same, for images to be included on the PDF cover page as 'co-publisher logos'.

Note: similar to https://github.com/metanorma/metanorma-bsi?tab=readme-ov-file#visual-appearance.

**Comment by Intelligent2013** [comment]
@ronaldtse may be it would be better to put the logos on cover page directly by the designer/user? Then we don't need to introduce these parameters:
> `:coverpage-image-event-logo:`
> `:coverpage-image-partner-logo:`
> `:coverpage-image-copublisher-logo:`


From Guidelines:

> **Partner logos** also appear in the bottom left corner.
Please note that when there are multiple partners /
sponsors / collaborators and not enough space
on the cover to include all the logos, they can be
placed on the title page instead (first page
of the publication).

It means that we need to allow the user to specify second page with additional logos:

- `:coverpage-image:`
_Comma-delimited list_ of image locations, for images to be included on the PDF cover page (and title page for logos). All image locations are relative to the source document.

**Comment by ronaldtse** [comment]
@Intelligent2013 I agree that it's easier to have the background include the logos. We just need to find a way to insert the second cover page even though it's not critical right now.

**Comment by opoudjis** [comment]
Done, code identical to BSI, images end up in metanorma-extensions/presentation-metadata:

````
       <metanorma-extension>
         <presentation-metadata>
           <name>coverpage-image</name>
           <value>
             <image src="images/image1.gif"/>
             <image src="images/image2.gif"/>
           </value>
         </presentation-metadata>
...
````
