### ISSUE TITLE
Support the attribute 'document-scheme'

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-itu#507]
Source issue: https://github.com/metanorma/metanorma-itu/issues/474

We need to support the document attribute `:document-scheme:` to switch the PDF styles between old and new  (similar to ISO).

I've tried to add:
```
:document-scheme: legacy
```
but ITU Metanorma XML doesn't contain
```
<presentation-metadata><name>document-scheme</name><value>legacy</value></presentation-metadata>
```

**Comment by ronaldtse** [comment]
Is this a “document scheme” or a “layout scheme”?

**Comment by Intelligent2013** [comment]
> Is this a “document scheme” or a “layout scheme”?

@ronaldtse in metanorma-iso, the alternative PDF layout specification supported by the attribute `:document-scheme:`
https://github.com/metanorma/metanorma-iso/issues/1080#issuecomment-1918692734.

**Comment by opoudjis** [comment]
I do not wish to differentiate document schemes and layout schemes, that's just going to lead to confusion.

**Comment by opoudjis** [comment]
I'm going to bite the bullet, and make document-scheme an attribute available to all flavours in metanorma.

**Comment by opoudjis** [comment]
Legal values: `current` and `legacy`.
