### ISSUE TITLE
Document attribute for slogan

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-itu#508]
Source issue: https://github.com/metanorma/metanorma-itu/issues/474

Besides the main and sub titles, ITU allows the 'slogan':
![image](https://github.com/metanorma/metanorma-itu/assets/5559926/9391f19f-61b3-4ecb-8a6a-caf468e3af86)

We need so support it.

**Comment by opoudjis** [comment]
`:slogan-title`, ends up as `//bibdata/title[@type = "slogan"]`
