### ISSUE TITLE
Page number position differs from the original

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#52]
Both Roman and Arabic page numbers are set to be at the end of the page, always on the right, while they are on the right for odd and on the left for even pages in referent .doc.
[page_number_position.zip](https://github.com/metanorma/metanorma-itu/files/3725299/page_number_position.zip)

**Comment by opoudjis** [comment]
Huh, who knew. The even and off footers will not work unless `mso-facing-pages:yes;` is included in the `@page` template for Word CSS.
