### ISSUE TITLE
Spacing in items lists

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#53]
Items lists include space after dashes, while tab is used in referent .doc.
[spacing_in_lists.zip](https://github.com/metanorma/metanorma-itu/files/3725314/spacing_in_lists.zip)

**Comment by opoudjis** [comment]
In fact there was a tab there, but the style was so cramped that you could not see it. This should be fixed by #59.

[spacing_in_lists.doc.zip](https://github.com/metanorma/metanorma-itu/files/3746463/spacing_in_lists.doc.zip)
