### ISSUE TITLE
Cross-references names include more information

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#54]
Cross-references names (for ITU-T) are different than in referent .doc. They include date and sometimes additional information about ISO/IEC, e.g. [ITU-T Y.3500 (08/2014) | ISO/IEC 17788] instead of [ITU-T Y.3500].

[reference_name.zip](https://github.com/metanorma/metanorma-itu/files/3725371/reference_name.zip)

**Comment by opoudjis** [comment]
This issue is to be resolved in https://github.com/relaton/relaton-itu/issues/27 and https://github.com/relaton/relaton-itu/issues/28.
