### ISSUE TITLE
Line break after the term in Definitions section

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#55]
Definitions section: after the (bold) term, there is a line break, before the definition of that term.

[definitions_new_line.zip](https://github.com/metanorma/metanorma-itu/files/3725381/definitions_new_line.zip)

**Comment by anermina** [comment]
I think there is no need for opening new issue, since it is related to this one, so I will only write a comment: ITU-T reference is bold (it is in the title), and it shouldn't be.

**Comment by opoudjis** [comment]
The term was a boldfaced paragraph in the stylesheet, which was preserved from ISO, and which was assumed to be a separate paragraph from the definition. The reference was bold because the entire paragraph containing the term was bold.
