### ISSUE TITLE
Spacing in listed abbreviations and acronyms

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#56]
Abbreviations and acronyms: Spacing is larger between the listed abbreviations/acronyms.
Listed items are also indented, and they shouldn't be.

[spacing_abbreviations.zip](https://github.com/metanorma/metanorma-itu/files/3725403/spacing_abbreviations.zip)

**Comment by opoudjis** [comment]
Definition lists are indented in ITU, but there is not a compelling reason to do so. Left-aligning.

Paragraph separation in ITU as 6pt in general; that has already been addressed in previous fix.
