### ISSUE TITLE
Spacing between the items in the items list

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#59]
Spacing between the subsequent items in the items list is smaller than it should be.
(and dashes are longer, but I don't think this makes any formatting changes)

[spacing_item_list.zip](https://github.com/metanorma/metanorma-itu/files/3725478/spacing_item_list.zip)

**Comment by opoudjis** [comment]
ISO uses em-dashes as list bullets; ITU uses en-dashes.

ITU has 1.4cm hanging indent for bullet lists; ISO has 0.63cm.
