### ISSUE TITLE
Figures numbering

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#60]
Figures numbering is different than in referent .doc (e.g. Figure 1 instead of Figure 6-1).

[spacing_figures.zip](https://github.com/metanorma/metanorma-itu/files/3725485/spacing_figures.zip)

**Comment by opoudjis** [comment]
Practice is inconsistent in ITU documents; ITU J.383 for example has Figure 1, 2, 3, ... Table 1, 2, 3...

Because we would like to enforce uniform practice, and because the variation between documents is unmotivated, I'm going to decline to implement this. But @ronaldtse, please confirm with ITU that this is not essential to implement.

**Comment by ronaldtse** [comment]
@opoudjis I have asked ITU for clarification and will update the thread when confirmed.

**Comment by ronaldtse** [comment]
From ITU editing team:

>  There is freedom for authors to use either numbering, but prefer the one that starts anew with each higher-level clause number. Especially for documents that are long or which tend to change with time (for which amendments are made).

**Comment by opoudjis** [comment]
There shall be no pointless freedom for authors under my watch. Freedom for authors is what gets SDOs into messes like they find themselves to begin with.

This ticket is requesting per-chapter numbering of assets. This is a big task. Ticket reopened.

**Comment by ronaldtse** [comment]
> This ticket is requesting per-chapter numbering of assets. This is a big task. Ticket reopened.

We already do that in Annexes. Is this better being an option?

**Comment by opoudjis** [comment]
It's still a lot of code to adjust, and a lot of test code. Under a deadline that has not been extended, and that is completely impossible to meet. 

I think rendering options are a daft thing to offer, and we do not want our semantic markup to be burdened with them.

**Comment by ronaldtse** [comment]
> Under a deadline that has not been extended, and that is now completely impossible to meet. 

We can't do everything at once for a fixed deadline, I'm not saying we have to fix this now.

> I think rendering options are a daft thing to offer, and we do not want our semantic markup to be burdened with them.

I agree. Let me check with them.

**Comment by ronaldtse** [comment]
In the Editing Guide, the figure/table numbering requirement is explicit:

> Figures shall be numbered with Arabic numerals, beginning with 1 (within annexes or appendices, there will be a letter-plus-period or a Roman-numeral-plus-period prefix). This numbering shall normally be independent from the numbering of the clause and of any tables. For Recommendations which are very long or complex, however, the author may number figures sequentially with respect to the single digit clause number. For example, Figure 4-3 denotes the third figure in clause 4 of the Recommendation in which it is contained. 

This will need to be an overridable option.

**Comment by opoudjis** [comment]
FFS. I should have had this guide *in January*.

Then this needs to be an option propagated from Metanorma.

**Comment by opoudjis** [comment]
Subfigures also need to change from ISO, to have letters rather than numbers.
