### ISSUE TITLE
Sections numbering format

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#61]
Chapters/sections/subsections numbering:
- there are dots at the end of each number (e.g. chapter 7. instead of chapter 7, or section 7.1. instead of section 7.1)
- referent .doc uses some kind of alignment for titles, while generated .doc uses spaces between the numbers and titles (this can best be seen by comparing section titles 7, 7.1, 7.1.1 and 7.1.1.1 in referent and generated .doc)

[sections_numbering.zip](https://github.com/metanorma/metanorma-itu/files/3725508/sections_numbering.zip)

**Comment by opoudjis** [comment]
There is tab for the top level clauses, but not the lower level clauses in isodoc. That inconsistency is unjustified, certainly in ISO that isodoc derives from, so I will refactor the space delimiter, and make it consistent.

**Comment by opoudjis** [comment]
Ticket never actually closed!
