### ISSUE TITLE
Font size in tables

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#64]
Font size in tables is generally smaller than it should be. However, some of the fields have larger font size than others (e.g. "Derived requirements" in Table II.4).

[table_font_size.zip](https://github.com/metanorma/metanorma-itu/files/3725550/table_font_size.zip)

**Comment by opoudjis** [comment]
Table text in ISO is 10pt, in ITU is 11pt.

The Derived Requirements is a list embedded in a table, and there is no rule right now to reduce its size.

**Comment by opoudjis** [comment]
Setting `table.MsoISOTable p {font-size: 11pt}` addresses this. Propagating to all other Word stylesheets.
