### ISSUE TITLE
References (bibliography) formatting

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#68]
References section: 
- reference name is different, doesn't include the word "Recommendation", uses italic for the recommendation's name and includes both month and year, instead of year only
- justification is needed
- there is no dot after each reference

[references.zip](https://github.com/metanorma/metanorma-itu/files/3726047/references.zip)

**Comment by opoudjis** [comment]
Adding ITU to the class of citation references that we do not prefix the organisation name to, since the organisation name is already part of the reference code.

**Comment by opoudjis** [comment]
References: there is no justification in the sources.

Dot added.

The titles are not being fetched correctly: the identified needs to be stripped from the title in relaton-itu.

**Comment by opoudjis** [comment]
The reference format needs to change from the current:

* [identifier] tab _Title_.

to:

* [identifier] tab identifier (year of publication), _Title_.

ITU instances are prefixed by "Recommendation".

**Comment by opoudjis** [comment]
Everything else addressed, but waiting for relaton/relaton-itu#26.

**Comment by opoudjis** [comment]
Also pending https://github.com/relaton/relaton-itu/issues/27
