### ISSUE TITLE
Different sizes and alignments of figures

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#69]
Figures have different sizes than in referent .doc (some of them are bigger, some of them are smaller) and some of them are not aligned properly:
- 6.3.1. Single processing unit type: Figure 3 is bigger than in referent .doc
- 6.3.2. Multi-processing unit type: Figure 4 is smaller than in referent .doc
- Table II.1: figure included in the table is smaller than it should be
- Table II.2: figure included in the table is smaller than it should be
- Table II.3: figure included in the table is smaller than it should be
- Table II.4: figure included in the table is smaller than it should be 
- Table II.8: figure included in the table is smaller than it should be
- Table II.5: figure is larger than it should be; it should be aligned to the left and the text should be on the right, next to the figure
- Table II.7: figure is larger than it should be; it should be aligned to the left and the text should be on the right, next to the figure
- Table II.6: figure should be aligned to the left and the text should be on the right, next to the figure
- Table II.9: one figure is missing, the other one is bigger than it should be
- Table II.10: figure is bigger than it should be 

[figure_size.zip](https://github.com/metanorma/metanorma-itu/files/3730614/figure_size.zip)

**Comment by anermina** [comment]
.zip file is updated with .doc file

**Comment by anermina** [comment]
Comments above refer to Y.3507 file. File G.650 has the same issue with the following figures:
- Figure 3 is smaller than it should be
- Figure 4 is smaller than it should be
- Figure 5 is smaller than it should be
- Figure 6 is larger than it should be
- Figure 7 is smaller than it should be
- Figure 8 is larger than it should be
- Figure 9-1 is smaller than it should be
- Figure 9-2 is smaller than it should be
- Figure 10-1 is smaller than it should be
- Figure 10-2 is smaller than it should be
- Figure 11 is smaller than it should be
- Figure 12 is smaller than it should be
- Figure 13 is smaller than it should be
- Figure 14 is smaller than it should be
- Figure 15 is smaller than it should be
- Figure 16 is smaller than it should be
- Figure 18 is smaller than it should be
- Figure 19 is smaller than it should be
- Figure I.1 is smaller than it should be
- Figure II.1 is smaller than it should be
- Figure IV.1 is smaller than it should be
- Figure IV.2 is smaller than it should be
- Figure IV.3 is smaller than it should be
- Figure V.1 is smaller than it should be
- Figure V.2 is smaller than it should be
- Figure V.3 is smaller than it should be

[figure_size_g650.zip](https://github.com/metanorma/metanorma-itu/files/3731572/figure_size_g650.zip)

**Comment by opoudjis** [comment]
The size of the figure is something I'm not comfortable micromanaging in Word. Metanorma currently tries to maximise the image size in Word to 400pt width or 680pt height, which should be the largest image size Word can deal with.

**Comment by opoudjis** [comment]
@ronaldtse Please confirm that the image size of Word output is acceptable to ITU.

**Comment by opoudjis** [comment]
Let me review these, they seem to be separate issue:

Table II.5: figure is larger than it should be; it should be aligned to the left and the text should be on the right, next to the figure
Table II.7: figure is larger than it should be; it should be aligned to the left and the text should be on the right, next to the figure
Table II.6: figure should be aligned to the left and the text should be on the right, next to the figure
Table II.9: one figure is missing, the other one is bigger than it should be

**Comment by opoudjis** [comment]
I'm... going to say no to these from Y.3507:

* II.5: Text wrap around image: a luxury, and will usually end up going horribly wrong.
* II.6: Ditto
* II.7: Ditto

For all of these, we can set the image to a smaller size with image attributes `[height=xxx,width=auto]` (although it will be trial and error to get these right with Word.) Honestly, I wouldn't bother.

The second image is indeed missing from the source; not sure what has happened, but I'll fix the source. @tgolubev failed to see this...

**Comment by ronaldtse** [comment]
> @ronaldtse Please confirm that the image size of Word output is acceptable to ITU.

I don't see an alternative except manual resizing.
