### ISSUE TITLE
Display part-of relation if this doc is an Annex of another

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-itu#7]

**Comment by opoudjis** [comment]
@ronaldtse to provide exemplar.

**Comment by ronaldtse** [comment]
Exemplar documents (Z.100) are already provided in mn-itu-docs.

**Comment by opoudjis** [comment]
This task is more complicated:

* Annexes have identifiers, and those identifiers need to be used as the ID of the annex, which is the content of the document
* The title page is what is affected by the part-of information

**Comment by ronaldtse** [comment]
This is in fact the same problem with MPFD, a generic solution would work well here.

**Comment by opoudjis** [comment]
This is going to be an adhoc solution, because the very notion of publishing a document part separately from the parent document, with no access to its identifiers, is nonsense for document integrity.

Introducing two document attributes: `:annexid:` and `:annextitle:`.

**Comment by opoudjis** [comment]
Updated identifiers within an annex document, to use annexid. Updated title page.

**Comment by ronaldtse** [comment]
> This is going to be an adhoc solution, because the very notion of publishing a document part separately from the parent document, with no access to its identifiers, is nonsense for document integrity.

@opoudjis this is just like MPFD; we will see this again in new flavors. The point is that a sub-document can be processed into a document, and a document can be split into shorter documents. Is it possible to make this generic?

**Comment by opoudjis** [comment]
... Well, wait. All this has done is put an extra ID for the appendix into the document. It is not processing the annexes in tandem with the initial document, it's just adding an additional title. It's not doing much, and I'm not sure what it is doing is that generalisable.
