### ISSUE TITLE
Tables split into several pages - no title and 1st row repetition

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#70]
When table is too long to fit to one page, its title and the first row of that table should be on the second and each following page where that table appears.

[large_tables.zip](https://github.com/metanorma/metanorma-itu/files/3726134/large_tables.zip)

**Comment by opoudjis** [comment]
First requirement to get repeating headings to work is in markup: there needs to be a blank line  between the first (header) and second line of the table:

````
[[table-i-1]]
.OCP related specifications
|===
^.^| *Family* ^.^| *Specification* ^.^| *Summary* ^.^| *Published*

.8+<.<| OpenRack V2 <.<| Twin Lakes 1S Server Design Specification V1.00 <<b-OCP_1S>> <.<v| This specification describes the design of the Twin Lakes 1S server based on the Intel Xeon
Processor D-2191 System-on-a-Chip (SoC). ^.^| 2018
````

As it turns out, if a table does have a distinct thead in Word, its headings will automatically repeat in Word. The reason that is not happening is that the style command `mso-table-anchor-vertical:paragraph;` is conflicting with it. I need to ensure that I can get rid of that styling without damaging anything.

**Comment by opoudjis** [comment]
And I cannot get rid of that style command, because it is needed to enforce spacing after tables: https://github.com/metanorma/metanorma-iso/issues/234

**Comment by opoudjis** [comment]
To my disgust, the only way I can see to resolve this is to postprocess the Word document, find all paragraphs following tables, and increase the spacing before them in CSS. This is very disruptive, and will need a lot of testing; I do not wish to prioritise it given the long backlog. We had massive trouble with the profusion of tables in ISO 8601, which led to introducing this table positioning to begin with.

**Comment by opoudjis** [comment]
In fact, tables are now wrapped in div, so we should be able to avoid any nonsense with frames anyway, by setting margin-bottom on the wrapper div.

**Comment by opoudjis** [comment]
I am also going to create a metanorma.css in isodoc, rather than perpetually update child gems with generic CSS, and without embarking on CSS refactoring of the kind that has bogged the HTML down for months. The metanorma.css will be thin.
