### ISSUE TITLE
Table formatting (different style)

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#71]
History section: 
- different table style
- footnote is written below the table, not at the end of the page
- for ITU-Ts Amd. and Cor., there should be a tab before the title in the table

[table_formatting.zip](https://github.com/metanorma/metanorma-itu/files/3726279/table_formatting.zip)

**Comment by opoudjis** [comment]
The bold facing is an error in markup: all cells have been marked up as header cells (`<.<h| 1.0`), none should be. I will change the source documents.

I am *very* reluctant to change the positioning of table footnotes from the Metanorma default, it will be very difficult. Asking @ronaldtse if ITU will insist on this.

Turning off gridlines: I am doing so as a one-off for these history tables.

I am not injecting random tabs in front of Amendment, Correction document identifiers, and I am not centering the headers. @ronaldtse Please confirm this is not seen as vital.
