### ISSUE TITLE
Different font sizes and spacing in general

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#72]
Due to the different font sizes and spacing, some of the pages don't have the exact same content in generated and referent .doc. For specific cases such as notes and items lists, separate GitHub issues were opened. The rest of the differences causing these issues are as follows: 
- titles of figures have smaller font size - therefore, in original .doc some of the labels are in multiple paragraphs, while they are in one in the generated .doc -> example in G.650
- font size for titles of subsections is smaller than it should be (level x.1.1 and x.1.1.1) -> example in Y.3507
- font size for titles of tables is smaller than it should be -> example in Y.3507
- appendices have smaller font size for the title and subtitle -> example in Y.3507
- text is not justified -> example in Y.3507
- there is a bigger spacing between the title/subtitle and the first paragraph -> example in Y.3507
- there is a bigger spacing between paragraphs -> example in Y.3507
- there is a bigger spacing between sections and subsections -> example in Y.3507

[formatting_issues.zip](https://github.com/metanorma/metanorma-itu/files/3726362/formatting_issues.zip)

**Comment by anermina** [comment]
Solved by an updated done by @opoudjis :
- titles of figures have smaller font size - therefore, in original .doc some of the labels are in multiple paragraphs, while they are in one in the generated .doc -> example in G.650
- font size for titles of tables is smaller than it should be -> example in Y.3507
- appendices have smaller font size for the title and subtitle -> example in Y.3507
- there is a bigger spacing between the title/subtitle and the first paragraph
- there is a bigger spacing between paragraphs
- there is a bigger spacing between sections and subsections 

Remaining issues:
- text is not justified (the issue remained only in the items lists) -> justification_lists.zip
- font size for titles of subsections is smaller than it should be (level x.1.1 and x.1.1.1)  -> spacing_subsec.zip

Additionally:
- spacing before subsections at level 3 (e.g. 3.3.1) and 4 (e.g. 3.3.1.1) should be checked (I didn't find any markup issue here yet, but it seems that spacing is smaller than it should be) -> spacing_subsec.zip

[spacing_subsec.zip](https://github.com/metanorma/metanorma-itu/files/3741238/spacing_subsec.zip)

[justification_lists.zip](https://github.com/metanorma/metanorma-itu/files/3741256/justification_lists.zip)

**Comment by opoudjis** [comment]
Font size of definitions terms has been fixed already. Spacing fixed now; also putting 6pt as bottom spacing for all headers.

**Comment by anermina** [comment]
Spacing between the title/subtitle and the first paragraph is now bigger than it should be.

Example from ITU-T Editing Guidelines:
![image](https://user-images.githubusercontent.com/55683568/68087949-d96fb800-fe5a-11e9-8844-122db8f1a3a0.png)

[spacing2.zip](https://github.com/metanorma/metanorma-itu/files/3801734/spacing2.zip)

**Comment by opoudjis** [comment]
The Word template has a style "Normalaftertitle", which has a space of 18pt before.  I assumed that this applied after all titles. The distribution of Normalaftertitle is not specified in the ITU Editing Guidelines; but from the sample documents we publish, it is clearly not used after all section titles; instead, it appears:

* Immediately after annex titles
* Immediately after figure captions
