### ISSUE TITLE
Spacing in equations

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#74]
There is a bigger spacing between symbols and characters (e.g. two subsequent integrals) in equations, which makes them much wider than in original .doc.

[spacing_equations.zip](https://github.com/metanorma/metanorma-itu/files/3726389/spacing_equations.zip)

**Comment by opoudjis** [comment]
Nermina, you will need to pull the new Gemfile for mn-samples-itu, so you can fetch the latest html2doc as well.

**Comment by anermina** [comment]
Thank you, Nick. I pulled the new Gemfile.
