### ISSUE TITLE
Size of the brackets in equations

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#75]
Equations: brackets size doesn't auto-fit in .doc like in .html, so most of the brackets are smaller than they should be (e.g. when there is a fraction, bracket size is a half of the fractions' size).

[brackets_equations.zip](https://github.com/metanorma/metanorma-itu/files/3726392/brackets_equations.zip)

**Comment by opoudjis** [comment]
This is the same issue as https://github.com/metanorma/metanorma-nist/issues/26, and I'm merging this issue into that.
