### ISSUE TITLE
Cross-referencing format doesn't match the original

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#76]
Cross-referencing format doesn't match with original .doc:
- when equation is cross-referenced, clause from where the equation origins is also noted (although mostly it's not in referent .doc)
- cross-references for notes are in format "see Clause 3.3.7, Note 2" in generated .doc, while in original .doc it is referred to some note in the format "see Note 2 in clause 3.3.7" (referencing to notes was rare in the documents, so it cannot be stated that original files always refer to notes like this, but maybe it is worth mentioning this difference)

[cross_referencing.zip](https://github.com/metanorma/metanorma-itu/files/3726441/cross_referencing.zip)

**Comment by opoudjis** [comment]
* I can change the Metanorma default of "Clause 3.3.7, Note 2" to "Note 2 in clause 3.3.7", but I would like confirmation from ITU that this is desirable. @ronaldtse 
* Referencing the containing clause for equations is not necessary if they are consecutively numbered through the document, and you have noted that the source document is inconsistent. I am inclined not to action, but this also needs confirmation from ITU. @ronaldtse

**Comment by ronaldtse** [comment]
@opoudjis I have confirmed with ITU.

They will standardize with "OBJ # in clause N", i.e. "Note 2 in clause 3.3.7” and “Equation 2 in clause 3.3.7”.

**Comment by opoudjis** [comment]
Empty xrefs are being treated as containers. Oh noes...

**Comment by opoudjis** [comment]
Poor detection of error condition in isodoc, if the citation is missing. Fixing.
