### ISSUE TITLE
Figure appears on one page, its title on the other

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#77]
If label of the figure cannot fit to the same page as the figure itself, it will appear on the following page.

![fig8_g-650](https://user-images.githubusercontent.com/55683568/66783432-2bff2980-eed8-11e9-9b81-9476a85d7fb1.PNG)

**Comment by opoudjis** [comment]
The Word stylesheets all have `page-break-before: avoid`; that works in a small sample document, but it clearly is being ignored here. `page-break-inside: avoid` on the containing div is also being ignored. I am going to have to wrap any captioned pictures in Word in paragraphs, and make those paragraphs be `page-break-after: avoid`, in isodoc postprocessing.
