### ISSUE TITLE
Sections numbering duplication

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#79]
Section numbers are duplicated in some cases (G.650 document), e.g.:
- II.1. II.1 General
- II.2 II.2 Test apparatus

[numbering_duplication.zip](https://github.com/metanorma/metanorma-itu/files/3731483/numbering_duplication.zip)

**Comment by opoudjis** [comment]
That's not duplication, that's simply a markup error: the numbers need to be removed from the title:

````
[[a_IV_1_2_1Optical_source]]
===== IV.1.2.1 Optical source
````

to 

````
[[a_IV_1_2_1Optical_source]]
===== Optical source
````

I am emending the documents.
