### ISSUE TITLE
Title appears for un-titled tables

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#80]
In case table caption/title/label is not specified, its numbering still appears as the title of that table, e.g. "Table III". In referent .doc, there is no title at all in this case.

[tables_wo_title.zip](https://github.com/metanorma/metanorma-itu/files/3731597/tables_wo_title.zip)

**Comment by ronaldtse** [comment]
@anermina all ITU tables must be reference-able and therefore must be numbered. Closing.

**Comment by opoudjis** [comment]
That is simply not true, Ronald. At all.  The history of the document in G.650 is a table, and it needs to have the title suppressed, because no doubt ITU do not consider it referencable: that's certainly how they've authored it in source.

**Comment by ronaldtse** [comment]
So this ticket is only specific to the history table, fine to reopen it. The original ticket did not explain this.

**Comment by opoudjis** [comment]
Actually, while it applies to History, it also applies to the table in G.650, Appendix III, which is the example @anermina brings up.

It is entirely reasonable to say that G.650, Appendix III should not have skipped its table numbering, and this was an inconsistency in markup. But this issue does need to be addressed for instances like the History table, anyway.

**Comment by opoudjis** [comment]
The good news is, this is just a markup issue. If you put `[%unnumbered]` in front of any table, it will not get a caption. I will adjust the documents on mn-samples-itu to have unnumbered History tables.

The bad news is, there is no space now between the preceding paragraph and the uncaptioned table.

**Comment by opoudjis** [comment]
In postprocessing, we need to replace

`<p class="TableTitle" style="text-align:center;"></p>`

which skips the paragraph completely, and fails to put any space before the table, with

with

`<p class="TableTitle" style="text-align:center;font-size:0pt">&nbsp;</p>`
