### ISSUE TITLE
Confirm ITU Recommendation Table/Figure numbering

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#81]
> Practice is inconsistent in ITU documents; ITU J.383 for example has Figure 1, 2, 3, ... Table 1, 2, 3...

For example:

* In J.383, they go by Figure 1, 2, 3, ... Table 1, 2, 3
* In Y.3507, it is Figure 6-1, Figure 6-2
* Some other documents have Table 2-1, etc.

Which scheme should be the one used moving ahead?

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-itu/issues/60#issuecomment-543765700_

**Comment by ronaldtse** [comment]
I've asked ITU for clarification, pending reply.

**Comment by opoudjis** [comment]
You got clarification in #60. Closing.

**Comment by ronaldtse** [comment]
Thanks!
