### ISSUE TITLE
Alignment in the Summary section

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#82]
Summary: years are aligned on the right instead on the left (only separator :: is used between the year and the rest of the text). 

![image](https://user-images.githubusercontent.com/55683568/67143719-88fb3680-f26e-11e9-8294-00fba46e43f9.png)
[years-alignment.zip](https://github.com/metanorma/metanorma-itu/files/3746561/years-alignment.zip)

**Comment by opoudjis** [comment]
What is actually happening is that the definition list is being rendered as a table, and the table is indented. That indentation has been removed in a recent fix. Within the table itself, as it turns out, the left cells are in fact left-aligned; you're just not seeing it because of autowidth.
