### ISSUE TITLE
Footer text size, position and justification

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#83]
Font size is smaller than it should be for "Rec. ITU-T G.650.1 (03/2018)" in the footer. Text spans into two rows.

![image](https://user-images.githubusercontent.com/55683568/67143813-9664f080-f26f-11e9-91f5-45d91108f63e.png)
[years-alignment.zip](https://github.com/metanorma/metanorma-itu/files/3746574/years-alignment.zip)

**Comment by opoudjis** [comment]
Already fixed
