### ISSUE TITLE
Text in the table doesn't have a proper vertical alignment

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#85]
In the rendered .doc files, text in the left column is vertically centered, while it should be aligned to the top. I thought this was only a markup issue, but after adding ".<" in order to properly align the text, alignment didn't change.

![image](https://user-images.githubusercontent.com/55683568/67145444-0aa88f80-f282-11e9-9768-d2e95207667d.png)
[verical_align_top.zip](https://github.com/metanorma/metanorma-itu/files/3746695/verical_align_top.zip)

**Comment by opoudjis** [comment]
There's two decision points here: 

* Should the general style for ITU tables be valign=middle in Word? @ronaldtse Query for ITU.
* Should we allow tables in Metanorma to be customised to have  either user-specified horizontal or vertical alignment? We have avoided that to date, and I think it is best practice to continue to: we would not expect tables to vary arbitrarily within a document.

I am going to implement valign=top for now in generic tables in ITU.

**Comment by ronaldtse** [comment]
@anermina also notice that the table on the left does not have the "bolding" set for headers: is the table header not set? Or is this an HTML rendering problem?

**Comment by ronaldtse** [comment]
@anermina also, notice the content in the "Summary" cells in the right table (first two rows) are different. The left table first two rows have two paragraphs conflated.

**Comment by anermina** [comment]
@ronaldtse This table is from Y.3507 specification, which I haven't been working on since the very beginning. I've made these changes later. The last pull request was because of them. This is how the table currently looks like: 
![image](https://user-images.githubusercontent.com/55683568/67215519-e388c400-f421-11e9-9b2e-dc56a6a84fb0.png)

At first I thought that there should be two paragraphs in the first row, but then I concluded that it's actually one paragraph and that it differs only because of the difference in column width in the original and generated document. If you think this should be separated into two paragraphs, I'll make that change as well.

**Comment by ronaldtse** [comment]
I'm still waiting for ITU clarification, will update here once I get it.

**Comment by ronaldtse** [comment]
Clarification from ITU:

> - Horizontally, text is left-aligned and values are center-aligned.
> - Vertically, both text and values are top-aligned.

I'm not sure how we can ensure that we know what is the column for "text" vs "value"... Thoughts?

**Comment by opoudjis** [comment]
Numerical vs alphanumeric is all I can think of, but that needs clarification

**Comment by ronaldtse** [comment]
ITU: authors should be able to encode whether a column is text or value.

**Comment by opoudjis** [comment]
Oh FFS.

We will have to add an idiosyncratic "value" attribute for each column, which gets parsed and applied to cells. (Even if HTML 5 allows per-column styling, Word via HTML 4 does not.)

**Comment by ronaldtse** [comment]
The alternative is to ask the user to do the alignment, but will be error prone.

**Comment by opoudjis** [comment]
This IS asking the user to do it, really...

**Comment by opoudjis** [comment]
Given that vertical alignment is fixed, and horizontal alignment is user determined, we need only mark this up via horizontal alignment:

````
[<,^,^,<]
|===
| Text | Value | Value | Text 

| Table | 121 | 0.1 | Other table
|===
````

This will work, and needs no intervention in markup.

@anermina and @manuel489, I don't know what the criteria are for text and values, but please encode the column horizontal alignment you find in your tables accordingly.

**Comment by ronaldtse** [comment]
The point is this must be communicated to ITU authors. Can you help document this in metanorma.com for ITU authors?

**Comment by opoudjis** [comment]
It's native Asciidoc behaviour, but OK.

**Comment by anermina** [comment]
> Clarification from ITU:
> 
> > * Horizontally, text is left-aligned and values are center-aligned.
> > * Vertically, both text and values are top-aligned.
> 
> I'm not sure how we can ensure that we know what is the column for "text" vs "value"... Thoughts?

Just to double-check: this doesn't apply to the titles of columns (first row of the table)? I think they are all horizontally centered in the original documents.

**Comment by ronaldtse** [comment]
@anermina actually you are 100% correct. Now I realized we made a mistake with the documentation... argh.

**Comment by opoudjis** [comment]
Which @ronaldtse  has now fixed....

... Very good catch, @anermina! I am very happy you're working with us!

**Comment by ronaldtse** [comment]
This task is completed via https://github.com/metanorma/metanorma.com/pull/168
