### ISSUE TITLE
Add ITU document type: "Resolution"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#88]
Example: https://www.itu.int/dms_pub/itu-t/opb/res/T-RES-T.1-2008-PDF-E.pdf

**Comment by opoudjis** [comment]
The formatting of this document is quite different. For now, I'm ignoring. @ronaldtse Can I ignore the idiosyncratic rendering in general?

**Comment by opoudjis** [comment]
... I will: that is a huge task, which requires document samples and Word stylesheets.

**Comment by ronaldtse** [comment]
This is a placeholder task, not acting on it now.

**Comment by opoudjis** [comment]
Has just been done via https://github.com/metanorma/metanorma-itu/issues/133
