### ISSUE TITLE
ITU Editing Guidelines: Implement citations of standards

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#89]
From ITU Editing Guidelines:

![image](https://user-images.githubusercontent.com/11865/67157246-1ff1ec80-f35c-11e9-94e0-00bc2d8676f0.png)

Taking ITU-T Y.3500 as an example, it has two identifiers, so it is considered to be case 2:

"Identical Recommendation | International Standard (or "common text")": both identifiers should be shown in the citation.

Relevant issue in Relaton from: https://github.com/relaton/relaton-itu/issues/28

**Comment by opoudjis** [comment]
Fixing only this issue: the series of recommendations is not something Relaton supports.
