### ISSUE TITLE
Gem is failing right now on mn-itu-documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-itu#9]
Got something like "Can't run "|" on "recommendation".

This is becoming an official flavor and it has to remain stable. Thanks!

**Comment by opoudjis** [comment]
It is not going to become stable until rspec exists for the gem.  And that is going to take a week of me not doing anything else.

**Comment by opoudjis** [comment]
Fixed, but now I'm starting on rspec for metanorma-itu.
