### ISSUE TITLE
Spacing and alignment in annexes and appendices

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#92]
In case annex/appendix begins with some text (without a separate section), spacing between the title and the text should be bigger.

Title "Annex <number>" should be centered (there is some misplacement of title or subtitle).

[appendix_spacing.zip](https://github.com/metanorma/metanorma-itu/files/3763644/appendix_spacing.zip)

![image](https://user-images.githubusercontent.com/55683568/67418189-9bf16c00-f5ca-11e9-9823-8c3ff9376587.png)

**Comment by opoudjis** [comment]
Fixed centering.

The added space is in fact produced by applying a Normal_after_title style after all titles. I will automate it.
