### ISSUE TITLE
Text duplication in Definitions section

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#93]
"This Recommendation uses the following terms defined elsewhere:" is duplicated after the subtitle "Terms defined elsewhere".

![image](https://user-images.githubusercontent.com/55683568/67593446-6b443a80-f762-11e9-840b-abcc89dc54d9.png)
[duplicated_text.zip](https://github.com/metanorma/metanorma-itu/files/3773212/duplicated_text.zip)

**Comment by opoudjis** [comment]
That's a bug not a feature. :-) Please remove the text "This Recommendation uses the following terms defined elsewhere:" from the Asciidoctor source; it is inserted automatically.

**Comment by opoudjis** [comment]
the part of the text that is repeating is not written in .adoc at all

**Comment by opoudjis** [comment]
I was inserting the term in both the XML and the HTML separately.
