### ISSUE TITLE
Differences in footnotes included in the table

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#94]
Differences in footnotes included in a table:
- In the footnote description, footnote labels have bigger font size.
- Bracket ")" is missing in the footnote labels (they are labeled as a, b, c,...). 
- There is a bigger spacing after the footnote label and its description.
- Footnote description is indented in the first row only.

![image](https://user-images.githubusercontent.com/55683568/67595534-3090d100-f767-11e9-8c5c-03af106e3a82.png)

[table_style.zip](https://github.com/metanorma/metanorma-itu/files/3773309/table_style.zip)

**Comment by opoudjis** [comment]
ITU have set the hanging indents on table footnotes in this document MANUALLY. Their template for table footnotes has made no provision for hanging indents, and I will need to emend this in the stylesheet.

This of course is exactly why ITU needs a tool like Metanorma. Or at least, a properly maintained stylesheet...

**Comment by opoudjis** [comment]
Needs several fixes. Word footnote target (footnote label) needs to be `<span>`, not `<a>`, in order to render correctly. TableFootnoteRef style needs to inherit from Footnote Reference. Local realisation of footnote reference needs to insert bracket. Local table footnote style needs hanging indent. Local table footnote needs 2pt before and after, although before it was 4pt, so it should have looked the same.

**Comment by anermina** [comment]
Is there a possibility to also add a bracket ")" in the text where the footnote is inserted? 
Currently, ITU-T Editing Guidelines document renders like this:
![image](https://user-images.githubusercontent.com/55683568/68091325-a50df300-fe7e-11e9-994a-32065b40902b.png)
while it should be rendered like this:
![image](https://user-images.githubusercontent.com/55683568/68091334-b525d280-fe7e-11e9-85f6-1d49f67124a1.png)

**Comment by opoudjis** [comment]
Yes, goes into queue

**Comment by opoudjis** [comment]
I'd converted the target but not the link as well. Fixing.

**Comment by opoudjis** [comment]
Solution superseded by that in metanorma/metanorma-iso#301
