### ISSUE TITLE
URL font size should be smaller

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#96]
URL font size is smaller in the original document.

![image](https://user-images.githubusercontent.com/55683568/67596876-08ef3800-f76a-11e9-9f72-a92f3e3ddeb0.png)
[url_size.zip](https://github.com/metanorma/metanorma-itu/files/3773385/url_size.zip)

**Comment by opoudjis** [comment]
And in a different font too.

**Comment by opoudjis** [comment]
Am not updating HTML stylesheet at this time.
