### ISSUE TITLE
Spacing in (regular text) footnote description

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#97]
In the regular footnote descriptions, spacing should be bigger between the footnote label and the footnote description.

![image](https://user-images.githubusercontent.com/55683568/67597379-4b654480-f76b-11e9-8395-b0d4a115be5f.png)
[footnote.zip](https://github.com/metanorma/metanorma-itu/files/3773412/footnote.zip)

**Comment by opoudjis** [comment]
Footnotes in Word have tab after reference number.
