### ISSUE TITLE
Different conventions in #20?

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#98]
It seems to me that "Author's guide for drafting ITU-T Recommendations" defines some values (such as footer content) differently than other ITU-T recommendations.

Is there an option to solve the following issues by making some mark-up changes:
1. Remove the word "SERIES" from the front page?
2. Remove "Recommendation ITU-T EDITING GUIDELINES" from the end of the front page and from the beginning of the page with Summary and History?
3. Change footer content from "Rec. ITU-T EDITING GUIDELINES (02/2016)" to "Author's guide for drafting ITU-T Recommendations"? Unlike the other recommendations, footer content in "Author's guide for drafting ITU-T Recommendations" is document title and not "Recommendation ITU-T" + value of :docnumber: + date.
4. Remove the page with Foreword, Note and Intellectual Property Rights?
5. Change "Recommendation ITU-T EDITING GUIDELINES" to "Recommendation ITU-T A.1500" (with footnote after 1500) at the beginning of page with Scope, References and Definitions?

![image](https://user-images.githubusercontent.com/55683568/67602447-e6175080-f776-11e9-8f0f-3ddef5f2bef3.png)
[front_page.zip](https://github.com/metanorma/metanorma-itu/files/3773717/front_page.zip)

**Comment by opoudjis** [comment]
None of these would be resolved with markup: they are all changes to underlying templates, and my understanding is, we are not providing different templates for different document types without explicit go-ahead. @ronaldtse?

**Comment by anermina** [comment]
One more difference: there is a subtitle on the page with Scope, References and Definitions in the original .doc file
![image](https://user-images.githubusercontent.com/55683568/68088051-7f232700-fe5b-11e9-8f51-88d5ff14cf00.png)

**Comment by ronaldtse** [comment]
@anermina thanks for the report, just one request — could you post the two images separately so that they can be easily compare in a smaller screen? Right now if the browser is slightly narrower I couldn’t compare the two. Thanks!

**Comment by anermina** [comment]
Sure.

Original:
![image](https://user-images.githubusercontent.com/55683568/68088180-c0680680-fe5c-11e9-9309-d0ae76e0bc9c.png)

Rendered:
![image](https://user-images.githubusercontent.com/55683568/68088176-b6de9e80-fe5c-11e9-9c32-d22cfb1098d6.png)

**Comment by ronaldtse** [comment]
Appreciate it 😄

**Comment by ronaldtse** [comment]
> None of these would be resolved with markup: they are all changes to underlying templates, and my understanding is, we are not providing different templates for different document types without explicit go-ahead: there is too much else to fix right now to make this a priority, and we would need explicit document templates from them, rather than inferring them from documents

The key is this document is not a real "Recommendation A.1500", it's a generic document that looks like "Recommendation A.1500". We have two alternatives:

1. Treat it as Recommendation A.1500.
2. Treat it not as Recommendation A.1500.

I suggest we take the first approach since it is simpler, and accept all the Recommendation styling and requirements.

**Comment by ronaldtse** [comment]
@opoudjis please confirm choice 1 is acceptable.

**Comment by opoudjis** [comment]
... This truly is a generic document and not an ITU Recommendation, but part of our brief is streamlining, and I agree that it is more expedient and probably less confusing to treat this as an instance of an ITU Recommendation. The alternative is to make up a separate template for this one document, which... is not warranted.

I think there are some things I can do though:

> Remove the word "SERIES" from the front page?

Will remove SERIES if there is no value.

> Remove "Recommendation ITU-T EDITING GUIDELINES" from the end of the front page and from the beginning of the page with Summary and History?

No

> Change footer content from "Rec. ITU-T EDITING GUIDELINES (02/2016)" to "Author's guide for drafting ITU-T Recommendations"? Unlike the other recommendations, footer content in "Author's guide for drafting ITU-T Recommendations" is document title and not "Recommendation ITU-T" + value of :docnumber: + date.

No 

> Remove the page with Foreword, Note and Intellectual Property Rights?

No

> Change "Recommendation ITU-T EDITING GUIDELINES" to "Recommendation ITU-T A.1500" (with footnote after 1500) at the beginning of page with Scope, References and Definitions?

Yes

**Comment by ronaldtse** [comment]
OK

**Comment by opoudjis** [comment]
The inline subtitling with date is idiosyncratic, rejected.

The inline Recommendation ITU-T A.1500.... Hm. it is overriding a legitimate document identifier, and we can't currently do so in the text but not the cover.

**Comment by opoudjis** [comment]
I've made a crude solution for the latter in the document.
