### ISSUE TITLE
Shading only a specific row in a table

### ISSUE THREAD

**Issue by anermina** [metanorma/metanorma-itu#99]
Is there an option to change the color of a specific row in a table (not all odd/even rows, but just specified ones, as in the image below)?

![image](https://user-images.githubusercontent.com/55683568/67603163-6c806200-f778-11e9-9c6f-0cd71faa9ff6.png)

**Comment by opoudjis** [comment]
Not at this time. If we did introduce such an option, we would want to keep it as semantic as possible --- "shaded" as an attribute, with a boolean value. 

Would want approval from @ronaldtse and ITU before proceeding to implement it; we are trying to keep idiosyncratic formatting down to a minimum.

**Comment by ronaldtse** [comment]
From ITU:

> In Recommendations, rows are not, in principle shaded.
> Authors are free to request so, but that’s not something that happens often.

Confirmed that this does not need to be supported.

**Comment by ronaldtse** [comment]
Closing for now.
